import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "../seed_culture_metadata_batch"

const NORDIC_CULTURES: CultureBatchEntry[] = [
  {
    slug: "norse-viking-peoples",
    name: "Norsemen & Viking Culture",
    name_fi: "Skandinaavit ja viikingit",
    native_name: "Norðmenn",
    alternate_names: ["Norsemen", "Vikings"],
    culture_group: "Nordic",
    lineage_id: "nordic",
    historical_period: "Iron Age to Viking Age Scandinavia",
    year_start: -500,
    year_end: 1066,
    period_label: "500 BCE – 1066 CE",
    period_label_fi: "500 eaa. – 1066 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Norsemen",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Viikingit",
    wikidata_id: "Q25279",
    summary_en: "Seafaring North Germanic culture renowned for longship shipbuilding, runic inscriptions, Norse mythology (Odin, Thor), and expansive exploration and trading routes across the North Atlantic and Eastern European river systems.",
    summary_fi: "Skandinavian merenkulkijakansa, joka tunnetaan pitkäveneistään, riimukirjoituksistaan, skandinaavisesta mytologiastaan ja tutkimusretkistään Atlantin yli ja Itä-Euroopan jokireiteille.",
    capital: "Hedeby, Birka, Ribe",
    feature_name_matches: ["Norsemen"]
  },
  {
    slug: "kingdom-of-sweden",
    name: "Kingdom of Sweden",
    name_fi: "Ruotsin kuningaskunta",
    native_name: "Konungariket Sverige",
    alternate_names: ["Sweden", "Sweden–Norway", "Swedish Empire"],
    culture_group: "Nordic",
    lineage_id: "sweden",
    historical_period: "Medieval to Modern Northern Europe",
    year_start: 970,
    year_end: 2026,
    period_label: "970 CE – Present",
    period_label_fi: "970 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sweden",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ruotsi",
    wikidata_id: "Q34",
    summary_en: "Nordic constitutional monarchy rising under Gustavus Adolphus into a 17th-century Baltic stormakt, known for the Nobel Prize, innovative social welfare model, and sustained democratic peace.",
    summary_fi: "Pohjoismainen kuningaskunta, joka nousi Kustaa II Aadolfin johdolla 1600-luvulla Itämeren suurvallaksi ja tunnetaan Nobel-palkinnoistaan ja modernista hyvinvointiyhteiskunnastaan.",
    capital: "Stockholm, Sigtuna, Gamla Uppsala",
    feature_name_matches: ["Sweden", "Sweden–Norway"]
  },
  {
    slug: "kingdom-of-denmark",
    name: "Kingdom of Denmark",
    name_fi: "Tanskan kuningaskunta",
    native_name: "Kongeriget Danmark",
    alternate_names: ["Denmark", "Denmark-Norway"],
    culture_group: "Nordic",
    lineage_id: "denmark",
    historical_period: "Medieval to Modern Scandinavia",
    year_start: 936,
    year_end: 2026,
    period_label: "936 CE – Present",
    period_label_fi: "936 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Denmark",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Tanska",
    wikidata_id: "Q35",
    summary_en: "Europe's oldest continuous monarchy, unified by Gorm the Old and Harald Bluetooth around the Jelling Stones, controlling the Danish straits and presiding over the North Sea and Oldenburg realms.",
    summary_fi: "Euroopan vanhin yhtäjaksoinen monarkia, jonka Gorm Vanha ja Harald Sinihammas yhdistivät Jellingin kivien aikoihin ja joka hallitsi Tanskan salmia ja Itämeren sisäänkäyntiä.",
    capital: "Copenhagen, Roskilde, Jelling",
    feature_name_matches: ["Denmark", "Denmark-Norway"]
  },
  {
    slug: "kingdom-of-norway",
    name: "Kingdom of Norway",
    name_fi: "Norjan kuningaskunta",
    native_name: "Kongeriket Norge",
    alternate_names: ["Norway", "Kingdom of Norway"],
    culture_group: "Nordic",
    lineage_id: "norway",
    historical_period: "Medieval to Modern Northern Europe",
    year_start: 872,
    year_end: 2026,
    period_label: "872 CE – Present",
    period_label_fi: "872 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Norway",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Norja",
    wikidata_id: "Q20",
    summary_en: "Atlantic coastal nation unified by Harald Fairhair at the Battle of Hafrsfjord in 872, famous for deep glaciated fjords, stave churches, polar exploration (Nansen, Amundsen), and the Sovereign Wealth Fund.",
    summary_fi: "Harald Kaunotukan Hafrsfjordin taistelun (872) myötä yhdistämä rannikkovaltio, joka tunnetaan vuonoistaan, sauvakirkoistaan, naparetkeilijöistään ja valtion eläkerahastostaan.",
    capital: "Oslo, Bergen, Nidaros (Trondheim)",
    feature_name_matches: ["Norway", "Kingdom of Norway"]
  },
  {
    slug: "kalmar-union",
    name: "Kalmar Union",
    name_fi: "Kalmarin unioni",
    native_name: "Kalmarunionen",
    alternate_names: ["Kalmar Union"],
    culture_group: "Nordic",
    lineage_id: "nordic",
    historical_period: "Late Medieval Scandinavia",
    year_start: 1397,
    year_end: 1523,
    period_label: "1397 CE – 1523 CE",
    period_label_fi: "1397 jaa. – 1523 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kalmar_Union",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kalmarin_unioni",
    wikidata_id: "Q62623",
    summary_en: "Pan-Scandinavian personal union brokered by Queen Margaret I at Kalmar Castle in 1397, uniting the kingdoms of Denmark, Norway, and Sweden under a single monarch to balance the Hanseatic League.",
    summary_fi: "Kuningatar Margareetan Kalmarin linnassa 1397 solmima valtioliitto, joka yhdisti Tanskan, Norjan ja Ruotsin valtakunnat saman hallitsijan alaisuuteen Hansaliiton vastapainoksi.",
    capital: "Copenhagen, Kalmar",
    feature_name_matches: ["Kalmar Union"]
  },
  {
    slug: "iceland-commonwealth",
    name: "Icelandic Commonwealth & Republic of Iceland",
    name_fi: "Islannin vapaavaltio ja tasavalta",
    native_name: "Þjóðveldið Ísland / Ísland",
    alternate_names: ["Iceland", "Icelandic Commonwealth"],
    culture_group: "Nordic",
    lineage_id: "iceland",
    historical_period: "Viking Settlement to Modern North Atlantic",
    year_start: 930,
    year_end: 2026,
    period_label: "930 CE – Present",
    period_label_fi: "930 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Icelandic_Commonwealth",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Islannin_vapaavaltio",
    wikidata_id: "Q217834",
    summary_en: "North Atlantic volcanic island civilization founded by Norse settlers in 874, establishing the world's oldest surviving parliament (Althing) at Þingvellir in 930 and composing the Icelandic Sagas.",
    summary_fi: "Pohjois-Atlantin tuliperäisen saaren yhteiskunta, joka perusti maailman vanhimman yhä toimivan parlamentin (Althing) Þingvellirissä vuonna 930 ja kirjoitti maineikkaat islanninsaagat.",
    capital: "Reykjavík, Þingvellir",
    feature_name_matches: ["Iceland", "Icelandic Commonwealth"]
  },
  {
    slug: "republic-of-finland",
    name: "Republic of Finland",
    name_fi: "Suomen tasavalta",
    native_name: "Suomen tasavalta / Republiken Finland",
    alternate_names: ["Finland", "Suomi"],
    culture_group: "Nordic",
    lineage_id: "finland",
    historical_period: "Prehistoric to Modern Fennoscandia",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Finland",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Suomi",
    wikidata_id: "Q33",
    summary_en: "Nordic democracy known as the 'Land of a Thousand Lakes', preserving the national epic Kalevala, achieving independence in 1917, and celebrated globally for educational excellence and high happiness index.",
    summary_fi: "Tuhansien järvien maana tunnettu pohjoismainen demokratia, joka loi kansalliseepos Kalevalan, itsenäistyi vuonna 1917 ja tunnetaan huippukoulutuksestaan ja hyvinvoinnistaan.",
    capital: "Helsinki, Turku",
    feature_name_matches: ["Finland", "Suomi"]
  },
  {
    slug: "greenland-kalaallit",
    name: "Greenland (Kalaallit Nunaat)",
    name_fi: "Grönlanti (Kalaallit Nunaat)",
    native_name: "Kalaallit Nunaat",
    alternate_names: ["Greenland"],
    culture_group: "Nordic",
    lineage_id: "greenland",
    historical_period: "Thule Inuit & Nordic Greenland",
    year_start: 986,
    year_end: 2026,
    period_label: "986 CE – Present",
    period_label_fi: "986 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Greenland",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gr%C3%B6nlanti",
    wikidata_id: "Q223",
    summary_en: "The world's largest island, settled by Thule Inuit ancestors and Erik the Red's Norsemen in 986, maintaining unique Arctic maritime hunting traditions and autonomous governance within the Danish Realm.",
    summary_fi: "Maailman suurin saari, jonne inuiitit ja Eerik Punaisen skandinaavit asettuivat vuonna 986 ja joka yhdistää arktisen pyyntikulttuurin ja autonomisen itsehallinnon Tanskan valtakunnassa.",
    capital: "Nuuk (Godthåb)",
    feature_name_matches: ["Greenland"]
  }
]

const outPath = path.resolve(__dirname, "../../data-sources/batches/nordic.json")
fs.writeFileSync(outPath, JSON.stringify(NORDIC_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${NORDIC_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(NORDIC_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
