import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "../seed_culture_metadata_batch"

const CENTRAL_AFRICA_CULTURES: CultureBatchEntry[] = [
  {
    slug: "luba-empire",
    name: "Kingdom of Luba",
    name_fi: "Luban kuningaskunta",
    native_name: "Buluba",
    alternate_names: ["Luba Empire", "Luba"],
    culture_group: "Central Africa",
    lineage_id: "central-africa",
    historical_period: "Medieval to 19th Century Central Africa",
    year_start: 1585,
    year_end: 1889,
    period_label: "1585 CE – 1889 CE",
    period_label_fi: "1585 jaa. – 1889 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Luba",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Luba_(valtio)",
    wikidata_id: "Q854041",
    summary_en: "Pre-colonial Central African kingdom in modern southeastern DR Congo founded by King Kongolo Mwamba, revered for sacred divine kingship traditions, intricate wood-carving arts, and memory boards (lukasa).",
    summary_fi: "Keskiafrikkalainen kuningaskunta nykyisen Kongon demokraattisen tasavallan kaakkoisosassa, joka tunnettiin pyhästä kuninkuudesta ja symbolisista muistolaudoistaan (lukasa).",
    capital: "Mwibele",
    feature_name_matches: ["Luba"]
  },
  {
    slug: "lunda-empire",
    name: "Lunda Empire & Kingdom of Kazembe",
    name_fi: "Lundan valtakunta ja Kazembe",
    native_name: "Lunda",
    alternate_names: ["Lunda", "Kazembe", "Kingdom of Kazembe"],
    culture_group: "Central Africa",
    lineage_id: "central-africa",
    historical_period: "Early Modern Central Africa",
    year_start: 1665,
    year_end: 1887,
    period_label: "1665 CE – 1887 CE",
    period_label_fi: "1665 jaa. – 1887 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Lunda_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Lunda_(valtio)",
    wikidata_id: "Q686259",
    summary_en: "Expansive confederation founded by Mwaant Yaav in the Kasai and Luapula river basins, controlling ivory, copper, and salt trade from the Atlantic to the Indian Ocean via its eastern tributary state Kazembe.",
    summary_fi: "Kasai- ja Luapulajokien laaksojen suuri konfederaatio, jota hallitsi Mwaant Yaav ja joka valvoi norsunluun ja kuparin kauppareittejä Atlantin ja Intian valtameren välillä.",
    capital: "Musumba, Mwansabombwe",
    feature_name_matches: ["Lunda", "Kazembe"]
  },
  {
    slug: "kuba-kingdom",
    name: "Kingdom of Kuba",
    name_fi: "Kuban kuningaskunta",
    native_name: "Kuba",
    alternate_names: ["Bakuba Kingdom", "Kuba"],
    culture_group: "Central Africa",
    lineage_id: "central-africa",
    historical_period: "Early Modern Central Africa",
    year_start: 1625,
    year_end: 1900,
    period_label: "1625 CE – 1900 CE",
    period_label_fi: "1625 jaa. – 1900 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Kuba",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kuba_(kuningaskunta)",
    wikidata_id: "Q1479599",
    summary_en: "Federation of Bushongo clans unified by King Shyaam a-Mbul a-Ngoong in the central Congo basin, internationally famous for geometric raffia textiles, ceremonial royal portrait sculptures (ndop), and masquerades.",
    summary_fi: "Kongon altaan yhdeksäntoista etnisen ryhmän liittokunta, joka tunnetaan geometrisistä raffiakankaistaan, seremoniallisista naamioistaan ja kuninkaallisista puuveistoksistaan (ndop).",
    capital: "Nsheng",
    feature_name_matches: ["Kuba"]
  },
  {
    slug: "ndongo-kingdom",
    name: "Kingdom of Ndongo",
    name_fi: "Ndongon kuningaskunta",
    native_name: "Ndongo",
    alternate_names: ["Angola", "Ndongo", "Matamba"],
    culture_group: "Central Africa",
    lineage_id: "angola",
    historical_period: "Early Modern West-Central Africa",
    year_start: 1500,
    year_end: 1671,
    period_label: "1500 CE – 1671 CE",
    period_label_fi: "1500 jaa. – 1671 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Ndongo",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ndongo",
    wikidata_id: "Q1435272",
    summary_en: "Mbundu kingdom in northern Angola ruled by the Ngola, celebrated for fierce diplomatic and military resistance against Portuguese colonial conquest under Queen Nzinga Mbande of Ndongo and Matamba.",
    summary_fi: "Mbundukansan kuningaskunta Pohjois-Angolassa, joka tunnetaan kuningatar Nzingan nerokkaasta diplomatiasta ja vuosikymmeniä kestäneestä vastarinnasta Portugalin siirtomaajoukkoja vastaan.",
    capital: "Kabasa",
    feature_name_matches: ["Ndongo"]
  },
  {
    slug: "kingdom-of-kongo",
    name: "Kingdom of Kongo & Republic of the Congo",
    name_fi: "Kongon kuningaskunta ja Kongon tasavalta",
    native_name: "Kongo dya Ntotila / Congo",
    alternate_names: ["Congo", "Congo (France)", "Kingdom of Kongo"],
    culture_group: "Central Africa",
    lineage_id: "congo",
    historical_period: "Medieval to Modern Central Africa",
    year_start: 1390,
    year_end: 2026,
    period_label: "1390 CE – Present",
    period_label_fi: "1390 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Kongo",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kongon_kuningaskunta",
    wikidata_id: "Q205560",
    summary_en: "Influential centralized empire along the lower Congo River that adopted Christianity under King Afonso I in the 16th century, later inspiring the modern Republic of the Congo (Brazzaville).",
    summary_fi: "Historiallinen suuri kuningaskunta Kongo-joen alajuoksulla, joka omaksui kristinuskon 1500-luvulla ja jonka perintöä kantaa nykyinen Kongon tasavalta (Brazzaville).",
    capital: "M'banza-Kongo (São Salvador), Brazzaville",
    feature_name_matches: ["Congo", "Congo (France)"]
  },
  {
    slug: "democratic-republic-of-the-congo",
    name: "Democratic Republic of the Congo",
    name_fi: "Kongon demokraattinen tasavalta",
    native_name: "Congo Belge / Zaïre / RD Congo",
    alternate_names: ["Belgian Congo", "Zaire", "Zaire (Belgium)", "Congo Free State"],
    culture_group: "Central Africa",
    lineage_id: "dr-congo",
    historical_period: "Colonial to Modern Central Africa",
    year_start: 1885,
    year_end: 2026,
    period_label: "1885 CE – Present",
    period_label_fi: "1885 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kongon_demokraattinen_tasavalta",
    wikidata_id: "Q974",
    summary_en: "Immense rainforest nation spanning the Congo Basin, suffering exploitation as Leopold II's Congo Free State and the Belgian Congo before gaining independence in 1960 under Patrice Lumumba.",
    summary_fi: "Keskisen Afrikan valtava valtio Kongon jokialtaassa, joka kärsi raskaasta siirtomaariistosta ennen itsenäistymistään Patrice Lumumban johdolla vuonna 1960.",
    capital: "Kinshasa (Léopoldville)",
    feature_name_matches: [
      "Belgian Congo",
      "Zaire",
      "Zaire (Belgium)"
    ]
  },
  {
    slug: "republic-of-cameroon",
    name: "Republic of Cameroon",
    name_fi: "Kamerunin tasavalta",
    native_name: "Cameroun / Cameroon",
    alternate_names: ["Cameroon", "Kamerun"],
    culture_group: "Central Africa",
    lineage_id: "cameroon",
    historical_period: "Colonial to Modern Central Africa",
    year_start: 1884,
    year_end: 2026,
    period_label: "1884 CE – Present",
    period_label_fi: "1884 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Cameroon",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kamerun",
    wikidata_id: "Q1009",
    summary_en: "Often called 'Africa in miniature' for its diverse geography ranging from Sahelian savannas to Atlantic beaches and Mount Cameroon, home to Grassfields fon kingdoms and Bamum script.",
    summary_fi: "Afrikan pienoiskoossa -nimellä tunnettu monimuotoinen valtio Guineanlahdella, jossa kohtaavat sademetsät ja savannit ja jossa Bamum-kuningaskunta kehitti oman kirjoitusjärjestelmänsä.",
    capital: "Yaoundé, Douala",
    feature_name_matches: ["Cameroon"]
  },
  {
    slug: "central-african-republic",
    name: "Central African Republic",
    name_fi: "Keski-Afrikan tasavalta",
    native_name: "Centrafrique / Bêafrîka",
    alternate_names: ["Central African Republic", "Ubangi-Shari"],
    culture_group: "Central Africa",
    lineage_id: "central-african-republic",
    historical_period: "Colonial to Modern Central Africa",
    year_start: 1903,
    year_end: 2026,
    period_label: "1903 CE – Present",
    period_label_fi: "1903 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Central_African_Republic",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Keski-Afrikan_tasavalta",
    wikidata_id: "Q929",
    summary_en: "Landlocked nation situated on the watershed between the Chad and Congo basins, formerly French Ubangi-Shari, gaining independence in 1960 under pan-African visionary Barthélemy Boganda.",
    summary_fi: "Sisämaavaltio Tšadin ja Kongon vesistöjen vedenjakajalla, entinen Ranskan Ubangi-Šari, joka saavutti itsenäisyyden Barthélemy Bogandan johdolla vuonna 1960.",
    capital: "Bangui",
    feature_name_matches: ["Central African Republic"]
  },
  {
    slug: "republic-of-chad",
    name: "Republic of Chad",
    name_fi: "Tšadin tasavalta",
    native_name: "Tchad / تشاد",
    alternate_names: ["Chad"],
    culture_group: "Central Africa",
    lineage_id: "chad",
    historical_period: "Colonial to Modern Central Africa",
    year_start: 1900,
    year_end: 2026,
    period_label: "1900 CE – Present",
    period_label_fi: "1900 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Chad",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/T%C5%A1ad",
    wikidata_id: "Q657",
    summary_en: "Extensive Sahelian nation bridging North and Central Africa, centered on the ancient Lake Chad depression and the Tibesti mountains, site of the hominid discovery Toumaï (Sahelanthropus tchadensis).",
    summary_fi: "Pohjois- ja Keski-Afrikan rajalla sijaitseva laaja valtio Tšadjärven altaassa, josta löydettiin yksi varhaisimmista tunnetuista ihmisen esi-isistä (Sahelanthropus tchadensis / Toumaï).",
    capital: "N'Djamena (Fort-Lamy)",
    feature_name_matches: ["Chad"]
  },
  {
    slug: "equatorial-guinea",
    name: "Republic of Equatorial Guinea",
    name_fi: "Päiväntasaajan Guinean tasavalta",
    native_name: "Guinea Ecuatorial",
    alternate_names: ["Spanish Guinea", "Equatorial Guinea"],
    culture_group: "Central Africa",
    lineage_id: "equatorial-guinea",
    historical_period: "Colonial to Modern Central Africa",
    year_start: 1778,
    year_end: 2026,
    period_label: "1778 CE – Present",
    period_label_fi: "1778 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Equatorial_Guinea",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/P%C3%A4iv%C3%A4ntasaajan_Guinea",
    wikidata_id: "Q983",
    summary_en: "The only sovereign Spanish-speaking country in Africa, composed of the mainland territory of Río Muni and the volcanic Gulf of Guinea islands of Bioko and Annobón.",
    summary_fi: "Afrikan ainoa espanjankielinen valtio, joka koostuu Río Munin manneralueesta sekä Biokon ja Annobónin tuliperäisistä saarista Guineanlahdella.",
    capital: "Malabo, Ciudad de la Paz",
    feature_name_matches: ["Equatorial Guinea", "Spanish Guinea"]
  },
  {
    slug: "gabonese-republic",
    name: "Gabonese Republic",
    name_fi: "Gabonin tasavalta",
    native_name: "Gabon",
    alternate_names: ["Gabon"],
    culture_group: "Central Africa",
    lineage_id: "gabon",
    historical_period: "Colonial to Modern Central Africa",
    year_start: 1885,
    year_end: 2026,
    period_label: "1885 CE – Present",
    period_label_fi: "1885 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gabon",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gabon",
    wikidata_id: "Q1000",
    summary_en: "Equatorial Atlantic nation largely blanketed by pristine tropical rainforests, home to the UNESCO-listed Lopé-Okanda ecosystem, Mpongwe coastal trade, and significant petroleum wealth.",
    summary_fi: "Päiväntasaajan rannikkovaltio, jonka pinta-alasta valtaosa on koskematonta sademetsää ja joka tunnetaan luonnonvaroistaan ja Lopén kansallispuistosta.",
    capital: "Libreville",
    feature_name_matches: ["Gabon"]
  }
]

const outPath = path.resolve(__dirname, "../../data-sources/batches/central-africa.json")
fs.writeFileSync(outPath, JSON.stringify(CENTRAL_AFRICA_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${CENTRAL_AFRICA_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(CENTRAL_AFRICA_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
