import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "../seed_culture_metadata_batch"

const WESTERN_EUROPE_CULTURES: CultureBatchEntry[] = [
  {
    slug: "hallstatt-culture",
    name: "Hallstatt Culture",
    name_fi: "Hallstattin kulttuuri",
    alternate_names: ["Hallstatt"],
    culture_group: "Western Europe",
    lineage_id: "celt",
    historical_period: "Early Iron Age Central-Western Europe",
    year_start: -1200,
    year_end: -450,
    period_label: "1200 BCE – 450 BCE",
    period_label_fi: "1200 eaa. – 450 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Hallstatt_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Hallstattin_kulttuuri",
    wikidata_id: "Q202161",
    summary_en: "Predominant Western and Central European early Iron Age culture centered around Austrian salt mines, characterized by rich chieftain wagon graves, iron swords, and Mediterranean trade connections.",
    summary_fi: "Varhainen rautakautinen kulttuuri Keski- ja Länsi-Euroopassa, joka tunnetaan Itävallan Hallstattin suolakaivoksista, päälliköiden vaunuhautauksista ja rauta-aseista.",
    capital: "Hallstatt, Heuneburg",
    feature_name_matches: ["Hallstatt culture"]
  },
  {
    slug: "la-tene-celtic-culture",
    name: "La Tène Culture & Celts",
    name_fi: "La Tènen kulttuuri ja keltit",
    native_name: "Celtici / Galli",
    alternate_names: ["La Tène culture", "Celts", "Celtiberians"],
    culture_group: "Western Europe",
    lineage_id: "celt",
    historical_period: "Iron Age Celtic Europe",
    year_start: -450,
    year_end: 100,
    period_label: "450 BCE – 100 CE",
    period_label_fi: "450 eaa. – 100 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/La_T%C3%A8ne_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/La_T%C3%A8nen_kulttuuri",
    wikidata_id: "Q193152",
    summary_en: "Classical Iron Age Celtic civilization named after Lake Neuchâtel, noted for intricate curvilinear spiral metalwork, fortified hillfort oppida, druidic priesthoods, and migration across Iberia, Gaul, and Britain.",
    summary_fi: "Rautakauden kelttiläinen kulttuuri, joka tunnetaan taidokkaasta spiraaliornamentiikastaan, linnoitetuista oppidum-kaupungeistaan ja leviämisestään Galliaan, Britanniaan ja Iberiaan.",
    capital: "Bibracte, Entremont, Numantia",
    feature_name_matches: ["La Tène culture", "Celts", "Celtiberians"]
  },
  {
    slug: "early-germanic-tribes",
    name: "Early Germanic Tribes & Suebi",
    name_fi: "Varhaiset germaanit ja sveebit",
    native_name: "Germani / Suebi",
    alternate_names: ["Germanic tribes", "Suebi"],
    culture_group: "Western Europe",
    lineage_id: "germanic",
    historical_period: "Antiquity to Migration Period",
    year_start: -500,
    year_end: 585,
    period_label: "500 BCE – 585 CE",
    period_label_fi: "500 eaa. – 585 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Germanic_peoples",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Germaanit",
    wikidata_id: "Q22633",
    summary_en: "Indo-European tribal confederations of northern and central Europe who checked Roman expansion along the Rhine-Danube limes and founded post-Roman successor kingdoms across Western Europe, including the Suebic Kingdom of Gallaecia.",
    summary_fi: "Pohjois- ja Keski-Euroopan germaaniheimot, jotka pysäyttivät Rooman laajentumisen Reinin rajalle ja perustivat kansainvaellusajan kuningaskuntia kuten sveebien valtion Galiciassa.",
    capital: "Magna Germania / Bracara Augusta",
    feature_name_matches: ["Germanic tribes", "Suebi"]
  },
  {
    slug: "frankish-kingdom",
    name: "Franks & Merovingian Kingdom",
    name_fi: "Frankit ja merovingikuningaskunta",
    native_name: "Regnum Francorum",
    alternate_names: ["Franks", "Frankish Kingdom"],
    culture_group: "Western Europe",
    lineage_id: "france",
    historical_period: "Late Antiquity to Early Middle Ages",
    year_start: 450,
    year_end: 751,
    period_label: "450 CE – 751 CE",
    period_label_fi: "450 jaa. – 751 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Franks",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Frankit",
    wikidata_id: "Q4341",
    summary_en: "Germanic confederation unified under Merovingian king Clovis I, who converted to Nicene Christianity in 496 CE, conquered Roman Gaul, and established the foundation of medieval France and Germany.",
    summary_fi: "Kansainvaellusajan germaaniheimo, jonka merovingikuningas Klodvig I yhdisti ja käänsi kristinuskoon vuonna 496 luoden pohjan Ranskan ja Saksan keskiaikaisille valtioille.",
    capital: "Tournai, Paris, Metz, Soissons",
    feature_name_matches: ["Franks", "Frankish Kingdom"]
  },
  {
    slug: "carolingian-empire",
    name: "Carolingian Empire",
    name_fi: "Karolingien valtakunta",
    native_name: "Imperium Romanum / Francorum",
    alternate_names: ["Empire of Charlemagne", "Carolingian"],
    culture_group: "Western Europe",
    lineage_id: "france",
    historical_period: "Early Medieval Western Europe",
    year_start: 751,
    year_end: 888,
    period_label: "751 CE – 888 CE",
    period_label_fi: "751 jaa. – 888 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Carolingian_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Karolinginen_valtakunta",
    wikidata_id: "Q31929",
    summary_en: "Pan-Western European empire created by Charlemagne, crowned Emperor of the Romans by Pope Leo III on Christmas Day 800 CE, sparking the Carolingian Renaissance in learning and arts.",
    summary_fi: "Kaarle Suuren luoma Länsi-Euroopan kattanut valtakunta, jonka paavi kruunasi Rooman keisariksi vuonna 800 ja joka synnytti karolingisen kirjallisen ja sivistyksellisen renessanssin.",
    capital: "Aachen",
    feature_name_matches: ["Carolingian Empire"]
  },
  {
    slug: "kingdom-of-france",
    name: "Kingdom & Republic of France",
    name_fi: "Ranskan kuningaskunta ja tasavalta",
    native_name: "Royaume de France / République française",
    alternate_names: ["Kingdom of France", "France", "New France"],
    culture_group: "Western Europe",
    lineage_id: "france",
    historical_period: "Medieval to Modern Western Europe",
    year_start: 843,
    year_end: 2026,
    period_label: "843 CE – Present",
    period_label_fi: "843 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_France",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ranskan_kuningaskunta",
    wikidata_id: "Q70972",
    summary_en: "Evolving from West Francia after the Treaty of Verdun in 843, France became a preeminent European superpower under the Capetians, Bourbons, and Napoleon, establishing the universal ideals of Liberté, égalité, fraternité.",
    summary_fi: "Verdunin sopimuksessa 843 syntynyt Ranskan valtio nousi kapetingien, Bourbonien ja Napoleonin johdolla Euroopan johtavaksi mahdiksi ja vapauden aatteiden levittäjäksi.",
    capital: "Paris, Versailles",
    feature_name_matches: ["Kingdom of France", "France", "New France"]
  },
  {
    slug: "french-colonial-africa",
    name: "French Colonial Africa",
    name_fi: "Ranskan siirtomaa-Afrikka",
    native_name: "Afrique-Équatoriale / Occidentale française",
    alternate_names: ["French West Africa", "French Equatorial Africa", "French Cameroons"],
    culture_group: "Western Europe",
    lineage_id: "france",
    historical_period: "Colonial African Federation",
    year_start: 1895,
    year_end: 1960,
    period_label: "1895 CE – 1960 CE",
    period_label_fi: "1895 jaa. – 1960 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/French_West_Africa",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ranskan_L%C3%A4nsi-Afrikka",
    wikidata_id: "Q210682",
    summary_en: "Federations of French colonial territories across West and Central Africa (AOF and AEF) administered from Dakar and Brazzaville, achieving independence in the pivotal decolonization year of 1960.",
    summary_fi: "Ranskan Länsi- ja Päiväntasaajan Afrikan siirtomaaliitot, joita hallittiin Dakarista ja Brazzavillestä ja joiden jäsenmaat itsenäistyivät pääosin Afrikan vuonna 1960.",
    capital: "Dakar, Brazzaville",
    feature_name_matches: [
      "French West Africa",
      "French Equatorial Africa",
      "French Cameroons"
    ]
  },
  {
    slug: "duchy-of-brittany",
    name: "Duchy of Brittany",
    name_fi: "Bretagnen herttuakunta",
    native_name: "Dugelezh Breizh",
    alternate_names: ["Britany", "Breizh"],
    culture_group: "Western Europe",
    lineage_id: "celt",
    historical_period: "Medieval Celtic Brittany",
    year_start: 851,
    year_end: 1532,
    period_label: "851 CE – 1532 CE",
    period_label_fi: "851 jaa. – 1532 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Duchy_of_Brittany",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bretagnen_herttuakunta",
    wikidata_id: "Q12019",
    summary_en: "Sovereign Celtic state on the Armorican peninsula established by Nominoe, maintaining independence from both England and France through diplomatic maneuvering until union with France under Queen Claude in 1532.",
    summary_fi: "Bretagnen niemimaalla sijainnut kelttiläinen herttuakunta, joka säilytti itsenäisyytensä Ranskan ja Englannin välissä aina vuoden 1532 unioniin saakka.",
    capital: "Nantes, Rennes",
    feature_name_matches: ["Britany"]
  },
  {
    slug: "burgundians-kingdom",
    name: "Kingdom of the Burgundians",
    name_fi: "Burgundien kuningaskunta",
    native_name: "Regnum Burgundionum",
    alternate_names: ["Burgundians"],
    culture_group: "Western Europe",
    lineage_id: "germanic",
    historical_period: "Late Antiquity to Early Middle Ages",
    year_start: 411,
    year_end: 534,
    period_label: "411 CE – 534 CE",
    period_label_fi: "411 jaa. – 534 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_the_Burgundians",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Burgundit",
    wikidata_id: "Q1128537",
    summary_en: "East Germanic people who established kingdoms at Worms and later in the Rhône-Alps valley (Sapaudia), famous in Germanic legend through the Nibelungenlied and Lex Burgundionum law code.",
    summary_fi: "Itägermaaninen kansa, joka perusti kuningaskuntansa Reinin ja myöhemmin Rhônen laaksoon ja jonka kohtalot ikuistettiin Nibelungein lauluun.",
    capital: "Worms, Geneva, Lyon",
    feature_name_matches: ["Burgundians"]
  },
  {
    slug: "visigothic-kingdom",
    name: "Visigothic Kingdom",
    name_fi: "Länsigoottien valtakunta",
    native_name: "Regnum Visigothorum",
    alternate_names: ["Visigoths", "Visigothic Kingdom"],
    culture_group: "Western Europe",
    lineage_id: "spain",
    historical_period: "Late Antiquity to Early Middle Ages",
    year_start: 418,
    year_end: 720,
    period_label: "418 CE – 720 CE",
    period_label_fi: "418 jaa. – 720 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Visigothic_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/L%C3%A4nsigoottien_valtakunta",
    wikidata_id: "Q126936",
    summary_en: "Post-Roman kingdom founded by Alaric's Visigoths in southwestern Gaul (Toulouse) and expanding across the entire Iberian Peninsula from Toledo, codifying the famous Visigothic Code (Forum Iudicum).",
    summary_fi: "Länsigoottien perustama kuningaskunta Toulousessa ja Toledossa, joka hallitsi koko Iberian niemimaata ja loi laajan lakikokoelman (Forum Iudicum).",
    capital: "Toulouse, Toledo",
    feature_name_matches: ["Visigothic Kingdom", "Visigoths"]
  },
  {
    slug: "ostrogothic-kingdom",
    name: "Ostrogothic Kingdom",
    name_fi: "Itägoottien valtakunta",
    native_name: "Regnum Ostrogothorum",
    alternate_names: ["Ostrogoths", "Goths"],
    culture_group: "Western Europe",
    lineage_id: "italy",
    historical_period: "Late Antiquity Italy",
    year_start: 493,
    year_end: 553,
    period_label: "493 CE – 553 CE",
    period_label_fi: "493 jaa. – 553 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Ostrogothic_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/It%C3%A4goottien_valtakunta",
    wikidata_id: "Q208194",
    summary_en: "Kingdom established by Theodoric the Great in Italy and the Illyrian provinces following the fall of the Western Roman Empire, maintaining Roman civil administration and legal traditions from Ravenna.",
    summary_fi: "Teoderik Suuren Italiaan perustama itägoottien valtakunta Ravennassa, joka säilytti roomalaisen hallintojärjestelmän ja monumentaaliarkkitehtuurin.",
    capital: "Ravenna, Rome",
    feature_name_matches: ["Ostrogoths", "Goths"]
  },
  {
    slug: "vandal-kingdom",
    name: "Vandal Kingdom",
    name_fi: "Vandaalien valtakunta",
    native_name: "Regnum Vandalorum",
    alternate_names: ["Vandals"],
    culture_group: "Western Europe",
    lineage_id: "germanic",
    historical_period: "Late Antiquity Western Mediterranean",
    year_start: 429,
    year_end: 534,
    period_label: "429 CE – 534 CE",
    period_label_fi: "429 jaa. – 534 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Vandal_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Vandaalit",
    wikidata_id: "Q102370",
    summary_en: "East Germanic kingdom established by King Genseric across Roman North Africa, Corsica, Sardinia, and Sicily, commanding the western Mediterranean fleet and famously sacking Rome in 455 CE.",
    summary_fi: "Kuningas Geiserikin Pohjois-Afrikkaan perustama vandaalien merivaltakunta, joka hallitsi läntisen Välimeren saaria ja ryösti Rooman vuonna 455.",
    capital: "Carthage",
    feature_name_matches: ["Vandals"]
  },
  {
    slug: "lombards-kingdom",
    name: "Lombard Kingdoms & Principalities",
    name_fi: "Langobardien kuningaskunnat ja ruhtinaskunnat",
    native_name: "Regnum Langobardorum",
    alternate_names: ["Lombard duchies", "Lombard principalities", "Lombardy"],
    culture_group: "Western Europe",
    lineage_id: "italy",
    historical_period: "Early Medieval Italy",
    year_start: 568,
    year_end: 774,
    period_label: "568 CE – 774 CE",
    period_label_fi: "568 jaa. – 774 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_the_Lombards",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Langobardien_valtakunta",
    wikidata_id: "Q854415",
    summary_en: "Germanic people who conquered northern and central Italy under King Alboin, giving their name to Lombardy and establishing independent southern duchies like Benevento and Spoleto.",
    summary_fi: "Langobardien kuningaskunta Pohjois- ja Keski-Italiassa, joka antoi nimensä Lombardialle ja loi vahvoja eteläisiä ruhtinaskuntia kuten Beneventon.",
    capital: "Pavia, Benevento",
    feature_name_matches: [
      "Lombard duchies",
      "Lombard principalities",
      "Lombardy"
    ]
  },
  {
    slug: "frisian-kingdom",
    name: "Frisian Kingdom",
    name_fi: "Friisien kuningaskunta",
    native_name: "Magna Frisia",
    alternate_names: ["Frisians"],
    culture_group: "Western Europe",
    lineage_id: "netherlands",
    historical_period: "Early Medieval Low Countries",
    year_start: 600,
    year_end: 734,
    period_label: "600 CE – 734 CE",
    period_label_fi: "600 jaa. – 734 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Frisian_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Friisit",
    wikidata_id: "Q768019",
    summary_en: "Coastal kingdom in the modern Netherlands and northwestern Germany ruled by kings Aldgisl and Redbad, dominating North Sea maritime commerce through the trade emporium of Dorestad.",
    summary_fi: "Pohjanmeren rannikkovaltio nykyisten Alankomaiden alueella, joka hallitsi Pohjanmeren kauppareittejä Dorestadin satamasta käsin.",
    capital: "Utrecht, Dorestad",
    feature_name_matches: ["Frisians"]
  },
  {
    slug: "dutch-republic",
    name: "Dutch Republic & Kingdom of the Netherlands",
    name_fi: "Yhdistyneet provinssit ja Alankomaiden kuningaskunta",
    native_name: "Republiek der Zeven Verenigde Nederlanden / Nederland",
    alternate_names: [
      "Dutch Republic",
      "Netherlands",
      "Dutch settlements",
      "Dutch Brazil",
      "Dutch Guiana",
      "Dutch Guinea",
      "Netherlands Indies"
    ],
    culture_group: "Western Europe",
    lineage_id: "netherlands",
    historical_period: "Early Modern to Modern Low Countries",
    year_start: 1581,
    year_end: 2026,
    period_label: "1581 CE – Present",
    period_label_fi: "1581 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Dutch_Republic",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Yhdistyneet_provinssit",
    wikidata_id: "Q170072",
    summary_en: "Pioneering federal republic and maritime commercial empire leading the Dutch Golden Age in science, finance (first stock exchange), art (Rembrandt, Vermeer), and global seafaring trade via the VOC and WIC.",
    summary_fi: "Alankomaiden tasavalta ja kultakauden merimahti, joka mullisti maailmankaupan ja pankkilaitoksen ja loi häikäisevän maalaustaiteen perinteen.",
    capital: "The Hague, Amsterdam",
    feature_name_matches: [
      "Dutch Republic",
      "Netherlands",
      "Dutch settlements",
      "Dutch Brazil",
      "Dutch Guiana",
      "Dutch Guinea",
      "Netherlands Indies"
    ]
  },
  {
    slug: "kingdom-of-belgium",
    name: "Kingdom of Belgium",
    name_fi: "Belgian kuningaskunta",
    native_name: "België / Belgique",
    alternate_names: ["Belgium"],
    culture_group: "Western Europe",
    lineage_id: "belgium",
    historical_period: "Modern Western Europe",
    year_start: 1830,
    year_end: 2026,
    period_label: "1830 CE – Present",
    period_label_fi: "1830 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Belgium",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Belgia",
    wikidata_id: "Q31",
    summary_en: "Constitutional monarchy in the Low Countries established after the 1830 Belgian Revolution, serving as a pioneer of the continental Industrial Revolution and the diplomatic heart of the European Union.",
    summary_fi: "Vuoden 1830 vallankumouksen jälkeen itsenäistynyt valtio, joka oli Euroopan mannermaan teollisen vallankumouksen kärkimaa ja toimii nykyään Euroopan unionin pääkeskuksena.",
    capital: "Brussels",
    feature_name_matches: ["Belgium"]
  },
  {
    slug: "grand-duchy-of-luxembourg",
    name: "Grand Duchy of Luxembourg",
    name_fi: "Luxemburgin suurherttuakunta",
    native_name: "Lëtzebuerg / Luxembourg",
    alternate_names: ["Luxembourg"],
    culture_group: "Western Europe",
    lineage_id: "luxembourg",
    historical_period: "Medieval to Modern Western Europe",
    year_start: 963,
    year_end: 2026,
    period_label: "963 CE – Present",
    period_label_fi: "963 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Luxembourg",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Luxemburg",
    wikidata_id: "Q32",
    summary_en: "World's only remaining sovereign Grand Duchy, founded by Count Siegfried at the fortified rock of Bock in 963, historically producing Holy Roman Emperors and flourishing as a European financial capital.",
    summary_fi: "Maailman ainoa itsenäinen suurherttuakunta, jonka kreivi Siegfried perusti Bockin kalliolinnoitukselle vuonna 963 ja josta muodostui Euroopan keskeinen finanssikeskus.",
    capital: "Luxembourg City",
    feature_name_matches: ["Luxembourg"]
  },
  {
    slug: "anglo-saxons",
    name: "Anglo-Saxons",
    name_fi: "Anglosaksit",
    native_name: "Englasaxe",
    alternate_names: ["Anglo-Saxons", "Saxons"],
    culture_group: "Western Europe",
    lineage_id: "britain",
    historical_period: "Early Medieval Britain",
    year_start: 450,
    year_end: 1066,
    period_label: "450 CE – 1066 CE",
    period_label_fi: "450 jaa. – 1066 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Anglo-Saxons",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Anglosaksit",
    wikidata_id: "Q127357",
    summary_en: "Germanic tribes (Angles, Saxons, Jutes) who migrated to Britain in the 5th century, establishing the Heptarchy kingdoms (Wessex, Mercia, Northumbria), composing Beowulf, and laying the foundations of England.",
    summary_fi: "Britanniaan 400-luvulla saapuneet germaaniheimot (anglit, saksit ja juutit), jotka loivat varhaiset kuningaskunnat, Beowulf-runoelman ja perustan Englannin valtiolle.",
    capital: "Winchester, Bamburgh",
    feature_name_matches: ["Anglo-Saxons", "Saxons"]
  },
  {
    slug: "electorate-of-saxony",
    name: "Electorate & Kingdom of Saxony",
    name_fi: "Saksin vaaliruhtinaskunta ja kuningaskunta",
    native_name: "Kurfürstentum Sachsen",
    alternate_names: ["Saxony", "Kingdom of Saxony"],
    culture_group: "Western Europe",
    lineage_id: "germany",
    historical_period: "Early Modern to 19th Century German Realm",
    year_start: 1356,
    year_end: 1918,
    period_label: "1356 CE – 1918 CE",
    period_label_fi: "1356 jaa. – 1918 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Electorate_of_Saxony",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Saksin_vaaliruhtinaskunta",
    wikidata_id: "Q156199",
    summary_en: "Prestigious Holy Roman imperial electorate and cradle of the Protestant Reformation under Frederick the Wise, famed for Dresden baroque architecture, Meissen porcelain, and musical patronage.",
    summary_fi: "Pyhän saksalais-roomalaisen keisarikunnan merkittävä vaaliruhtinaskunta ja uskonpuhdistuksen kehto, joka tunnettiin Dresdenin barokkitaiteesta ja Meissenin posliinista.",
    capital: "Dresden, Wittenberg",
    feature_name_matches: ["Saxony"]
  },
  {
    slug: "kingdom-of-england",
    name: "Kingdom of England & United Kingdom",
    name_fi: "Englannin kuningaskunta ja Yhdistynyt kuningaskunta",
    native_name: "Kingdom of England / United Kingdom",
    alternate_names: [
      "England",
      "England and Ireland",
      "United Kingdom",
      "United Kingdom of Great Britain and Ireland"
    ],
    culture_group: "Western Europe",
    lineage_id: "britain",
    historical_period: "Medieval to Modern Britain",
    year_start: 927,
    year_end: 2026,
    period_label: "927 CE – Present",
    period_label_fi: "927 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_England",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Englannin_kuningaskunta",
    wikidata_id: "Q179876",
    summary_en: "Unified by Athelstan in 927 and transformed by the 1066 Norman Conquest, England developed parliamentary democracy, Magna Carta, common law, and forged the global British Empire.",
    summary_fi: "Vuonna 927 yhdistynyt ja normannivalloituksen 1066 myötä uudistunut Englannin kuningaskunta, joka kehitti parlamentarismin, Magna Cartan ja loi maailmanlaajuisen imperiumin.",
    capital: "London, Winchester",
    feature_name_matches: [
      "England",
      "England and Ireland",
      "United Kingdom",
      "United Kingdom of Great Britain and Ireland"
    ]
  },
  {
    slug: "ireland-realm",
    name: "Kingdom & Republic of Ireland",
    name_fi: "Irlannin kuningaskunta ja tasavalta",
    native_name: "Éire",
    alternate_names: ["Ireland", "Kingdom of Ireland"],
    culture_group: "Western Europe",
    lineage_id: "ireland",
    historical_period: "Early Christian to Modern Ireland",
    year_start: 400,
    year_end: 2026,
    period_label: "400 CE – Present",
    period_label_fi: "400 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/History_of_Ireland",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Irlannin_historia",
    wikidata_id: "Q22890",
    summary_en: "Gaelic island nation renowned for early medieval monastic learning (Book of Kells), epic mythology, resisting Tudor conquest, and winning independence as a sovereign republic in 1922.",
    summary_fi: "Gaelilainen saarivaltio, joka tunnetaan varhaiskeskiajan luostarisivistyksestä (Kellsin kirja), rikkaasta mytologiastaan ja vuonna 1922 saavutetusta itsenäisyydestään.",
    capital: "Dublin, Tara",
    feature_name_matches: ["Ireland", "Kingdom of Ireland"]
  },
  {
    slug: "welsh-kingdoms",
    name: "Welsh Kingdoms & Celts",
    name_fi: "Walesin kuningaskunnat",
    native_name: "Cymru",
    alternate_names: ["Welsh", "Celtic kingdoms"],
    culture_group: "Western Europe",
    lineage_id: "celt",
    historical_period: "Sub-Roman to Medieval Wales",
    year_start: 450,
    year_end: 1283,
    period_label: "450 CE – 1283 CE",
    period_label_fi: "450 jaa. – 1283 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Wales_in_the_Middle_Ages",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Walesin_historia",
    wikidata_id: "Q18835",
    summary_en: "Brythonic Celtic kingdoms (Gwynedd, Powys, Deheubarth) in western Britain that repelled Saxon expansion, codified the Laws of Hywel Dda, and preserved ancient bardic poetic traditions.",
    summary_fi: "Walesin kelttiläiset kuningaskunnat (Gwynedd, Powys ym.), jotka torjuivat anglosaksien valloitusyritykset ja loivat Hywel Ddan maineikkaan lakikokoelman.",
    capital: "Aberffraw, Dinefwr",
    feature_name_matches: ["Welsh", "Celtic kingdoms"]
  },
  {
    slug: "kingdom-of-scotland",
    name: "Kingdom of Scotland & Picts",
    name_fi: "Skotlannin kuningaskunta ja piktit",
    native_name: "Rìoghachd na h-Alba",
    alternate_names: ["Scotland", "Scots", "Picts"],
    culture_group: "Western Europe",
    lineage_id: "scotland",
    historical_period: "Early Medieval to Modern Scotland",
    year_start: 500,
    year_end: 2026,
    period_label: "500 CE – Present",
    period_label_fi: "500 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Scotland",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Skotlannin_kuningaskunta",
    wikidata_id: "Q230791",
    summary_en: "Gaelic and Pictish realm unified under Kenneth MacAlpin in 843, fiercely guarding independence in Wars of Independence under William Wallace and Robert the Bruce.",
    summary_fi: "Kenneth MacAlpinin vuonna 843 yhdistämä gaelien ja piktien kuningaskunta, joka puolusti itsenäisyyttään Robert the Brucen ja William Wallacen johdolla.",
    capital: "Edinburgh, Scone, Stirling",
    feature_name_matches: ["Scotland", "Scots", "Picts"]
  },
  {
    slug: "swedes-and-goths-medieval",
    name: "Early Medieval Svear & Geats",
    name_fi: "Svealaiset ja göötit",
    native_name: "Svear och Götar",
    alternate_names: ["Swedes and Goths"],
    culture_group: "Western Europe",
    lineage_id: "nordic",
    historical_period: "Vendel to Early Viking Age Scandinavia",
    year_start: 550,
    year_end: 1000,
    period_label: "550 CE – 1000 CE",
    period_label_fi: "550 jaa. – 1000 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Geats",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/G%C3%B6%C3%B6tit",
    wikidata_id: "Q200787",
    summary_en: "North Germanic peoples of Scandinavia mentioned in Beowulf (Svear of Uppland and Geats of Götaland) whose amalgamation under kings like Olof Skötkonung formed the medieval Swedish kingdom.",
    summary_fi: "Skandinavian pohjoisgermaaniset kansat (svealaiset ja göötit), joiden liitto loi pohjan Ruotsin kuningaskunnan muodostumiselle.",
    capital: "Gamla Uppsala",
    feature_name_matches: ["Swedes and Goths"]
  },
  {
    slug: "colony-new-south-wales",
    name: "Colony of New South Wales",
    name_fi: "Uuden Etelä-Walesin siirtokunta",
    alternate_names: ["New South Wales", "New South Wales (UK)"],
    culture_group: "Western Europe",
    lineage_id: "oceania",
    historical_period: "Colonial Australia",
    year_start: 1788,
    year_end: 1901,
    period_label: "1788 CE – 1901 CE",
    period_label_fi: "1788 jaa. – 1901 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Colony_of_New_South_Wales",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Uusi_Etel%C3%A4-Wales",
    wikidata_id: "Q3224",
    summary_en: "The first British colony on the Australian continent, established at Sydney Cove in 1788 by Governor Arthur Phillip with the First Fleet, expanding across eastern Australia until federation in 1901.",
    summary_fi: "Ensimmäinen brittiläinen siirtokunta Australiassa, jonka Arthur Phillip perusti Sydney Coveen vuonna 1788 ja joka toimi Australian federaation perustana.",
    capital: "Sydney",
    feature_name_matches: ["New South Wales", "New South Wales (UK)"]
  },
  {
    slug: "penobscot-nation",
    name: "Penobscot Indian Nation",
    name_fi: "Penobscot-intiaanikansa",
    native_name: "Páhnawápskewi",
    alternate_names: ["Penobscot"],
    culture_group: "Western Europe",
    lineage_id: "north-america",
    historical_period: "Northeast Woodlands Indigenous Traditions",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Penobscot",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Wabanaki",
    wikidata_id: "Q1474932",
    summary_en: "Indigenous Eastern Algonquian nation of the Wabanaki Confederacy native to the Penobscot River basin in Maine, renowned for birchbark canoe craft and birch basketry.",
    summary_fi: "Pohjois-Amerikan koillisalueen algonkin-kielinen alkuperäiskansa Mainen Penobscot-joen laaksossa, joka tunnetaan tuohesta valmistetuista kanooteistaan ja korinpunonnasta.",
    capital: "Indian Island, Maine",
    feature_name_matches: ["Penobscot"]
  }
]

const outPath = path.resolve(__dirname, "../../data-sources/batches/western-europe.json")
fs.writeFileSync(outPath, JSON.stringify(WESTERN_EUROPE_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${WESTERN_EUROPE_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(WESTERN_EUROPE_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
