/**
 * Modern country baseline cartographic palette.
 * Provides curated, high-contrast, vibrant colors for modern countries (by ISO-3 and standard names).
 * Used as the foundational baseline when resolving historical predecessor lineages.
 */

export interface ModernCountryColor {
  isoA3: string
  name: string
  color: string
  cultureGroup?: string
  aliases?: string[]
}

export const MODERN_COUNTRY_PALETTE: Record<string, ModernCountryColor> = {
  // Western Europe
  GBR: { isoA3: "GBR", name: "United Kingdom", color: "#1d4ed8", cultureGroup: "Western Europe", aliases: ["uk", "great britain", "britain", "england", "scotland", "wales", "northern ireland"] },
  FRA: { isoA3: "FRA", name: "France", color: "#2563eb", cultureGroup: "Western Europe", aliases: ["french republic"] },
  DEU: { isoA3: "DEU", name: "Germany", color: "#b45309", cultureGroup: "Central Europe", aliases: ["deutschland", "federal republic of germany"] },
  ITA: { isoA3: "ITA", name: "Italy", color: "#15803d", cultureGroup: "Southern Europe", aliases: ["italia", "italian republic"] },
  ESP: { isoA3: "ESP", name: "Spain", color: "#dc2626", cultureGroup: "Southern Europe", aliases: ["españa", "kingdom of spain"] },
  PRT: { isoA3: "PRT", name: "Portugal", color: "#047857", cultureGroup: "Southern Europe", aliases: ["portuguese republic"] },
  NLD: { isoA3: "NLD", name: "Netherlands", color: "#ea580c", cultureGroup: "Western Europe", aliases: ["holland", "the netherlands"] },
  BEL: { isoA3: "BEL", name: "Belgium", color: "#ca8a04", cultureGroup: "Western Europe", aliases: ["kingdom of belgium"] },
  CHE: { isoA3: "CHE", name: "Switzerland", color: "#e11d48", cultureGroup: "Central Europe", aliases: ["swiss confederation"] },
  AUT: { isoA3: "AUT", name: "Austria", color: "#ef4444", cultureGroup: "Central Europe", aliases: ["republic of austria"] },
  IRL: { isoA3: "IRL", name: "Ireland", color: "#16a34a", cultureGroup: "Western Europe", aliases: ["republic of ireland", "éire"] },
  LUX: { isoA3: "LUX", name: "Luxembourg", color: "#38bdf8", cultureGroup: "Western Europe", aliases: ["grand duchy of luxembourg"] },
  MCO: { isoA3: "MCO", name: "Monaco", color: "#dc2626", cultureGroup: "Western Europe", aliases: ["principality of monaco"] },
  LIE: { isoA3: "LIE", name: "Liechtenstein", color: "#2563eb", cultureGroup: "Central Europe" },
  AND: { isoA3: "AND", name: "Andorra", color: "#ca8a04", cultureGroup: "Southern Europe" },
  SMR: { isoA3: "SMR", name: "San Marino", color: "#0284c7", cultureGroup: "Southern Europe" },
  VAT: { isoA3: "VAT", name: "Vatican City", color: "#eab308", cultureGroup: "Southern Europe", aliases: ["holy see", "vatican"] },
  MLT: { isoA3: "MLT", name: "Malta", color: "#dc2626", cultureGroup: "Southern Europe", aliases: ["republic of malta"] },

  // Nordic
  SWE: { isoA3: "SWE", name: "Sweden", color: "#0284c7", cultureGroup: "Nordic", aliases: ["kingdom of sweden"] },
  NOR: { isoA3: "NOR", name: "Norway", color: "#0369a1", cultureGroup: "Nordic", aliases: ["kingdom of norway"] },
  DNK: { isoA3: "DNK", name: "Denmark", color: "#be123c", cultureGroup: "Nordic", aliases: ["kingdom of denmark"] },
  FIN: { isoA3: "FIN", name: "Finland", color: "#0284c7", cultureGroup: "Nordic", aliases: ["republic of finland", "suomi"] },
  ISL: { isoA3: "ISL", name: "Iceland", color: "#2563eb", cultureGroup: "Nordic", aliases: ["republic of iceland"] },
  GRL: { isoA3: "GRL", name: "Greenland", color: "#0891b2", cultureGroup: "Nordic", aliases: ["kalaallit nunaat"] },
  FRO: { isoA3: "FRO", name: "Faroe Islands", color: "#0284c7", cultureGroup: "Nordic" },
  ALA: { isoA3: "ALA", name: "Åland Islands", color: "#0284c7", cultureGroup: "Nordic" },

  // Eastern & Central Europe & Balkans
  RUS: { isoA3: "RUS", name: "Russia", color: "#be123c", cultureGroup: "Slavic", aliases: ["russian federation"] },
  UKR: { isoA3: "UKR", name: "Ukraine", color: "#0284c7", cultureGroup: "Slavic" },
  BLR: { isoA3: "BLR", name: "Belarus", color: "#15803d", cultureGroup: "Slavic", aliases: ["republic of belarus"] },
  POL: { isoA3: "POL", name: "Poland", color: "#e11d48", cultureGroup: "Central Europe", aliases: ["republic of poland"] },
  CZE: { isoA3: "CZE", name: "Czech Republic", color: "#2563eb", cultureGroup: "Central Europe", aliases: ["czechia"] },
  SVK: { isoA3: "SVK", name: "Slovakia", color: "#0284c7", cultureGroup: "Central Europe", aliases: ["slovak republic"] },
  HUN: { isoA3: "HUN", name: "Hungary", color: "#16a34a", cultureGroup: "Central Europe" },
  ROU: { isoA3: "ROU", name: "Romania", color: "#ca8a04", cultureGroup: "Eastern Europe" },
  BGR: { isoA3: "BGR", name: "Bulgaria", color: "#059669", cultureGroup: "Eastern Europe", aliases: ["republic of bulgaria"] },
  GRC: { isoA3: "GRC", name: "Greece", color: "#0284c7", cultureGroup: "Southern Europe", aliases: ["hellas", "hellenic republic"] },
  SRB: { isoA3: "SRB", name: "Serbia", color: "#b91c1c", cultureGroup: "Balkans", aliases: ["republic of serbia"] },
  HRV: { isoA3: "HRV", name: "Croatia", color: "#dc2626", cultureGroup: "Balkans", aliases: ["republic of croatia"] },
  BIH: { isoA3: "BIH", name: "Bosnia and Herzegovina", color: "#1d4ed8", cultureGroup: "Balkans", aliases: ["bosnia"] },
  ALB: { isoA3: "ALB", name: "Albania", color: "#991b1b", cultureGroup: "Balkans", aliases: ["republic of albania"] },
  SVN: { isoA3: "SVN", name: "Slovenia", color: "#0284c7", cultureGroup: "Balkans", aliases: ["republic of slovenia"] },
  MKD: { isoA3: "MKD", name: "Macedonia", color: "#ea580c", cultureGroup: "Balkans", aliases: ["north macedonia", "republic of north macedonia"] },
  MNE: { isoA3: "MNE", name: "Montenegro", color: "#b91c1c", cultureGroup: "Balkans" },
  KOS: { isoA3: "KOS", name: "Kosovo", color: "#1d4ed8", cultureGroup: "Balkans", aliases: ["republic of kosovo"] },
  MDA: { isoA3: "MDA", name: "Moldova", color: "#ca8a04", cultureGroup: "Eastern Europe", aliases: ["republic of moldova"] },
  EST: { isoA3: "EST", name: "Estonia", color: "#0284c7", cultureGroup: "Baltic", aliases: ["republic of estonia"] },
  LVA: { isoA3: "LVA", name: "Latvia", color: "#881337", cultureGroup: "Baltic", aliases: ["republic of latvia"] },
  LTU: { isoA3: "LTU", name: "Lithuania", color: "#ca8a04", cultureGroup: "Baltic", aliases: ["republic of lithuania"] },
  CYP: { isoA3: "CYP", name: "Cyprus", color: "#ea580c", cultureGroup: "Mediterranean", aliases: ["republic of cyprus", "n. cyprus", "northern cyprus"] },

  // Middle East & North Africa
  TUR: { isoA3: "TUR", name: "Turkey", color: "#e11d48", cultureGroup: "Middle East", aliases: ["türkiye", "republic of turkey"] },
  IRN: { isoA3: "IRN", name: "Iran", color: "#0d9488", cultureGroup: "Middle East", aliases: ["islamic republic of iran", "persia"] },
  IRQ: { isoA3: "IRQ", name: "Iraq", color: "#047857", cultureGroup: "Middle East", aliases: ["republic of iraq"] },
  SYR: { isoA3: "SYR", name: "Syria", color: "#15803d", cultureGroup: "Middle East", aliases: ["syrian arab republic"] },
  LBN: { isoA3: "LBN", name: "Lebanon", color: "#dc2626", cultureGroup: "Middle East", aliases: ["lebanese republic"] },
  ISR: { isoA3: "ISR", name: "Israel", color: "#0284c7", cultureGroup: "Middle East", aliases: ["state of israel"] },
  PSE: { isoA3: "PSE", name: "Palestine", color: "#059669", cultureGroup: "Middle East", aliases: ["state of palestine", "west bank and gaza", "gaza"] },
  JOR: { isoA3: "JOR", name: "Jordan", color: "#047857", cultureGroup: "Middle East", aliases: ["hashemite kingdom of jordan"] },
  SAU: { isoA3: "SAU", name: "Saudi Arabia", color: "#15803d", cultureGroup: "Middle East", aliases: ["kingdom of saudi arabia"] },
  YEM: { isoA3: "YEM", name: "Yemen", color: "#b91c1c", cultureGroup: "Middle East", aliases: ["republic of yemen"] },
  OMN: { isoA3: "OMN", name: "Oman", color: "#dc2626", cultureGroup: "Middle East", aliases: ["sultanate of oman"] },
  ARE: { isoA3: "ARE", name: "United Arab Emirates", color: "#059669", cultureGroup: "Middle East", aliases: ["uae", "emirates"] },
  QAT: { isoA3: "QAT", name: "Qatar", color: "#881337", cultureGroup: "Middle East", aliases: ["state of qatar"] },
  KWT: { isoA3: "KWT", name: "Kuwait", color: "#16a34a", cultureGroup: "Middle East", aliases: ["state of kuwait"] },
  BHR: { isoA3: "BHR", name: "Bahrain", color: "#dc2626", cultureGroup: "Middle East", aliases: ["kingdom of bahrain"] },
  EGY: { isoA3: "EGY", name: "Egypt", color: "#d97706", cultureGroup: "North Africa", aliases: ["arab republic of egypt"] },
  LBY: { isoA3: "LBY", name: "Libya", color: "#16a34a", cultureGroup: "North Africa", aliases: ["state of libya"] },
  TUN: { isoA3: "TUN", name: "Tunisia", color: "#e11d48", cultureGroup: "North Africa", aliases: ["republic of tunisia"] },
  DZA: { isoA3: "DZA", name: "Algeria", color: "#059669", cultureGroup: "North Africa", aliases: ["people's democratic republic of algeria"] },
  MAR: { isoA3: "MAR", name: "Morocco", color: "#b91c1c", cultureGroup: "North Africa", aliases: ["kingdom of morocco"] },
  ESH: { isoA3: "ESH", name: "Western Sahara", color: "#ca8a04", cultureGroup: "North Africa", aliases: ["w. sahara", "sahrawi arab democratic republic"] },
  SDN: { isoA3: "SDN", name: "Sudan", color: "#047857", cultureGroup: "North Africa", aliases: ["republic of the sudan"] },
  SSD: { isoA3: "SSD", name: "South Sudan", color: "#1d4ed8", cultureGroup: "East Africa", aliases: ["s. sudan", "republic of south sudan"] },

  // East & Southeast Asia
  CHN: { isoA3: "CHN", name: "China", color: "#dc2626", cultureGroup: "East Asia", aliases: ["people's republic of china", "prc"] },
  JPN: { isoA3: "JPN", name: "Japan", color: "#e11d48", cultureGroup: "East Asia", aliases: ["nippon"] },
  KOR: { isoA3: "KOR", name: "South Korea", color: "#2563eb", cultureGroup: "East Asia", aliases: ["republic of korea", "korea"] },
  PRK: { isoA3: "PRK", name: "North Korea", color: "#991b1b", cultureGroup: "East Asia", aliases: ["democratic people's republic of korea", "dprk"] },
  MNG: { isoA3: "MNG", name: "Mongolia", color: "#2563eb", cultureGroup: "Central Asia" },
  TWN: { isoA3: "TWN", name: "Taiwan", color: "#0284c7", cultureGroup: "East Asia", aliases: ["republic of china", "formosa"] },
  HKG: { isoA3: "HKG", name: "Hong Kong", color: "#dc2626", cultureGroup: "East Asia" },
  MAC: { isoA3: "MAC", name: "Macau", color: "#059669", cultureGroup: "East Asia" },
  VNM: { isoA3: "VNM", name: "Vietnam", color: "#dc2626", cultureGroup: "Southeast Asia", aliases: ["socialist republic of vietnam", "viet nam"] },
  THA: { isoA3: "THA", name: "Thailand", color: "#2563eb", cultureGroup: "Southeast Asia", aliases: ["kingdom of thailand", "siam"] },
  MMR: { isoA3: "MMR", name: "Myanmar", color: "#ca8a04", cultureGroup: "Southeast Asia", aliases: ["burma", "republic of the union of myanmar"] },
  KHM: { isoA3: "KHM", name: "Cambodia", color: "#0284c7", cultureGroup: "Southeast Asia", aliases: ["kingdom of cambodia"] },
  LAO: { isoA3: "LAO", name: "Laos", color: "#1d4ed8", cultureGroup: "Southeast Asia", aliases: ["lao people's democratic republic"] },
  MYS: { isoA3: "MYS", name: "Malaysia", color: "#2563eb", cultureGroup: "Southeast Asia" },
  IDN: { isoA3: "IDN", name: "Indonesia", color: "#dc2626", cultureGroup: "Southeast Asia", aliases: ["republic of indonesia"] },
  PHL: { isoA3: "PHL", name: "Philippines", color: "#1d4ed8", cultureGroup: "Southeast Asia", aliases: ["republic of the philippines"] },
  SGP: { isoA3: "SGP", name: "Singapore", color: "#dc2626", cultureGroup: "Southeast Asia", aliases: ["republic of singapore"] },
  BRN: { isoA3: "BRN", name: "Brunei", color: "#ca8a04", cultureGroup: "Southeast Asia", aliases: ["brunei darussalam"] },
  TLS: { isoA3: "TLS", name: "Timor-Leste", color: "#dc2626", cultureGroup: "Southeast Asia", aliases: ["east timor", "democratic republic of timor-leste"] },

  // South & Central Asia & Caucasus
  IND: { isoA3: "IND", name: "India", color: "#ea580c", cultureGroup: "South Asia", aliases: ["republic of india", "bharat"] },
  PAK: { isoA3: "PAK", name: "Pakistan", color: "#047857", cultureGroup: "South Asia", aliases: ["islamic republic of pakistan"] },
  BGD: { isoA3: "BGD", name: "Bangladesh", color: "#065f46", cultureGroup: "South Asia", aliases: ["people's republic of bangladesh"] },
  LKA: { isoA3: "LKA", name: "Sri Lanka", color: "#b45309", cultureGroup: "South Asia", aliases: ["ceylon", "democratic socialist republic of sri lanka"] },
  NPL: { isoA3: "NPL", name: "Nepal", color: "#dc2626", cultureGroup: "South Asia", aliases: ["federal democratic republic of nepal"] },
  BTN: { isoA3: "BTN", name: "Bhutan", color: "#ea580c", cultureGroup: "South Asia", aliases: ["kingdom of bhutan"] },
  MDV: { isoA3: "MDV", name: "Maldives", color: "#059669", cultureGroup: "South Asia", aliases: ["republic of maldives"] },
  AFG: { isoA3: "AFG", name: "Afghanistan", color: "#15803d", cultureGroup: "Central Asia", aliases: ["islamic emirate of afghanistan"] },
  KAZ: { isoA3: "KAZ", name: "Kazakhstan", color: "#0284c7", cultureGroup: "Central Asia", aliases: ["republic of kazakhstan"] },
  UZB: { isoA3: "UZB", name: "Uzbekistan", color: "#0284c7", cultureGroup: "Central Asia", aliases: ["republic of uzbekistan"] },
  TKM: { isoA3: "TKM", name: "Turkmenistan", color: "#047857", cultureGroup: "Central Asia" },
  KGZ: { isoA3: "KGZ", name: "Kyrgyzstan", color: "#dc2626", cultureGroup: "Central Asia", aliases: ["kyrgyz republic"] },
  TJK: { isoA3: "TJK", name: "Tajikistan", color: "#16a34a", cultureGroup: "Central Asia", aliases: ["republic of tajikistan"] },
  AZE: { isoA3: "AZE", name: "Azerbaijan", color: "#0284c7", cultureGroup: "Caucasus", aliases: ["republic of azerbaijan"] },
  ARM: { isoA3: "ARM", name: "Armenia", color: "#ea580c", cultureGroup: "Caucasus", aliases: ["republic of armenia"] },
  GEO: { isoA3: "GEO", name: "Georgia", color: "#dc2626", cultureGroup: "Caucasus" },

  // Americas
  USA: { isoA3: "USA", name: "United States", color: "#1e40af", cultureGroup: "North America", aliases: ["united states of america", "usa", "us"] },
  CAN: { isoA3: "CAN", name: "Canada", color: "#dc2626", cultureGroup: "North America" },
  MEX: { isoA3: "MEX", name: "Mexico", color: "#047857", cultureGroup: "Latin America", aliases: ["united mexican states"] },
  BRA: { isoA3: "BRA", name: "Brazil", color: "#15803d", cultureGroup: "Latin America", aliases: ["federative republic of brazil", "brasil"] },
  ARG: { isoA3: "ARG", name: "Argentina", color: "#0284c7", cultureGroup: "Latin America", aliases: ["argentine republic"] },
  COL: { isoA3: "COL", name: "Colombia", color: "#ca8a04", cultureGroup: "Latin America", aliases: ["republic of colombia"] },
  PER: { isoA3: "PER", name: "Peru", color: "#dc2626", cultureGroup: "Latin America", aliases: ["republic of peru"] },
  CHL: { isoA3: "CHL", name: "Chile", color: "#2563eb", cultureGroup: "Latin America", aliases: ["republic of chile"] },
  VEN: { isoA3: "VEN", name: "Venezuela", color: "#ca8a04", cultureGroup: "Latin America", aliases: ["bolivarian republic of venezuela"] },
  ECU: { isoA3: "ECU", name: "Ecuador", color: "#ca8a04", cultureGroup: "Latin America", aliases: ["republic of ecuador"] },
  BOL: { isoA3: "BOL", name: "Bolivia", color: "#15803d", cultureGroup: "Latin America", aliases: ["plurinational state of bolivia"] },
  PRY: { isoA3: "PRY", name: "Paraguay", color: "#dc2626", cultureGroup: "Latin America", aliases: ["republic of paraguay"] },
  URY: { isoA3: "URY", name: "Uruguay", color: "#0284c7", cultureGroup: "Latin America", aliases: ["oriental republic of uruguay"] },
  GUY: { isoA3: "GUY", name: "Guyana", color: "#16a34a", cultureGroup: "Latin America", aliases: ["co-operative republic of guyana"] },
  SUR: { isoA3: "SUR", name: "Suriname", color: "#047857", cultureGroup: "Latin America", aliases: ["republic of suriname"] },
  GUF: { isoA3: "GUF", name: "French Guiana", color: "#2563eb", cultureGroup: "Latin America" },
  FLK: { isoA3: "FLK", name: "Falkland Islands", color: "#1d4ed8", cultureGroup: "Latin America", aliases: ["falkland is.", "islas malvinas"] },

  // Caribbean & Central America
  CUB: { isoA3: "CUB", name: "Cuba", color: "#1d4ed8", cultureGroup: "Caribbean", aliases: ["republic of cuba"] },
  HTI: { isoA3: "HTI", name: "Haiti", color: "#1e40af", cultureGroup: "Caribbean", aliases: ["republic of haiti"] },
  DOM: { isoA3: "DOM", name: "Dominican Republic", color: "#2563eb", cultureGroup: "Caribbean" },
  JAM: { isoA3: "JAM", name: "Jamaica", color: "#15803d", cultureGroup: "Caribbean" },
  PRI: { isoA3: "PRI", name: "Puerto Rico", color: "#dc2626", cultureGroup: "Caribbean", aliases: ["commonwealth of puerto rico"] },
  TTO: { isoA3: "TTO", name: "Trinidad and Tobago", color: "#dc2626", cultureGroup: "Caribbean", aliases: ["trinidad"] },
  BHS: { isoA3: "BHS", name: "Bahamas", color: "#0284c7", cultureGroup: "Caribbean", aliases: ["the bahamas", "commonwealth of the bahamas"] },
  BRB: { isoA3: "BRB", name: "Barbados", color: "#2563eb", cultureGroup: "Caribbean" },
  LCA: { isoA3: "LCA", name: "Saint Lucia", color: "#0284c7", cultureGroup: "Caribbean" },
  VCT: { isoA3: "VCT", name: "Saint Vincent and the Grenadines", color: "#15803d", cultureGroup: "Caribbean" },
  GRD: { isoA3: "GRD", name: "Grenada", color: "#ca8a04", cultureGroup: "Caribbean" },
  ATG: { isoA3: "ATG", name: "Antigua and Barbuda", color: "#dc2626", cultureGroup: "Caribbean" },
  KNA: { isoA3: "KNA", name: "Saint Kitts and Nevis", color: "#059669", cultureGroup: "Caribbean" },
  DMA: { isoA3: "DMA", name: "Dominica", color: "#16a34a", cultureGroup: "Caribbean", aliases: ["commonwealth of dominica"] },
  BLZ: { isoA3: "BLZ", name: "Belize", color: "#1d4ed8", cultureGroup: "Central America" },
  GTM: { isoA3: "GTM", name: "Guatemala", color: "#0284c7", cultureGroup: "Central America", aliases: ["republic of guatemala"] },
  HND: { isoA3: "HND", name: "Honduras", color: "#0284c7", cultureGroup: "Central America", aliases: ["republic of honduras"] },
  SLV: { isoA3: "SLV", name: "El Salvador", color: "#1d4ed8", cultureGroup: "Central America", aliases: ["republic of el salvador"] },
  NIC: { isoA3: "NIC", name: "Nicaragua", color: "#0284c7", cultureGroup: "Central America", aliases: ["republic of nicaragua"] },
  CRI: { isoA3: "CRI", name: "Costa Rica", color: "#1d4ed8", cultureGroup: "Central America", aliases: ["republic of costa rica"] },
  PAN: { isoA3: "PAN", name: "Panama", color: "#2563eb", cultureGroup: "Central America", aliases: ["republic of panama"] },
  GLP: { isoA3: "GLP", name: "Guadeloupe", color: "#0284c7", cultureGroup: "Caribbean" },
  MTQ: { isoA3: "MTQ", name: "Martinique", color: "#0284c7", cultureGroup: "Caribbean" },
  ANT: { isoA3: "ANT", name: "Netherlands Antilles", color: "#ea580c", cultureGroup: "Caribbean", aliases: ["curacao", "aruba", "bonaire", "sint maarten"] },
  MSR: { isoA3: "MSR", name: "Montserrat", color: "#15803d", cultureGroup: "Caribbean" },
  AIA: { isoA3: "AIA", name: "Anguilla", color: "#ca8a04", cultureGroup: "Caribbean" },
  BLM: { isoA3: "BLM", name: "Saint Barthelemy", color: "#2563eb", cultureGroup: "Caribbean" },
  MAF: { isoA3: "MAF", name: "Saint Martin", color: "#2563eb", cultureGroup: "Caribbean" },
  VIR: { isoA3: "VIR", name: "United States Virgin Islands", color: "#1e40af", cultureGroup: "Caribbean" },
  VGB: { isoA3: "VGB", name: "British Virgin Islands", color: "#1d4ed8", cultureGroup: "Caribbean" },
  CYM: { isoA3: "CYM", name: "Cayman Islands", color: "#ca8a04", cultureGroup: "Caribbean" },
  BMU: { isoA3: "BMU", name: "Bermuda", color: "#dc2626", cultureGroup: "North America" },

  // Sub-Saharan Africa
  NGA: { isoA3: "NGA", name: "Nigeria", color: "#047857", cultureGroup: "West Africa", aliases: ["federal republic of nigeria"] },
  ETH: { isoA3: "ETH", name: "Ethiopia", color: "#15803d", cultureGroup: "East Africa", aliases: ["federal democratic republic of ethiopia", "abyssinia"] },
  ZAF: { isoA3: "ZAF", name: "South Africa", color: "#047857", cultureGroup: "Southern Africa", aliases: ["republic of south africa"] },
  COD: { isoA3: "COD", name: "Dem. Rep. Congo", color: "#0284c7", cultureGroup: "Central Africa", aliases: ["democratic republic of the congo", "drc", "zaire"] },
  COG: { isoA3: "COG", name: "Congo", color: "#059669", cultureGroup: "Central Africa", aliases: ["republic of the congo", "congo-brazzaville"] },
  KEN: { isoA3: "KEN", name: "Kenya", color: "#b91c1c", cultureGroup: "East Africa", aliases: ["republic of kenya"] },
  TZA: { isoA3: "TZA", name: "Tanzania", color: "#0d9488", cultureGroup: "East Africa", aliases: ["united republic of tanzania", "zanzibar"] },
  GHA: { isoA3: "GHA", name: "Ghana", color: "#ca8a04", cultureGroup: "West Africa", aliases: ["republic of ghana", "gold coast"] },
  CIV: { isoA3: "CIV", name: "Ivory Coast", color: "#ea580c", cultureGroup: "West Africa", aliases: ["côte d'ivoire", "republic of côte d'ivoire"] },
  CMR: { isoA3: "CMR", name: "Cameroon", color: "#15803d", cultureGroup: "Central Africa", aliases: ["republic of cameroon"] },
  MDG: { isoA3: "MDG", name: "Madagascar", color: "#dc2626", cultureGroup: "East Africa", aliases: ["republic of madagascar"] },
  AGO: { isoA3: "AGO", name: "Angola", color: "#dc2626", cultureGroup: "Southern Africa", aliases: ["republic of angola"] },
  MOZ: { isoA3: "MOZ", name: "Mozambique", color: "#047857", cultureGroup: "Southern Africa", aliases: ["republic of mozambique"] },
  ZWE: { isoA3: "ZWE", name: "Zimbabwe", color: "#ca8a04", cultureGroup: "Southern Africa", aliases: ["republic of zimbabwe", "rhodesia"] },
  ZMB: { isoA3: "ZMB", name: "Zambia", color: "#15803d", cultureGroup: "Southern Africa", aliases: ["republic of zambia", "northern rhodesia"] },
  SEN: { isoA3: "SEN", name: "Senegal", color: "#15803d", cultureGroup: "West Africa", aliases: ["republic of senegal"] },
  MLI: { isoA3: "MLI", name: "Mali", color: "#ca8a04", cultureGroup: "West Africa", aliases: ["republic of mali"] },
  BFA: { isoA3: "BFA", name: "Burkina Faso", color: "#dc2626", cultureGroup: "West Africa", aliases: ["upper volta"] },
  NER: { isoA3: "NER", name: "Niger", color: "#ea580c", cultureGroup: "West Africa", aliases: ["republic of the niger"] },
  TCD: { isoA3: "TCD", name: "Chad", color: "#1d4ed8", cultureGroup: "Central Africa", aliases: ["republic of chad"] },
  SOM: { isoA3: "SOM", name: "Somalia", color: "#0284c7", cultureGroup: "East Africa", aliases: ["federal republic of somalia", "somaliland"] },
  UGA: { isoA3: "UGA", name: "Uganda", color: "#ca8a04", cultureGroup: "East Africa", aliases: ["republic of uganda"] },
  RWA: { isoA3: "RWA", name: "Rwanda", color: "#0284c7", cultureGroup: "East Africa", aliases: ["republic of rwanda"] },
  BDI: { isoA3: "BDI", name: "Burundi", color: "#dc2626", cultureGroup: "East Africa", aliases: ["republic of burundi"] },
  NAM: { isoA3: "NAM", name: "Namibia", color: "#0284c7", cultureGroup: "Southern Africa", aliases: ["republic of namibia", "south west africa"] },
  BWA: { isoA3: "BWA", name: "Botswana", color: "#0284c7", cultureGroup: "Southern Africa", aliases: ["republic of botswana", "bechuanaland"] },
  SWZ: { isoA3: "SWZ", name: "Swaziland", color: "#b45309", cultureGroup: "Southern Africa", aliases: ["eswatini", "kingdom of eswatini"] },
  LSO: { isoA3: "LSO", name: "Lesotho", color: "#1d4ed8", cultureGroup: "Southern Africa", aliases: ["kingdom of lesotho", "basutoland"] },
  MWI: { isoA3: "MWI", name: "Malawi", color: "#991b1b", cultureGroup: "Southern Africa", aliases: ["republic of malawi", "nyasaland"] },
  BEN: { isoA3: "BEN", name: "Benin", color: "#ca8a04", cultureGroup: "West Africa", aliases: ["dahomey", "republic of benin"] },
  TGO: { isoA3: "TGO", name: "Togo", color: "#ca8a04", cultureGroup: "West Africa", aliases: ["togolese republic"] },
  SLE: { isoA3: "SLE", name: "Sierra Leone", color: "#047857", cultureGroup: "West Africa", aliases: ["republic of sierra leone"] },
  LBR: { isoA3: "LBR", name: "Liberia", color: "#dc2626", cultureGroup: "West Africa", aliases: ["republic of liberia"] },
  GIN: { isoA3: "GIN", name: "Guinea", color: "#dc2626", cultureGroup: "West Africa", aliases: ["republic of guinea", "french guinea"] },
  GNB: { isoA3: "GNB", name: "Guinea-Bissau", color: "#ea580c", cultureGroup: "West Africa", aliases: ["portuguese guinea"] },
  GMB: { isoA3: "GMB", name: "Gambia", color: "#1d4ed8", cultureGroup: "West Africa", aliases: ["the gambia", "republic of the gambia"] },
  MRT: { isoA3: "MRT", name: "Mauritania", color: "#047857", cultureGroup: "North Africa", aliases: ["islamic republic of mauritania"] },
  DJI: { isoA3: "DJI", name: "Djibouti", color: "#0284c7", cultureGroup: "East Africa", aliases: ["french somaliland"] },
  ERI: { isoA3: "ERI", name: "Eritrea", color: "#ea580c", cultureGroup: "East Africa", aliases: ["state of eritrea"] },
  GAB: { isoA3: "GAB", name: "Gabon", color: "#15803d", cultureGroup: "Central Africa", aliases: ["gabonese republic"] },
  GNQ: { isoA3: "GNQ", name: "Equatorial Guinea", color: "#059669", cultureGroup: "Central Africa", aliases: ["eq. guinea", "spanish guinea"] },
  CAF: { isoA3: "CAF", name: "Central African Republic", color: "#ca8a04", cultureGroup: "Central Africa", aliases: ["central african rep.", "ubangi-shari"] },
  CPV: { isoA3: "CPV", name: "Cape Verde", color: "#1d4ed8", cultureGroup: "West Africa", aliases: ["cabo verde"] },
  STP: { isoA3: "STP", name: "Sao Tome and Principe", color: "#15803d", cultureGroup: "Central Africa" },
  SYC: { isoA3: "SYC", name: "Seychelles", color: "#0284c7", cultureGroup: "East Africa" },
  MUS: { isoA3: "MUS", name: "Mauritius", color: "#dc2626", cultureGroup: "East Africa" },
  COM: { isoA3: "COM", name: "Comoros", color: "#15803d", cultureGroup: "East Africa" },

  // Oceania
  AUS: { isoA3: "AUS", name: "Australia", color: "#047857", cultureGroup: "Oceania", aliases: ["commonwealth of australia"] },
  NZL: { isoA3: "NZL", name: "New Zealand", color: "#1d4ed8", cultureGroup: "Oceania", aliases: ["aotearoa"] },
  PNG: { isoA3: "PNG", name: "Papua New Guinea", color: "#dc2626", cultureGroup: "Oceania", aliases: ["png"] },
  FJI: { isoA3: "FJI", name: "Fiji", color: "#0284c7", cultureGroup: "Oceania", aliases: ["republic of fiji"] },
  SLB: { isoA3: "SLB", name: "Solomon Islands", color: "#047857", cultureGroup: "Oceania", aliases: ["solomon is."] },
  VUT: { isoA3: "VUT", name: "Vanuatu", color: "#dc2626", cultureGroup: "Oceania", aliases: ["new hebrides"] },
  NCL: { isoA3: "NCL", name: "New Caledonia", color: "#0284c7", cultureGroup: "Oceania" },
  WSM: { isoA3: "WSM", name: "Samoa", color: "#dc2626", cultureGroup: "Oceania", aliases: ["western samoa", "independent state of samoa"] },
  ASM: { isoA3: "ASM", name: "American Samoa", color: "#1e40af", cultureGroup: "Oceania" },
  TON: { isoA3: "TON", name: "Tonga", color: "#dc2626", cultureGroup: "Oceania", aliases: ["kingdom of tonga"] },
  FSM: { isoA3: "FSM", name: "Micronesia", color: "#0284c7", cultureGroup: "Oceania", aliases: ["federated states of micronesia"] },
  PLW: { isoA3: "PLW", name: "Palau", color: "#0284c7", cultureGroup: "Oceania", aliases: ["republic of palau"] },
  MHL: { isoA3: "MHL", name: "Marshall Islands", color: "#0284c7", cultureGroup: "Oceania" },
  KIR: { isoA3: "KIR", name: "Kiribati", color: "#ea580c", cultureGroup: "Oceania" },
  TUV: { isoA3: "TUV", name: "Tuvalu", color: "#0284c7", cultureGroup: "Oceania", aliases: ["ellis islands"] },
  NRU: { isoA3: "NRU", name: "Nauru", color: "#1d4ed8", cultureGroup: "Oceania" },
  NIU: { isoA3: "NIU", name: "Niue", color: "#ca8a04", cultureGroup: "Oceania" },
  COK: { isoA3: "COK", name: "Cook Islands", color: "#1d4ed8", cultureGroup: "Oceania" },
  PYF: { isoA3: "PYF", name: "French Polynesia", color: "#0284c7", cultureGroup: "Oceania", aliases: ["tahiti"] },
  WLF: { isoA3: "WLF", name: "Wallis and Futuna Islands", color: "#dc2626", cultureGroup: "Oceania", aliases: ["wallis and futuna"] },
}

// Build fast normalized name lookup
export const MODERN_PALETTE_BY_NAME = new Map<string, ModernCountryColor>()

for (const item of Object.values(MODERN_COUNTRY_PALETTE)) {
  MODERN_PALETTE_BY_NAME.set(item.name.toLowerCase(), item)
  if (item.aliases) {
    for (const alias of item.aliases) {
      MODERN_PALETTE_BY_NAME.set(alias.toLowerCase(), item)
    }
  }
}
