import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "./seed_culture_metadata_batch"

const WEST_AFRICA_CULTURES: CultureBatchEntry[] = [
  {
    slug: "west-african-cereal-farmers",
    name: "Early West African Cereal Farmers",
    name_fi: "Varhaiset länsiafrikkalaiset viljanviljelijät",
    alternate_names: ["Sahelian Pastoralists and Farmers", "Nok Horizon"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Neolithic to Early Iron Age West Africa",
    year_start: -4000,
    year_end: 500,
    period_label: "4000 BCE – 500 CE",
    period_label_fi: "4000 eaa. – 500 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Nok_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Nok-kulttuuri",
    wikidata_id: "Q836371",
    summary_en: "Ancient agriculturalists and ironworkers across the West African Sahel and savanna who domesticated pearl millet, sorghum, and African rice, culminating in the refined terracotta sculptures and metallurgy of the Nok culture.",
    summary_fi: "Länsi-Afrikan Sahelin ja savannivyöhykkeen varhaiset viljelijät, jotka ottivat viljelyyn helmihirssin ja afrikkalaisen riisin sekä loivat Nok-kulttuurin kuuluisat terrakottaveistokset ja raudanvalun.",
    capital: "Dhar Tichitt, Nok",
    feature_name_matches: ["West African cereal farmers"]
  },
  {
    slug: "bantu-peoples",
    name: "Early Bantu Peoples",
    name_fi: "Varhaiset bantukansat",
    native_name: "Bantu",
    alternate_names: ["Bantu", "Bantu peoples", "Bantu Expansion"],
    culture_group: "West Africa",
    lineage_id: "bantu",
    historical_period: "Prehistoric to Iron Age Migration",
    year_start: -2000,
    year_end: 1000,
    period_label: "2000 BCE – 1000 CE",
    period_label_fi: "2000 eaa. – 1000 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Bantu_expansion",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bantut",
    wikidata_id: "Q173371",
    summary_en: "Originating in the Cameroon-Nigeria borderlands, Bantu speakers underwent one of humanity's greatest migrations, spreading agriculture, ceramic traditions, and ironworking across Central, Eastern, and Southern Africa.",
    summary_fi: "Kamerunin ja Nigerian rajaseuduilta lähteneet bantukansat levittäytyivät vuosituhansien kuluessa Keski-, Itä- ja Etelä-Afrikkaan tuoden mukanaan maatalouden, keramiikan ja raudanvalutaidon.",
    capital: "Cross River / Grassfields",
    feature_name_matches: ["Bantu", "Bantu peoples"]
  },
  {
    slug: "empire-of-ghana",
    name: "Ghana Empire & Modern Ghana",
    name_fi: "Ghanan valtakunta ja moderni Ghana",
    native_name: "Wagadou / Ghana",
    alternate_names: ["Empire of Ghana", "Wagadou", "Gold Coast", "Gold Coast (GB)", "Ghana"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Classical to Modern West Africa",
    year_start: 300,
    year_end: 2026,
    period_label: "300 CE – Present",
    period_label_fi: "300 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Ghana_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ghanan_kuningaskunta",
    wikidata_id: "Q206789",
    summary_en: "First major trans-Saharan Sahelian empire founded by the Soninke people, famed as the Land of Gold. Its proud name was adopted by the modern Republic of Ghana in 1957 under Kwame Nkrumah.",
    summary_fi: "Varhainen soninkekansan perustama trans-Saharan kultakaupan suurvalta Wagadou, jonka historiallisen nimen itsenäinen Ghana otti käyttöön vuonna 1957 Kwame Nkrumahin johdolla.",
    capital: "Koumbi Saleh, Accra",
    feature_name_matches: ["Empire of Ghana", "Ghana", "Gold Coast", "Gold Coast (GB)"]
  },
  {
    slug: "mali-empire",
    name: "Mali Empire & Modern Mali",
    name_fi: "Malin valtakunta ja moderni Mali",
    native_name: "Manden Kurufaba",
    alternate_names: ["Mali", "Manden Empire"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Medieval to Modern Sahel",
    year_start: 1235,
    year_end: 2026,
    period_label: "1235 CE – Present",
    period_label_fi: "1235 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Mali_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Malin_kuningaskunta",
    wikidata_id: "Q42735",
    summary_en: "Renowned Mandinka empire founded by Sundiata Keita, celebrated for astronomical wealth under Mansa Musa, the constitutional Kouroukan Fouga charter, and Islamic universities at Timbuktu and Djenné.",
    summary_fi: "Sundiata Keitan perustama mandinkojen keisarikunta, joka nousi Mansa Musan johdolla maailman maineeseen kultavarannoistaan ja Timbuktun ja Djennén yliopistoistaan.",
    capital: "Niani, Kangaba, Bamako",
    feature_name_matches: ["Mali"]
  },
  {
    slug: "songhai-empire",
    name: "Songhai Empire",
    name_fi: "Songhai-valtakunta",
    native_name: "Songhai",
    alternate_names: ["Songhay Empire"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Early Modern Western Sahel",
    year_start: 1464,
    year_end: 1591,
    period_label: "1464 CE – 1591 CE",
    period_label_fi: "1464 jaa. – 1591 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Songhai_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Songhai",
    wikidata_id: "Q202687",
    summary_en: "Largest imperial state in West African history, created by Sonni Ali and Askia Muhammad, commanding Niger River trade, establishing standard weights and measures, and patronizing Sankore Madrasah in Timbuktu.",
    summary_fi: "Yksi Länsi-Afrikan historian laajimmista imperiumeista, jonka Sonni Ali ja Askia Muhammad nostivat Niger-joen kaupan ja islamin oppineisuuden mahtitekijäksi.",
    capital: "Gao",
    feature_name_matches: ["Songhai"]
  },
  {
    slug: "kanem-bornu-empire",
    name: "Kanem-Bornu Empire",
    name_fi: "Kanem-Bornun valtakunta",
    native_name: "Kanem-Bornu",
    alternate_names: ["Kanem", "Kanem-Bornu", "Sayfawa Dynasty"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Classical to 19th Century Lake Chad Basin",
    year_start: 700,
    year_end: 1893,
    period_label: "700 CE – 1893 CE",
    period_label_fi: "700 jaa. – 1893 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kanem%E2%80%93Bornu_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kanem-Bornu",
    wikidata_id: "Q148419",
    summary_en: "Enduring Lake Chad basin empire ruled for a millennium by the Sayfawa dynasty, controlling trans-Saharan trade routes to Tripoli and fielding armored cavalry armed with Turkish firearms.",
    summary_fi: "Tšadjärven altaan vuosituhantinen imperiumi, jota Sayfawa-dynastia hallitsi valvoen Saharan ylittäviä kauppareittejä aina Välimerelle asti.",
    capital: "Njimi, Ngazargamu",
    feature_name_matches: ["Kanem", "Kanem-Bornu"]
  },
  {
    slug: "hausa-kingdoms",
    name: "Hausa Kingdoms",
    name_fi: "Hausavaltiot",
    native_name: "Kasashen Hausa",
    alternate_names: ["Hausa States", "Hausa Bakwai"],
    culture_group: "West Africa",
    lineage_id: "nigeria",
    historical_period: "Medieval to Early Modern Northern Nigeria",
    year_start: 1000,
    year_end: 1804,
    period_label: "1000 CE – 1804 CE",
    period_label_fi: "1000 jaa. – 1804 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Hausa_Kingdoms",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Hausat",
    wikidata_id: "Q1255869",
    summary_en: "Confederation of prosperous walled city-states (Kano, Katsina, Zaria, Gobir, Daura, Rano, Biram) specializing in indigo dyeing, leatherwork, and trans-Saharan commerce.",
    summary_fi: "Pohjois-Nigerian vauraat muurien ympäröimät kaupunkivaltiot (Kano, Katsina, Zaria ym.), jotka tunnettiin indigovärjäyksestä, nahkakaupasta ja vilkkaasta Saharan kaupasta.",
    capital: "Kano, Katsina, Daura",
    feature_name_matches: ["Hausa States"]
  },
  {
    slug: "oyo-empire",
    name: "Oyo Empire & Modern Nigeria",
    name_fi: "Oyon valtakunta ja moderni Nigeria",
    native_name: "Ilẹ̀ Ọba Ọ̀yọ́ / Nigeria",
    alternate_names: ["Oyo", "Yoruba Kingdom", "Nigeria"],
    culture_group: "West Africa",
    lineage_id: "nigeria",
    historical_period: "Post-Classical to Modern Nigeria",
    year_start: 1300,
    year_end: 2026,
    period_label: "1300 CE – Present",
    period_label_fi: "1300 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Oyo_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Oyo_(valtakunta)",
    wikidata_id: "Q849448",
    summary_en: "Formidable Yoruba empire in southwest Nigeria with disciplined cavalry armies and check-and-balance governance under the Alaafin and Oyo Mesi, evolving into modern Africa's most populous nation.",
    summary_fi: "Lounais-Nigerian mahtava jorubavaltakunta, joka nojasi kurinalaiseen ratsuväkeen ja perinteiseen vallanjakoon ja jonka alueelle muodostui nykyinen väkirikas Nigeria.",
    capital: "Oyo-Ile, Abuja, Lagos",
    feature_name_matches: ["Oyo", "Nigeria"]
  },
  {
    slug: "benin-kingdom",
    name: "Kingdom of Benin",
    name_fi: "Beninin kuningaskunta",
    native_name: "Arhuanran n'Edo",
    alternate_names: ["Edo Empire", "Benin"],
    culture_group: "West Africa",
    lineage_id: "nigeria",
    historical_period: "Medieval to 19th Century Southern Nigeria",
    year_start: 1180,
    year_end: 1897,
    period_label: "1180 CE – 1897 CE",
    period_label_fi: "1180 jaa. – 1897 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Benin",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Beninin_kuningaskunta",
    wikidata_id: "Q272997",
    summary_en: "Renowned Edo kingdom in the tropical rainforest of southern Nigeria, celebrated for monumental earthwork walls and world-famous cast bronze and brass artworks commissioned by the Oba.",
    summary_fi: "Etelä-Nigerian sademetsävyöhykkeen edokansan kuningaskunta, joka tunnetaan valtavista maavalleistaan ja hovin valamista maailmankuuluista pronssi- ja messinkiveistoksista.",
    capital: "Benin City (Edo)",
    feature_name_matches: ["Benin"]
  },
  {
    slug: "dahomey-kingdom",
    name: "Kingdom of Dahomey",
    name_fi: "Dahomeyn kuningaskunta",
    native_name: "Danxome",
    alternate_names: ["Dahomey", "Fon Kingdom"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Early Modern coastal West Africa",
    year_start: 1600,
    year_end: 1904,
    period_label: "1600 CE – 1904 CE",
    period_label_fi: "1600 jaa. – 1904 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Dahomey",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Dahomey",
    wikidata_id: "Q46880",
    summary_en: "Militarized Fon kingdom on the Bight of Benin famed for royal palaces at Abomey, extensive trade, and the Dahomey Amazons (Ahosi), an elite all-female front-line military regiment.",
    summary_fi: "Fon-kansan sotilaallisesti vahva kuningaskunta Guineanlahden rannikolla, joka tunnettiin Abomeyn kuninkaallisista palatseista ja naissoturien eliittirykmentistä (Dahomeyn amatsonit).",
    capital: "Abomey",
    feature_name_matches: ["Dahomey"]
  },
  {
    slug: "ashanti-empire",
    name: "Ashanti Empire & Akan States",
    name_fi: "Ašanti-valtakunta ja akan-valtiot",
    native_name: "Asanteman",
    alternate_names: ["Asante", "Akan", "Fante", "Ashanti Confederacy"],
    culture_group: "West Africa",
    lineage_id: "ghana",
    historical_period: "Early Modern to Colonial Ghana",
    year_start: 1670,
    year_end: 1902,
    period_label: "1670 CE – 1902 CE",
    period_label_fi: "1670 jaa. – 1902 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Ashanti_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/A%C5%A1anti",
    wikidata_id: "Q153164",
    summary_en: "Powerful Akan empire founded by Osei Tutu I united by the sacred Golden Stool (Sika Dwa), commanding gold mining, kente weaving, and fighting five Anglo-Ashanti wars against British forces.",
    summary_fi: "Akan-kansan mahtava imperiumi nykyisen Ghanan sademetsissä, jonka pyhä Kultainen jakkara yhdisti ja joka tunnetaan kultakaupasta, kente-kankaista ja sitkeästä vastarinnastaan brittijoukkoja vastaan.",
    capital: "Kumasi",
    feature_name_matches: ["Asante", "Akan", "Fante"]
  },
  {
    slug: "mossi-kingdoms",
    name: "Mossi Kingdoms & Burkina Faso",
    name_fi: "Mossivaltiot ja Burkina Faso",
    native_name: "Moogo / Burkina Faso",
    alternate_names: ["Mossi States", "Ouagadougou Kingdom", "Burkina Faso"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Medieval to Modern Upper Volta Basin",
    year_start: 1050,
    year_end: 2026,
    period_label: "1050 CE – Present",
    period_label_fi: "1050 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Mossi_Kingdoms",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Mossi",
    wikidata_id: "Q854089",
    summary_en: "Enduring equestrian kingdoms founded by legendary warrior princess Yennenga, maintaining political independence and ancestral spiritual traditions against imperial Mali, Songhai, and French rule.",
    summary_fi: "Mossikansan soturivaltakunnat nykyisessä Burkina Fasossa, jotka torjuivat Malin ja Songhain valloitukset ja säilyttivät itsenäisyytensä vuosisatojen ajan.",
    capital: "Ouagadougou, Tenkodogo, Yatenga",
    feature_name_matches: ["Mossi States", "Burkina Faso"]
  },
  {
    slug: "sokoto-fulani-empire",
    name: "Sokoto Caliphate & Fulani Empire",
    name_fi: "Sokoton kalifaatti ja fulani-imperiumi",
    native_name: "Daular Daular Usmaniyya",
    alternate_names: ["Fulani Empire", "Sokoto Caliphate"],
    culture_group: "West Africa",
    lineage_id: "nigeria",
    historical_period: "19th Century Islamic Sahel",
    year_start: 1804,
    year_end: 1903,
    period_label: "1804 CE – 1903 CE",
    period_label_fi: "1804 jaa. – 1903 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sokoto_Caliphate",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sokoton_kalifaatti",
    wikidata_id: "Q26576",
    summary_en: "Sunni Islamic empire founded by Usman dan Fodio during the Fulani jihads, uniting the Hausa city-states into the largest and most prosperous state in 19th-century sub-Saharan Africa.",
    summary_fi: "Usman dan Fodion perustama islamilainen kalifaatti Pohjois-Nigeriassa, joka yhdisti hausavaltiot ja muodosti 1800-luvun Saharan eteläpuolisen Afrikan suurimman valtion.",
    capital: "Sokoto, Gwandu",
    feature_name_matches: ["Fulani Empire"]
  },
  {
    slug: "wassoulou-empire",
    name: "Wassoulou Empire",
    name_fi: "Wassouloun valtakunta",
    native_name: "Wassoulou",
    alternate_names: ["Mandinka Empire", "Samori Empire"],
    culture_group: "West Africa",
    lineage_id: "west-africa",
    historical_period: "Late 19th Century Anti-Colonial State",
    year_start: 1878,
    year_end: 1898,
    period_label: "1878 CE – 1898 CE",
    period_label_fi: "1878 jaa. – 1898 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Wassoulou_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Samori_Tour%C3%A9",
    wikidata_id: "Q556608",
    summary_en: "Short-lived but powerful Mandinka empire created by Samori Ture with a modernized rifle-armed army and mobile gunpowder manufactories, fiercely resisting French colonial conquest across Guinea and Mali.",
    summary_fi: "Samori Tourén luoma mandinkavaltakunta Guinean ja Malin alueella, joka nojasi modernisoituun kivääriarmeijaan ja vastusti pitkään Ranskan siirtomaavaltausta.",
    capital: "Bissandugu",
    feature_name_matches: ["Wassoulou Empire"]
  },
  {
    slug: "wadai-empire",
    name: "Wadai Sultanate",
    name_fi: "Ouaddain sulttaanikunta",
    native_name: "سلطنة وداي",
    alternate_names: ["Wadai", "Wadai Empire", "Ouaddai"],
    culture_group: "West Africa",
    lineage_id: "chad",
    historical_period: "Early Modern to Colonial Eastern Sahel",
    year_start: 1635,
    year_end: 1912,
    period_label: "1635 CE – 1912 CE",
    period_label_fi: "1635 jaa. – 1912 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Wadai_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Wadain_sulttaanikunta",
    wikidata_id: "Q889601",
    summary_en: "Non-Arab Muslim sultanate located east of Lake Chad in modern Chad, controlling critical trans-Saharan caravan routes to Benghazi and resisting French colonial occupation until 1912.",
    summary_fi: "Itä-Tšadissa sijainnut islamilainen sulttaanikunta, joka valvoi trans-Saharan karavaanireittejä Välimerelle ja teki sitkeää vastarintaa Ranskan siirtomaajoukkoja vastaan.",
    capital: "Wara, Abéché",
    feature_name_matches: ["Wadai", "Wadai Empire"]
  },
  {
    slug: "senegal-jolof",
    name: "Jolof Empire & Republic of Senegal",
    name_fi: "Jolofin valtakunta ja Senegalin tasavalta",
    native_name: "Ndiambour / Sénégal",
    alternate_names: ["Senegal", "Senegal (FR)", "Wolof Empire"],
    culture_group: "West Africa",
    lineage_id: "senegal",
    historical_period: "Medieval to Modern Senegambia",
    year_start: 1350,
    year_end: 2026,
    period_label: "1350 CE – Present",
    period_label_fi: "1350 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Jolof_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Senegal",
    wikidata_id: "Q1049",
    summary_en: "Wolof empire spanning the Senegal and Gambia rivers, succeeded by kingdoms (Cayor, Baol, Waalo, Sine, Saloum) and modern democratic Senegal, celebrated for Teranga hospitality and arts.",
    summary_fi: "Wolofien historiallinen Jolof-valtakunta Senegambian jokialueella, josta kehittyi vakaa moderni Senegalin tasavalta tunnettuine Teranga-vieraanvaraisuuksineen.",
    capital: "Linguère, Dakar, Saint-Louis",
    feature_name_matches: ["Senegal", "Senegal (FR)"]
  },
  {
    slug: "republic-of-the-gambia",
    name: "Republic of The Gambia",
    name_fi: "Gambian tasavalta",
    native_name: "The Gambia",
    alternate_names: ["Gambia"],
    culture_group: "West Africa",
    lineage_id: "gambia",
    historical_period: "Colonial to Modern Senegambia",
    year_start: 1821,
    year_end: 2026,
    period_label: "1821 CE – Present",
    period_label_fi: "1821 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/The_Gambia",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gambia",
    wikidata_id: "Q1005",
    summary_en: "Smallest sovereign nation in mainland Africa, flanking both sides of the navigable Gambia River, historically contested between Britain and France, gaining full independence in 1965.",
    summary_fi: "Manner-Afrikan pienin valtio Gambia-joen molemmin puolin, joka toimi brittiläisenä siirtokuntana ja saavutti itsenäisyytensä vuonna 1965.",
    capital: "Banjul",
    feature_name_matches: ["Gambia"]
  },
  {
    slug: "republic-of-guinea",
    name: "Republic of Guinea",
    name_fi: "Guinean tasavalta",
    native_name: "Guinée",
    alternate_names: ["Guinea", "French Guinea"],
    culture_group: "West Africa",
    lineage_id: "guinea",
    historical_period: "Colonial to Modern Guinea",
    year_start: 1891,
    year_end: 2026,
    period_label: "1891 CE – Present",
    period_label_fi: "1891 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Guinea",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Guinea",
    wikidata_id: "Q1006",
    summary_en: "Coastal West African nation rich in bauxite and gold, source of the Niger and Senegal rivers in the Fouta Djallon highlands, achieving independence under Ahmed Sékou Touré in 1958.",
    summary_fi: "Länsi-Afrikan rannikkovaltio, jonka Fouta Djallonin ylängöiltä saavat alkunsa Niger- ja Senegal-joet ja joka itsenäistyi Ranskasta ensimmäisenä vuonna 1958.",
    capital: "Conakry",
    feature_name_matches: ["Guinea"]
  },
  {
    slug: "guinea-bissau",
    name: "Republic of Guinea-Bissau",
    name_fi: "Guinea-Bissaun tasavalta",
    native_name: "Guiné-Bissau",
    alternate_names: ["Portuguese Guinea", "Guinea-Bissau", "Guinea-Bissau (Portugal)"],
    culture_group: "West Africa",
    lineage_id: "guinea-bissau",
    historical_period: "Colonial to Modern West Africa",
    year_start: 1588,
    year_end: 2026,
    period_label: "1588 CE – Present",
    period_label_fi: "1588 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Guinea-Bissau",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Guinea-Bissau",
    wikidata_id: "Q1007",
    summary_en: "Tropical coastal nation encompassing the Bijagós Archipelago, colonized by Portugal as Portuguese Guinea and gaining independence in 1973 following Amílcar Cabral's liberation struggle.",
    summary_fi: "Länsi-Afrikan rannikkovaltio ja Bijagóssaaret, joka oli Portugalin siirtomaana ja saavutti itsenäisyyden Amílcar Cabralin johtaman vapaustaistelun jälkeen vuonna 1973.",
    capital: "Bissau",
    feature_name_matches: [
      "Guinea-Bissau",
      "Guinea-Bissau (Portugal)",
      "Portuguese Guinea"
    ]
  },
  {
    slug: "republic-of-sierra-leone",
    name: "Republic of Sierra Leone",
    name_fi: "Sierra Leonen tasavalta",
    native_name: "Sierra Leone",
    alternate_names: ["Sierra Leone"],
    culture_group: "West Africa",
    lineage_id: "sierra-leone",
    historical_period: "Colonial to Modern Coastal West Africa",
    year_start: 1787,
    year_end: 2026,
    period_label: "1787 CE – Present",
    period_label_fi: "1787 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sierra_Leone",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sierra_Leone",
    wikidata_id: "Q1044",
    summary_en: "West African Atlantic republic founded in 1787 as Freetown by British abolitionists as a resettlement haven for formerly enslaved Black Loyalists and recaptives, known as Krio people.",
    summary_fi: "Atlantin rannikon valtio, jonka pääkaupungin Freetownin brittiläiset orjuudenvastustajat perustivat vuonna 1787 vapautetuille orjille ja josta muodostui krio-kulttuuri.",
    capital: "Freetown",
    feature_name_matches: ["Sierra Leone"]
  },
  {
    slug: "republic-of-liberia",
    name: "Republic of Liberia",
    name_fi: "Liberian tasavalta",
    native_name: "Republic of Liberia",
    alternate_names: ["Liberia"],
    culture_group: "West Africa",
    lineage_id: "liberia",
    historical_period: "Modern Sovereign Republic",
    year_start: 1822,
    year_end: 2026,
    period_label: "1822 CE – Present",
    period_label_fi: "1822 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Liberia",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Liberia",
    wikidata_id: "Q1014",
    summary_en: "Africa's oldest modern republic, declared independent in 1847 by freed African Americans supported by the American Colonization Society, maintaining sovereignty throughout the Scramble for Africa.",
    summary_fi: "Afrikan vanhin moderni tasavalta, jonka Yhdysvalloista palanneet vapautetut afroamerikkalaiset perustivat ja joka julistautui itsenäiseksi vuonna 1847 säilyttäen itsenäisyytensä siirtomaa-aikana.",
    capital: "Monrovia",
    feature_name_matches: ["Liberia"]
  },
  {
    slug: "republic-of-cote-divoire",
    name: "Republic of Côte d'Ivoire",
    name_fi: "Norsunluurannikon tasavalta",
    native_name: "Côte d'Ivoire",
    alternate_names: ["Ivory Coast"],
    culture_group: "West Africa",
    lineage_id: "cote-divoire",
    historical_period: "Colonial to Modern West Africa",
    year_start: 1893,
    year_end: 2026,
    period_label: "1893 CE – Present",
    period_label_fi: "1893 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Ivory_Coast",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Norsunluurannikko",
    wikidata_id: "Q1008",
    summary_en: "Prosperous West African nation on the Gulf of Guinea, the world's leading producer of cocoa, achieving independence from France in 1960 under longtime leader Félix Houphouët-Boigny.",
    summary_fi: "Guineanlahden rannikkovaltio ja maailman johtava kaakaontuottaja, joka itsenäistyi Ranskasta vuonna 1960 pitkäaikaisen presidenttinsä Félix Houphouët-Boignyn johdolla.",
    capital: "Yamoussoukro, Abidjan",
    feature_name_matches: ["Ivory Coast"]
  },
  {
    slug: "togolese-republic",
    name: "Togolese Republic",
    name_fi: "Togon tasavalta",
    native_name: "Togo",
    alternate_names: ["Togo", "French Togoland"],
    culture_group: "West Africa",
    lineage_id: "togo",
    historical_period: "Colonial to Modern West Africa",
    year_start: 1884,
    year_end: 2026,
    period_label: "1884 CE – Present",
    period_label_fi: "1884 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Togo",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Togo",
    wikidata_id: "Q945",
    summary_en: "Narrow West African republic along the Gulf of Guinea, formerly German Togoland and a French mandate, home to the UNESCO World Heritage mud-tower fortifications of Koutammakou.",
    summary_fi: "Kapea Länsi-Afrikan valtio Guineanlahdella, entinen Saksan ja Ranskan siirtomaa-alue, joka tunnetaan Koutammakoun Unescon suojelemista savilinnoituksista.",
    capital: "Lomé",
    feature_name_matches: ["Togo"]
  },
  {
    slug: "republic-of-niger",
    name: "Republic of Niger",
    name_fi: "Nigerin tasavalta",
    native_name: "Niger",
    alternate_names: ["Niger"],
    culture_group: "West Africa",
    lineage_id: "niger",
    historical_period: "Colonial to Modern Sahel",
    year_start: 1922,
    year_end: 2026,
    period_label: "1922 CE – Present",
    period_label_fi: "1922 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Niger",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Niger",
    wikidata_id: "Q1032",
    summary_en: "Landlocked Sahelian nation named after the Niger River, home to ancient caravan cities like Agadez, prominent Tuareg and Hausa communities, and rich uranium deposits.",
    summary_fi: "Sisämaavaltio Sahelin vyöhykkeellä Niger-joen varrella, jossa yhdistyvät tuaregien ja hausojen kulttuurit ja historiallinen Agadezin aavikkokaupunki.",
    capital: "Niamey",
    feature_name_matches: ["Niger"]
  }
]

const outPath = path.resolve(__dirname, "../data-sources/batches/west-africa.json")
fs.writeFileSync(outPath, JSON.stringify(WEST_AFRICA_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${WEST_AFRICA_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(WEST_AFRICA_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
