import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "./seed_culture_metadata_batch"

const SOUTHERN_AFRICA_CULTURES: CultureBatchEntry[] = [
  {
    slug: "khoisan-peoples",
    name: "San & Khoekhoe Peoples (Khoisan)",
    name_fi: "Sanit ja khoikhoit (khoisan)",
    native_name: "Khoekhoen / Kx'a",
    alternate_names: ["Khoisan", "Bushmen", "San", "Khoekhoe"],
    culture_group: "Southern Africa",
    lineage_id: "southern-africa",
    historical_period: "Prehistoric to Modern Southern Africa",
    year_start: -10000,
    year_end: 2026,
    period_label: "10,000 BCE – Present",
    period_label_fi: "10 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Khoisan",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Khoisanit",
    wikidata_id: "Q207431",
    summary_en: "Indigenous click-language hunting and herding peoples of Southern Africa, representing one of humanity's deepest ancestral genetic lineages, renowned for extraordinary rock art across the Drakensberg and Kalahari.",
    summary_fi: "Eteläisen Afrikan alkuperäiskansat, jotka puhuvat maiskautusäänteitä sisältäviä kieliä ja edustavat ihmiskunnan vanhimpia geneettisiä linjoja, tunnettuina Drakensbergin ja Kalaharin kalliomaalauksista.",
    capital: "Kalahari / Karoo",
    feature_name_matches: ["Khoisan"]
  },
  {
    slug: "kingdom-of-zimbabwe",
    name: "Kingdom of Zimbabwe",
    name_fi: "Zimbabwen kuningaskunta",
    native_name: "Dzimba-dza-mabwe",
    alternate_names: ["Great Zimbabwe"],
    culture_group: "Southern Africa",
    lineage_id: "zimbabwe",
    historical_period: "Medieval Southern Africa",
    year_start: 1220,
    year_end: 1450,
    period_label: "1220 CE – 1450 CE",
    period_label_fi: "1220 jaa. – 1450 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Zimbabwe",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Suur-Zimbabwe",
    wikidata_id: "Q614838",
    summary_en: "Medieval Shona kingdom centered at the UNESCO World Heritage drystone citadel of Great Zimbabwe, dominating Indian Ocean gold and ivory trade routes connecting to Kilwa and Sofala.",
    summary_fi: "Shonakansan keskiaikainen kuningaskunta, jonka massiiviset laastittomat kivilinnat Suur-Zimbabwessa hallitsivat Intian valtameren kulta- ja norsunluukauppaa Sofalan sataman kautta.",
    capital: "Great Zimbabwe",
    feature_name_matches: ["Great Zimbabwe"]
  },
  {
    slug: "kingdom-of-mutapa",
    name: "Kingdom of Mutapa",
    name_fi: "Mutapan kuningaskunta (Mwenemutapa)",
    native_name: "Mwenemutapa",
    alternate_names: ["Mwenemutapa", "Monomotapa", "Mutapa Empire"],
    culture_group: "Southern Africa",
    lineage_id: "zimbabwe",
    historical_period: "Late Medieval to Early Modern Southern Africa",
    year_start: 1430,
    year_end: 1760,
    period_label: "1430 CE – 1760 CE",
    period_label_fi: "1430 jaa. – 1760 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Mutapa",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Monamotapa",
    wikidata_id: "Q849405",
    summary_en: "Successor empire to Great Zimbabwe founded by Nyatsimba Mutota, spanning the Zambezi and Limpopo river valleys and controlling rich alluvial goldfields contested by Portuguese traders.",
    summary_fi: "Suur-Zimbabwen seuraajavaltio Sambesi- ja Limpopojokien laaksoissa, jota hallitsi Mwenemutapa ja joka valvoi Afrikan sisämaan rikkaita kultakaivoksia.",
    capital: "Zvongombe",
    feature_name_matches: ["Mwenemutapa"]
  },
  {
    slug: "rozvi-empire",
    name: "Rozvi Empire",
    name_fi: "Rozvin valtakunta",
    native_name: "Rozvi",
    alternate_names: ["Rozwi", "Butua", "Torwa Dynasty"],
    culture_group: "Southern Africa",
    lineage_id: "zimbabwe",
    historical_period: "Early Modern Southern Africa",
    year_start: 1684,
    year_end: 1889,
    period_label: "1684 CE – 1889 CE",
    period_label_fi: "1684 jaa. – 1889 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Rozvi_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Rozvi-valtio",
    wikidata_id: "Q2171221",
    summary_en: "Shona warrior state founded by Changamire Dombo that expelled the Portuguese from the Zimbabwean plateau and built the chevron-patterned stone palace ruins at Danamombe and Khami.",
    summary_fi: "Shonasoturien valtio, jonka johtaja Changamire Dombo karkotti portugalilaiset Zimbabwen ylängöltä ja joka rakensi Khamin ja Danamomben upeat kivipalatsit.",
    capital: "Danamombe, Khami",
    feature_name_matches: ["Rozwi"]
  },
  {
    slug: "zulu-kingdom",
    name: "Zulu Kingdom",
    name_fi: "Zulujen kuningaskunta",
    native_name: "KwaZulu",
    alternate_names: ["Zulu", "Zululand", "Zulu Empire"],
    culture_group: "Southern Africa",
    lineage_id: "south-africa",
    historical_period: "19th Century Southern Africa",
    year_start: 1816,
    year_end: 1897,
    period_label: "1816 CE – 1897 CE",
    period_label_fi: "1816 jaa. – 1897 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Zulu_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Zulumaa",
    wikidata_id: "Q649660",
    summary_en: "Militarized monarchy forged by Shaka Zulu using innovative 'buffalo horns' tactical formations and iklwa thrusting spears, famously routing British imperial troops at the Battle of Isandlwana in 1879.",
    summary_fi: "Kuningas Shakan perustama kurinalainen zulujen sotilasvaltio, joka kehitti puhvelinsarvitaktiikan ja saavutti historiallisen voiton brittiarmeijasta Isandlwanan taistelussa vuonna 1879.",
    capital: "kwaBulawayo, Ulundi",
    feature_name_matches: ["Zulu", "Zululand"]
  },
  {
    slug: "xhosa-kingdom",
    name: "Xhosa Kingdom",
    name_fi: "Xhosien kuningaskunta",
    native_name: "kwaXhosa",
    alternate_names: ["Xhosa", "Gcaleka", "Rharhabe"],
    culture_group: "Southern Africa",
    lineage_id: "south-africa",
    historical_period: "Precolonial to 19th Century Eastern Cape",
    year_start: 1500,
    year_end: 1879,
    period_label: "1500 CE – 1879 CE",
    period_label_fi: "1500 jaa. – 1879 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Xhosa_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Xhosat",
    wikidata_id: "Q8044738",
    summary_en: "Nguni-speaking monarchies of the Eastern Cape who fought nine ferocious Frontier Wars over a century (1779–1879) against Dutch and British encroachment, producing Nelson Mandela.",
    summary_fi: "Etelä-Afrikan Itä-Kapin ngunikansan kuningaskunnat, jotka kävivät vuosisadan kestäneet yhdeksän rajasotaa eurooppalaisia siirtolaisia vastaan ja joista polveutui Nelson Mandela.",
    capital: "Great Fish River / Eastern Cape",
    feature_name_matches: ["Xhosa"]
  },
  {
    slug: "republic-of-south-africa",
    name: "Republic of South Africa",
    name_fi: "Etelä-Afrikan tasavalta",
    native_name: "South Africa / Suid-Afrika",
    alternate_names: ["South Africa", "Union of South Africa"],
    culture_group: "Southern Africa",
    lineage_id: "south-africa",
    historical_period: "Colonial to Modern Rainbow Nation",
    year_start: 1910,
    year_end: 2026,
    period_label: "1910 CE – Present",
    period_label_fi: "1910 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/South_Africa",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Etel%C3%A4-Afrikka",
    wikidata_id: "Q258",
    summary_en: "Industrialized multi-ethnic nation at the southern tip of Africa, transitioning from racial apartheid to a constitutional democracy in 1994 under Nobel laureate Nelson Mandela.",
    summary_fi: "Afrikan eteläkärjen monietninen teollisuusmaa, joka siirtyi apartheid-rotuerottelujärjestelmästä perustuslailliseen monipuoluedemokratiaan vuonna 1994 Nelson Mandelan johdolla.",
    capital: "Pretoria, Cape Town, Bloemfontein",
    feature_name_matches: ["South Africa"]
  },
  {
    slug: "kingdom-of-lesotho",
    name: "Kingdom of Lesotho",
    name_fi: "Lesothon kuningaskunta",
    native_name: "Muso oa Lesotho",
    alternate_names: ["Basutoland", "Lesotho"],
    culture_group: "Southern Africa",
    lineage_id: "lesotho",
    historical_period: "19th Century to Modern Mountain Realm",
    year_start: 1822,
    year_end: 2026,
    period_label: "1822 CE – Present",
    period_label_fi: "1822 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Lesotho",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Lesotho",
    wikidata_id: "Q1013",
    summary_en: "High-altitude mountain enclave nation surrounded entirely by South Africa, consolidated by King Moshoeshoe I on the Thaba Bosiu plateau to safeguard Basotho autonomy.",
    summary_fi: "Etelä-Afrikan ympäröimä vuoristokuningaskunta, jonka kuningas Moshoeshoe I perusti Thaba Bosiun vuorilinnoitukselta käsin turvatakseen basothokansan itsemääräämisoikeuden.",
    capital: "Maseru",
    feature_name_matches: ["Basutoland", "Lesotho"]
  },
  {
    slug: "kingdom-of-eswatini",
    name: "Kingdom of Eswatini (Swaziland)",
    name_fi: "Eswatinin kuningaskunta (Swazimaa)",
    native_name: "Umbuso weSwatini",
    alternate_names: ["Swaziland", "Eswatini"],
    culture_group: "Southern Africa",
    lineage_id: "eswatini",
    historical_period: "Precolonial to Modern Monarchy",
    year_start: 1745,
    year_end: 2026,
    period_label: "1745 CE – Present",
    period_label_fi: "1745 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Eswatini",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Eswatini",
    wikidata_id: "Q1050",
    summary_en: "Traditional Nguni kingdom unified by King Sobhuza I and Mswati II, preserving the dual monarchy of the Ngwenyama (King) and Ndlovukati (Queen Mother) and sacred Umhlanga ceremonies.",
    summary_fi: "Perinteinen swazien kuningaskunta, jota hallitsevat yhdessä kuningas (Ngwenyama) ja kuningasäiti (Ndlovukati) ja jossa vaalitaan perinteisiä Umhlanga-rituaaleja.",
    capital: "Mbabane, Lobamba",
    feature_name_matches: ["Swaziland"]
  },
  {
    slug: "republic-of-botswana",
    name: "Republic of Botswana",
    name_fi: "Botswanan tasavalta",
    native_name: "Lefatshe la Botswana",
    alternate_names: ["Botswana", "Bechuanaland"],
    culture_group: "Southern Africa",
    lineage_id: "botswana",
    historical_period: "Colonial to Modern Kalahari Democracy",
    year_start: 1885,
    year_end: 2026,
    period_label: "1885 CE – Present",
    period_label_fi: "1885 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Botswana",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Botswana",
    wikidata_id: "Q963",
    summary_en: "Stable multi-party democracy in the Kalahari Basin, famous for the Okavango Delta, diamond stewardship, and continuous governance under Batswana customary law (kgotla).",
    summary_fi: "Kalaharin altaassa sijaitseva vakaa demokratia, joka tunnetaan Okavangon suistoalueesta, timanttitaloudestaan ja perinteisestä kgotla-kyläkokousjärjestelmästään.",
    capital: "Gaborone",
    feature_name_matches: ["Botswana"]
  },
  {
    slug: "republic-of-namibia",
    name: "Republic of Namibia",
    name_fi: "Namibian tasavalta",
    native_name: "Namibia",
    alternate_names: ["Namibia", "German South West Africa"],
    culture_group: "Southern Africa",
    lineage_id: "namibia",
    historical_period: "Colonial to Modern Coastal Desert",
    year_start: 1884,
    year_end: 2026,
    period_label: "1884 CE – Present",
    period_label_fi: "1884 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Namibia",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Namibia",
    wikidata_id: "Q1030",
    summary_en: "Vast Atlantic desert nation containing the Namib Desert and Fish River Canyon, winning independence in 1990 under SWAPO after German colonial and South African mandate rule.",
    summary_fi: "Lounais-Afrikan laaja aavikkovaltio, joka saavutti itsenäisyytensä vuonna 1990 SWAPO:n vapaustaistelun jälkeen oltuaan Saksan ja Etelä-Afrikan hallinnassa.",
    capital: "Windhoek",
    feature_name_matches: ["Namibia"]
  },
  {
    slug: "republic-of-angola",
    name: "Republic of Angola",
    name_fi: "Angolan tasavalta",
    native_name: "Angola",
    alternate_names: ["Angola", "Angola (Portugal)", "Portuguese West Africa"],
    culture_group: "Southern Africa",
    lineage_id: "angola",
    historical_period: "Colonial to Modern Southwest Africa",
    year_start: 1575,
    year_end: 2026,
    period_label: "1575 CE – Present",
    period_label_fi: "1575 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Angola",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Angola",
    wikidata_id: "Q916",
    summary_en: "Resource-rich South Atlantic nation colonized by Portugal for four centuries, achieving independence in 1975 under Agostinho Neto's MPLA, rich in oil, diamonds, and Kizomba music.",
    summary_fi: "Luonnonvaroiltaan rikas Lounais-Afrikan valtio, joka oli Portugalin siirtomaana neljän vuosisadan ajan ja itsenäistyi vuonna 1975 Agostinho Neton johdolla.",
    capital: "Luanda",
    feature_name_matches: ["Angola", "Angola (Portugal)"]
  },
  {
    slug: "republic-of-mozambique",
    name: "Republic of Mozambique",
    name_fi: "Mosambikin tasavalta",
    native_name: "Moçambique",
    alternate_names: ["Mozambique", "Mozambique (Portugal)", "Portuguese East Africa"],
    culture_group: "Southern Africa",
    lineage_id: "mozambique",
    historical_period: "Colonial to Modern Southeast Africa",
    year_start: 1505,
    year_end: 2026,
    period_label: "1505 CE – Present",
    period_label_fi: "1505 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Mozambique",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Mosambik",
    wikidata_id: "Q1029",
    summary_en: "Indian Ocean coastal nation with historic Swahili-Portuguese trading fortresses on the Island of Mozambique, achieving independence in 1975 under Samora Machel's FRELIMO.",
    summary_fi: "Intian valtameren rannikkovaltio, jonka Mosambikin saari toimi vuosisatoja Portugalin Itä-Afrikan kauppakeskuksena ja joka itsenäistyi FRELIMO:n johdolla 1975.",
    capital: "Maputo (Lourenço Marques)",
    feature_name_matches: ["Mozambique", "Mozambique (Portugal)"]
  },
  {
    slug: "republic-of-zambia",
    name: "Republic of Zambia",
    name_fi: "Sambian tasavalta",
    native_name: "Zambia",
    alternate_names: ["Zambia", "Northern Rhodesia"],
    culture_group: "Southern Africa",
    lineage_id: "zambia",
    historical_period: "Colonial to Modern Central-Southern Africa",
    year_start: 1911,
    year_end: 2026,
    period_label: "1911 CE – Present",
    period_label_fi: "1911 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Zambia",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sambia",
    wikidata_id: "Q953",
    summary_en: "Landlocked nation straddling the Zambezi River and Victoria Falls (Mosi-oa-Tunya), formerly Northern Rhodesia, achieving independence in 1964 under Kenneth Kaunda.",
    summary_fi: "Sambesi-joen ja Victorian putousten äärellä sijaitseva sisämaavaltio, entinen Pohjois-Rhodesia, joka saavutti itsenäisyytensä vuonna 1964 Kenneth Kaundan johdolla.",
    capital: "Lusaka",
    feature_name_matches: ["Zambia", "Northern Rhodesia"]
  },
  {
    slug: "republic-of-zimbabwe",
    name: "Republic of Zimbabwe",
    name_fi: "Zimbabwen tasavalta",
    native_name: "Zimbabwe",
    alternate_names: ["Zimbabwe", "Rhodesia", "Southern Rhodesia"],
    culture_group: "Southern Africa",
    lineage_id: "zimbabwe",
    historical_period: "Colonial to Modern Southern Africa",
    year_start: 1890,
    year_end: 2026,
    period_label: "1890 CE – Present",
    period_label_fi: "1890 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Zimbabwe",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Zimbabwe",
    wikidata_id: "Q954",
    summary_en: "Plateau nation between the Zambezi and Limpopo rivers, colonized as Southern Rhodesia by Cecil Rhodes's company, winning recognized independence as Zimbabwe in 1980.",
    summary_fi: "Sambesi- ja Limpopojokien välisellä ylängöllä sijaitseva valtio, entinen Etelä-Rhodesia, joka saavutti kansainvälisesti tunnustetun itsenäisyyden Zimbabwena vuonna 1980.",
    capital: "Harare (Salisbury)",
    feature_name_matches: ["Zimbabwe", "Rhodesia"]
  },
  {
    slug: "republic-of-malawi",
    name: "Republic of Malawi",
    name_fi: "Malawin tasavalta",
    native_name: "Dziko la Malaŵi",
    alternate_names: ["Malawi", "Nyasaland"],
    culture_group: "Southern Africa",
    lineage_id: "malawi",
    historical_period: "Colonial to Modern Lake Malawi Realm",
    year_start: 1891,
    year_end: 2026,
    period_label: "1891 CE – Present",
    period_label_fi: "1891 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Malawi",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Malawi",
    wikidata_id: "Q1020",
    summary_en: "Elongated southeastern African nation centered on Lake Malawi (Lake Nyasa), formerly the British protectorate of Nyasaland, known as the 'Warm Heart of Africa'.",
    summary_fi: "Malawijärven (Njassajärven) rannoille levittäytyvä Kaakkois-Afrikan sisämaavaltio, entinen brittiläinen Njassamaa, joka tunnetaan lempinimellä Afrikan lämmin sydän.",
    capital: "Lilongwe, Zomba",
    feature_name_matches: ["Malawi", "Nyasaland"]
  },
  {
    slug: "gitxsan-first-nation",
    name: "Gitxsan Lax̱yip",
    name_fi: "Gitxsan-kansa",
    native_name: "Gitx̱san Lax̱yip",
    alternate_names: ["Gitx̱san Lax̱yip", "Gitxsan"],
    culture_group: "Southern Africa",
    lineage_id: "north-america",
    historical_period: "Pacific Northwest Indigenous Traditions",
    year_start: -5000,
    year_end: 2026,
    period_label: "5000 BCE – Present",
    period_label_fi: "5000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gitxsan",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Luoteisrannikon_intiaanit",
    wikidata_id: "Q1528876",
    summary_en: "Indigenous First Nation of the Skeena River watershed in northwestern British Columbia, celebrated for totem poles, matrilineal Wilp house groups, and the landmark Delgamuukw land rights legal case.",
    summary_fi: "Kanadan Brittiläisen Kolumbian Skeenajoen vesistön alkuperäiskansa, joka tunnetaan mahtavista toteemipaaluistaan ja historiallisesta Delgamuukw-maaoikeudenkäynnistä.",
    capital: "Hazelton / Skeena River",
    feature_name_matches: ["Gitx̱san Lax̱yip"]
  },
  {
    slug: "san-carlos-apache-nation",
    name: "San Carlos Apache Tribe",
    name_fi: "San Carlosin apatšit",
    alternate_names: ["San Carlos Apache"],
    culture_group: "Southern Africa",
    lineage_id: "north-america",
    historical_period: "Southwest Native American Traditions",
    year_start: 1200,
    year_end: 2026,
    period_label: "1200 CE – Present",
    period_label_fi: "1200 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/San_Carlos_Apache_Tribe",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Apat%C5%A1it",
    wikidata_id: "Q3351980",
    summary_en: "Federally recognized Western Apache sovereign nation in eastern Arizona, preserving matrilineal clan heritage, holy Crown Dance rituals, and sacred sites at Oak Flat (Chi'chil Biłdagoteel).",
    summary_fi: "Arizonan itäosissa asuva liittovaltion tunnustama läntisten apatšien heimo, joka vaalii perinteisiä klaanirakenteitaan ja pyhiä kruunutanssiseremonioitaan.",
    capital: "San Carlos, Arizona",
    feature_name_matches: ["San Carlos Apache"]
  },
  {
    slug: "sanpoil-people",
    name: "Sanpoil Indigenous People",
    name_fi: "Sanpoil-kansa",
    alternate_names: ["San Poil", "Nesilextcl'n"],
    culture_group: "Southern Africa",
    lineage_id: "north-america",
    historical_period: "Columbia Plateau Indigenous Traditions",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sanpoil_(tribe)",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Tasankointiaanit",
    wikidata_id: "Q3472856",
    summary_en: "Interior Salish-speaking indigenous people of the Columbia River and Sanpoil River valleys in Washington State, historically pacifist and renowned for communal salmon trapping at Kettle Falls.",
    summary_fi: "Washingtonin osavaltion Columbian jokialueen sisämaasalish-kielinen alkuperäiskansa, joka tunnettiin rauhanomaisuudestaan ja lohenkalastuksestaan.",
    capital: "Columbia River / Washington",
    feature_name_matches: ["San Poil"]
  }
]

const outPath = path.resolve(__dirname, "../data-sources/batches/southern-africa.json")
fs.writeFileSync(outPath, JSON.stringify(SOUTHERN_AFRICA_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${SOUTHERN_AFRICA_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(SOUTHERN_AFRICA_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
