import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "./seed_culture_metadata_batch"

const OCEANIA_CULTURES: CultureBatchEntry[] = [
  // 1. Australian Aboriginal Hunter-Gatherers & Pan-Aboriginal Horizons
  {
    slug: "australian-aboriginal-hunter-gatherers",
    name: "Australian Aboriginal Hunter-Gatherers",
    name_fi: "Australian aboriginaalit metsästäjä-keräilijät",
    native_name: "Indigenous Australians / First Nations of Australia",
    alternate_names: ["Australian aboriginal hunter-gatherers", "Aboriginal tribes"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Ancient to Continuous Indigenous Australian Horizon",
    year_start: -65000,
    year_end: 2026,
    period_label: "65,000 BCE – Present",
    period_label_fi: "65 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Indigenous_Australians",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Australian_aboriginaalit",
    wikidata_id: "Q132155",
    summary_en: "One of the oldest continuous cultural traditions on Earth, Indigenous Australians developed sophisticated land management fire-stick practices, songlines, complex kinship systems, and Dreamtime mythologies across the continent.",
    summary_fi: "Yksi maapallon vanhimmista yhtäjaksoisista kulttuureista; Australian aboriginaalit kehittivät kehittyneen maankäytön kuloitusmenetelmineen, uniaikamytologian ja laululinjoihin perustuvan maantieteellisen perinteen.",
    capital: "Various tribal estates across Sahul and Australia",
    feature_name_matches: ["Australian aboriginal hunter-gatherers", "Aboriginal tribes"]
  },
  {
    slug: "tasmanian-aborigines",
    name: "Tasmanian Aborigines (Palawa)",
    name_fi: "Tasmanian aboriginaalit (Palawa)",
    native_name: "Palawa / Lutruwita",
    alternate_names: ["Aboriginal Tasmanians", "Tasmanian hunter-gatherers", "Palawa"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Indigenous Tasmanian Horizon",
    year_start: -40000,
    year_end: 2026,
    period_label: "40,000 BCE – Present",
    period_label_fi: "40 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Aboriginal_Tasmanians",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Tasmanialaiset",
    wikidata_id: "Q749455",
    summary_en: "Indigenous people of Lutruwita (Tasmania) isolated from mainland Australia after the flooding of the Bass Strait roughly 12,000 years ago, who preserved unique adapted maritime and stone tool technologies despite colonial devastation in the Black War.",
    summary_fi: "Lutruwitan (Tasmanian) alkuperäisasukkaat, jotka eristyivät mantereesta Bassinsalmen tulvimisen myötä noin 12 000 vuotta sitten ja säilyttivät ainutlaatuisen rannikko- ja kivikautisen elämäntavan siirtomaasotien vainoista huolimatta.",
    capital: "Lutruwita (Tasmania)",
    feature_name_matches: ["Aboriginal Tasmanians", "Tasmanian hunter-gatherers"]
  },
  {
    slug: "arrernte-nation",
    name: "Arrernte People",
    name_fi: "Arrernte-kansa",
    native_name: "Arrernte / Aranda",
    alternate_names: ["Arrernte", "Aranda"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Central Australian Indigenous Society",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Arrernte_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Arrernte",
    wikidata_id: "Q2605809",
    summary_en: "Aboriginal Australian people of the Central Desert region surrounding Mparntwe (Alice Springs), famed for their intricate Dreamtime totemic landscape traditions, rich kinship organization, and preservation of the Arrernte language.",
    summary_fi: "Keski-Australian aavikkoalueen ja Mparntwen (Alice Springs) alkuperäiskansa, joka tunnetaan uniajan toteemisista maisemaperinteistään, rikkaasta sukulaisuusjärjestelmästään ja arrernten kielen vaalimisesta.",
    capital: "Mparntwe (Alice Springs)",
    feature_name_matches: ["Arrernte"]
  },
  {
    slug: "eora-nation",
    name: "Eora Nation",
    name_fi: "Eora-kansa",
    native_name: "Eora",
    alternate_names: ["Eora"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Sydney Basin Coastal Indigenous Nation",
    year_start: -20000,
    year_end: 2026,
    period_label: "20,000 BCE – Present",
    period_label_fi: "20 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Eora",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Eora",
    wikidata_id: "Q1346369",
    summary_en: "Aboriginal Australian clan custodians of coastal Sydney Harbour and Botany Bay, whose prominent resistance leader Pemulwuy led the multi-clan frontier war against British colonial expansion in the late 18th century.",
    summary_fi: "Sydneyn sataman ja Botany Bayn rannikon perinteiset aboriginaalinomistajat, joiden johtaja Pemulwuy johti maineikasta vastarintasotaa brittien siirtokuntaa vastaan 1700-luvun lopulla.",
    capital: "Warrane (Sydney Cove)",
    feature_name_matches: ["Eora"]
  },
  {
    slug: "ngunawal-people",
    name: "Ngunnawal People",
    name_fi: "Ngunnawal-kansa",
    native_name: "Ngunnawal / Ngunawal",
    alternate_names: ["Ngunawal", "Ngunnawal"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Highland Indigenous Nation",
    year_start: -25000,
    year_end: 2026,
    period_label: "25,000 BCE – Present",
    period_label_fi: "25 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Ngunnawal",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ngunnawalit",
    wikidata_id: "Q7022718",
    summary_en: "Traditional Indigenous owners of the Southern Tablelands and modern Australian Capital Territory surrounding Canberra, known for ancestral gatherings to harvest bogong moths in the Brindabella Ranges.",
    summary_fi: "Eteläisten ylänköjen ja Canberran pääkaupunkialueen perinteiset aboriginaalialueen omistajat, jotka kokoontuivat ikimuistoisesti Brindabella-vuorille bogong-yökkösten vuosittaiseen pyyntiin.",
    capital: "Canberra / Yass Valley",
    feature_name_matches: ["Ngunawal"]
  },
  {
    slug: "muruwari-people",
    name: "Muruwari People",
    name_fi: "Muruwari-kansa",
    native_name: "Muruwari / Muruwurri",
    alternate_names: ["Muruwari"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Culgoa-Barwon River Indigenous Nation",
    year_start: -20000,
    year_end: 2026,
    period_label: "20,000 BCE – Present",
    period_label_fi: "20 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Muruwari_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Muruwari",
    wikidata_id: "Q6939626",
    summary_en: "Aboriginal Australian nation inhabiting the border territory between northern New South Wales and southern Queensland along the Culgoa and Barwon river systems, declaring symbolic continuous sovereignty.",
    summary_fi: "Uuden Etelä-Walesin pohjoisosan ja Queenslandin rajaseudulla Culgoa- ja Barwon-jokien varrella elävä aboriginaalikansa, joka on julistanut katkeamattoman symbolisen suvereniteettinsa.",
    capital: "Brewarrina / Barringun",
    feature_name_matches: ["Muruwari"]
  },
  {
    slug: "bibbulman-nation",
    name: "Bibbulman (Noongar) People",
    name_fi: "Bibbulman-kansa (Noongar)",
    native_name: "Bibbulman / Noongar",
    alternate_names: ["Bibbulman", "Bibbulmun"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Southwest Australian Indigenous Nation",
    year_start: -45000,
    year_end: 2026,
    period_label: "45,000 BCE – Present",
    period_label_fi: "45 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Noongar",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Noongar",
    wikidata_id: "Q1371587",
    summary_en: "Prominent dialect group of the Noongar nation in southwest Western Australia, holding deep ancestral connections across coastal wetlands, karri forests, and maritime estuaries.",
    summary_fi: "Länsi-Australian lounaisosan Noongar-kansakunnan merkittävä heimo- ja murreryhmä, jolla on syvä perinteinen side rannikon kosteikkoihin, eukalyptusmetsiin ja jokisuistoihin.",
    capital: "Southwest Western Australia",
    feature_name_matches: ["Bibbulman"]
  },
  {
    slug: "goreng-people",
    name: "Goreng (Koreng) People",
    name_fi: "Goreng-kansa",
    native_name: "Goreng / Koreng",
    alternate_names: ["Goreng", "Koreng"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Great Southern Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Koreng",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Koreng",
    wikidata_id: "Q6431940",
    summary_en: "Noongar subgroup inhabiting the inland Great Southern region of Western Australia around Katanning and Gnowangerup, sustaining unique six-season cyclical ecological knowledge.",
    summary_fi: "Noongar-kansakuntaan kuuluva heimo Länsi-Australian Great Southern -sisämaassa Katanningin ja Gnowangerupin alueella, joka ylläpitää perinteistä kuuden vuodenajan ekologista kalenteria.",
    capital: "Katanning / Gnowangerup",
    feature_name_matches: ["Goreng"]
  },
  {
    slug: "kaniyang-people",
    name: "Kaniyang People",
    name_fi: "Kaniyang-kansa",
    native_name: "Kaniyang / Kaneang",
    alternate_names: ["Kaniyang"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Southwest Forest Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kaneang",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kaneang",
    wikidata_id: "Q6361817",
    summary_en: "Noongar dialect group dwelling in the jarrah and marri forest belt of southwestern Australia around Collie, Donnybrook, and Bridgetown.",
    summary_fi: "Noongar-kansaan kuuluva heimo Länsi-Australian lounaisissa metsissä Collien, Donnybrookin ja Bridgetownin alueella.",
    capital: "Bridgetown / Collie River basin",
    feature_name_matches: ["Kaniyang"]
  },
  {
    slug: "pinjarup-people",
    name: "Pinjarup People",
    name_fi: "Pinjarup-kansa",
    native_name: "Pinjarup / Bindjareb",
    alternate_names: ["Pinjarup", "Bindjareb"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Murray River Coastal Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Pinjarup",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pinjarup",
    wikidata_id: "Q7195861",
    summary_en: "Bindjareb Noongar people of the Murray River and Peel-Harvey estuary south of Perth, who fiercely defended their waterway estates during the 1834 Pinjarra conflict.",
    summary_fi: "Perthin eteläpuolella Murray-joen ja Peel-Harveyn suistoalueella asuva Bindjareb Noongar -heimo, joka puolusti aluettaan vuoden 1834 Pinjarran taistelussa.",
    capital: "Pinjarra / Mandurah",
    feature_name_matches: ["Pinjarup"]
  },
  {
    slug: "badimaya-people",
    name: "Badimaya People",
    name_fi: "Badimaya-kansa",
    native_name: "Badimaya / Badimia",
    alternate_names: ["Badimaya"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Midwest Pastoral Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Badimaya_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Badimaya",
    wikidata_id: "Q4841029",
    summary_en: "Aboriginal nation of the Mid West and Murchison regions of Western Australia, speaking an endangered Kartu language with rich rock art sites around Lake Moore.",
    summary_fi: "Länsi-Australian Mid Westin ja Murchisonin alueiden aboriginaalikansa, joka puhuu uhanalaista kartu-kieltä ja tunnetaan Lake Mooren kalliomaalauksistaan.",
    capital: "Mount Magnet / Paynes Find",
    feature_name_matches: ["Badimaya"]
  },
  {
    slug: "banjima-people",
    name: "Banjima People",
    name_fi: "Banjima-kansa",
    native_name: "Banjima / Panyjima",
    alternate_names: ["Banjima", "Panyjima"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Pilbara Hamersley Indigenous Nation",
    year_start: -40000,
    year_end: 2026,
    period_label: "40,000 BCE – Present",
    period_label_fi: "40 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Banjima",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Banjima",
    wikidata_id: "Q4856003",
    summary_en: "Traditional Aboriginal owners of the Central Pilbara and Hamersley Range, including Karijini National Park, holding deep spiritual and songline connections across deep gorges.",
    summary_fi: "Keski-Pilbaran ja Hamersley-vuoriston perinteiset omistajat Karijinin rotkoalueella Länsi-Australiassa, joilla on ikiaikaiset laululinjayhteydet jylhiin kanjoneihin.",
    capital: "Hamersley Range / Karijini",
    feature_name_matches: ["Banjima"]
  },
  {
    slug: "bardi-people",
    name: "Bardi People",
    name_fi: "Bardi-kansa",
    native_name: "Bardi / Baada",
    alternate_names: ["Bardi"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Dampier Peninsula Saltwater Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Bardi_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bardi",
    wikidata_id: "Q4860098",
    summary_en: "Maritime saltwater Aboriginal people of the northern Dampier Peninsula in the West Kimberley, renowned for open-ocean raft navigation, pearl-shell crafting, and tidal knowledge.",
    summary_fi: "Länsi-Kimberleyn Dampierin niemimaan pohjoiskärjessä elävä merellinen aboriginaalikansa, joka tunnetaan avomerilauttailustaan, helminsimpukkatöistään ja vuorovesiosaamisestaan.",
    capital: "Ardyaloon (One Arm Point) / Cape Leveque",
    feature_name_matches: ["Bardi"]
  },
  {
    slug: "jabirrjabirr-people",
    name: "Jabirrjabirr People",
    name_fi: "Jabirrjabirr-kansa",
    native_name: "Jabirrjabirr / Dyaberdyaber",
    alternate_names: ["Jabirrjabirr"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Kimberley Coastal Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Jabirr_Jabirr",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Jabirr_Jabirr",
    wikidata_id: "Q6110271",
    summary_en: "Saltwater Indigenous group of the western Dampier Peninsula coast south of Beagle Bay, with strong linguistic and ceremonial ties to the Nyulnyulan cultural group.",
    summary_fi: "Länsi-Kimberleyn Dampierin niemimaalla Beagle Bayn eteläpuolella asuva merellinen aboriginaalikansa, joka kuuluu nyulnyulan-kieliryhmään.",
    capital: "Dampier Peninsula / Beagle Bay coast",
    feature_name_matches: ["Jabirrjabirr"]
  },
  {
    slug: "karajarri-people",
    name: "Karajarri People",
    name_fi: "Karajarri-kansa",
    native_name: "Karajarri / Karadjari",
    alternate_names: ["Karajarri"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "West Kimberley Coastal and Desert Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Karajarri",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Karajarri",
    wikidata_id: "Q6368551",
    summary_en: "Aboriginal group south of Broome whose lands bridge the Great Sandy Desert (Pirra) and the Eighty Mile Beach saltwater coast (Jurarr), governed by Pirra and Jurarr customary laws.",
    summary_fi: "Broomen eteläpuolella Isoa Hiekka-aavikkoa ja Eighty Mile Beachin rannikkoa asuttava aboriginaalikansa, jota ohjaavat Pirran ja Jurarrin ikiaikaiset lait.",
    capital: "Bidyadanga / Eighty Mile Beach",
    feature_name_matches: ["Karajarri"]
  },
  {
    slug: "gooniyandi-people",
    name: "Gooniyandi People",
    name_fi: "Gooniyandi-kansa",
    native_name: "Gooniyandi / Gunian",
    alternate_names: ["Gooniyandi"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Fitzroy River Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gooniyandi_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gooniyandi",
    wikidata_id: "Q5583709",
    summary_en: "Indigenous Australian people centered around the Fitzroy River crossing in Western Australia, known for active language maintenance and preservation of riverine song cycles.",
    summary_fi: "Fitzroy Crossingin aluetta Länsi-Australiassa asuttava aboriginaalikansa, joka tunnetaan kielensä elvytyksestä ja jokialueiden lauluperinteistä.",
    capital: "Fitzroy Crossing / Mimbi Caves",
    feature_name_matches: ["Gooniyandi"]
  },
  {
    slug: "jaru-people",
    name: "Jaru People",
    name_fi: "Jaru-kansa",
    native_name: "Jaru / Djaru",
    alternate_names: ["Jaru", "Djaru"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "East Kimberley Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Jaru_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Jaru_(kansa)",
    wikidata_id: "Q6161474",
    summary_en: "Aboriginal Australian people of the East Kimberley region around Halls Creek and the upper Ord and Sturt Creek rivers, who survived the Halls Creek gold rush frontier violence.",
    summary_fi: "Itä-Kimberleyn Halls Creekin sekä Ylä-Ordin ja Sturt Creekin aluetta asuttava aboriginaalikansa, joka selviytyi kultaryntäyksen väkivaltaisesta siirtomaakaudesta.",
    capital: "Halls Creek / Sturt Creek",
    feature_name_matches: ["Jaru"]
  },
  {
    slug: "gamberre-people",
    name: "Gamberre People",
    name_fi: "Gamberre-kansa",
    native_name: "Gamberre / Kambre",
    alternate_names: ["Gamberre"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "North Kimberley Coastal Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gamberre",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gamberre",
    wikidata_id: "Q5519665",
    summary_en: "Coastal Aboriginal nation inhabiting Admiralty Gulf and Napier Broome Bay in the northernmost Kimberley, renowned for sacred Gwion Gwion and Wandjina rock art traditions.",
    summary_fi: "Pohjois-Kimberleyn Admiralty Gulfin ja Napier Broome Bayn rannikon aboriginaalikansa, joka tunnetaan pyhistä Gwion Gwion- ja Wandjina-kalliomaalauksistaan.",
    capital: "Napier Broome Bay / Admiralty Gulf",
    feature_name_matches: ["Gamberre"]
  },
  {
    slug: "yiiji-people",
    name: "Yiiji People",
    name_fi: "Yiiji-kansa",
    native_name: "Yiiji / Yeidji",
    alternate_names: ["Yiiji", "Yeidji"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Cambridge Gulf Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Yeidji",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Yeidji",
    wikidata_id: "Q8051283",
    summary_en: "Aboriginal Australian group living around the Cambridge Gulf and Forrest River mission in the far north of the East Kimberley, maintaining strong cultural law.",
    summary_fi: "Itä-Kimberleyn pohjoisosassa Cambridge Gulfin ja Forrest-joen alueella asuva aboriginaalikansa, joka on ylläpitänyt perinteistä kulttuurilakiaan.",
    capital: "Oombulgurri / Forrest River",
    feature_name_matches: ["Yiiji"]
  },
  {
    slug: "gurindji-people",
    name: "Gurindji People",
    name_fi: "Gurindji-kansa",
    native_name: "Gurindji",
    alternate_names: ["Gurindji"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Victoria River Indigenous Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gurindji_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gurindji",
    wikidata_id: "Q3120970",
    summary_en: "Pioneering Aboriginal nation whose historic 1966 Wave Hill walk-off led by Vincent Lingiari sparked the modern Australian Indigenous land rights movement.",
    summary_fi: "Victoria-joen aluetta Pohjoisterritoriossa asuttava aboriginaalikansa, jonka vuoden 1966 Wave Hillin lakko Vincent Lingiarin johdolla käynnisti Australian maaoikeusliikkeen.",
    capital: "Kalkarindji / Daguragu",
    feature_name_matches: ["Gurindji"]
  },
  {
    slug: "jawoyn-people",
    name: "Jawoyn People",
    name_fi: "Jawoyn-kansa",
    native_name: "Jawoyn / Djauan",
    alternate_names: ["Jawoyn"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Katherine Gorge Indigenous Nation",
    year_start: -40000,
    year_end: 2026,
    period_label: "40,000 BCE – Present",
    period_label_fi: "40 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Jawoyn",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Jawoyn",
    wikidata_id: "Q6167909",
    summary_en: "Indigenous nation caring for Nitmiluk (Katherine Gorge) and western Arnhem Land escarpments, celebrated for their joint management of the Nitmiluk National Park.",
    summary_fi: "Nitmilukin (Katherine Gorge) rotkomaisemia ja Länsi-Arnheminmaata vaaliva aboriginaalikansa, joka hallinnoi Nitmilukin kansallispuistoa yhteishallintomallilla.",
    capital: "Katherine / Nitmiluk",
    feature_name_matches: ["Jawoyn"]
  },
  {
    slug: "gunwinggu-people",
    name: "Gunwinggu (Kunwinjku) People",
    name_fi: "Gunwinggu-kansa (Kunwinjku)",
    native_name: "Kunwinjku / Gunwinggu",
    alternate_names: ["Gunwinggu", "Kunwinjku"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "West Arnhem Land Rock and Bark Art Nation",
    year_start: -40000,
    year_end: 2026,
    period_label: "40,000 BCE – Present",
    period_label_fi: "40 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kunwinjku_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kunwinjku",
    wikidata_id: "Q3120977",
    summary_en: "Bininj people of Western Arnhem Land world-renowned for their dynamic rarrk cross-hatching bark painting, ochre rock galleries, and preservation of the Bininj Kunwok language.",
    summary_fi: "Länsi-Arnheminmaan aboriginaalikansa, joka on maailmankuulu rarrk-ristiviivoitustekniikalla tehdyistä tuohesta ja kalliosta koostuvista taideteoksistaan ja bininj kunwok -kielestään.",
    capital: "Gunbalanya (Oenpelli)",
    feature_name_matches: ["Gunwinggu"]
  },
  {
    slug: "gagudju-people",
    name: "Gagudju People",
    name_fi: "Gagudju-kansa",
    native_name: "Gagudju / Kakadu",
    alternate_names: ["Gagudju"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Kakadu Wetland Indigenous Nation",
    year_start: -40000,
    year_end: 2026,
    period_label: "40,000 BCE – Present",
    period_label_fi: "40 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gagudju",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gagudju",
    wikidata_id: "Q3120968",
    summary_en: "Traditional owners who gave their name to Kakadu National Park, celebrated for their stewardship of biodiverse billabongs, floodplain wetlands, and ancestral Nourlangie rock art.",
    summary_fi: "Kakadun kansallispuistolle nimensä antanut Pohjoisterritorion aboriginaalikansa, joka tunnetaan kosteikkojensa suojelusta ja Nourlangien muinaisista kalliotaiteista.",
    capital: "Jabiru / Kakadu Basin",
    feature_name_matches: ["Gagudju"]
  },
  {
    slug: "iwaidja-people",
    name: "Iwaidja People",
    name_fi: "Iwaidja-kansa",
    native_name: "Iwaidja / Yiwaydja",
    alternate_names: ["Iwaidja"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Cobourg Peninsula Maritime Nation",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Iwaidja",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Iwaidja",
    wikidata_id: "Q6098711",
    summary_en: "Coastal Aboriginal people of the Cobourg Peninsula and Croker Island who engaged in historic maritime trade and trepang harvesting with visiting Makassan sailors from Sulawesi.",
    summary_fi: "Cobourgin niemimaan ja Croker Islandin rannikon aboriginaalikansa, joka harjoitti vuosisatoja merikauppaa ja merimakkarapyyntiä Sulawesin makassarilaisten purjehtijoiden kanssa.",
    capital: "Minjilang (Croker Island) / Garig Gunak Barlu",
    feature_name_matches: ["Iwaidja"]
  },
  {
    slug: "arnhem-land-peoples",
    name: "Arnhem Land Indigenous Peoples",
    name_fi: "Arnheminmaan alkuperäiskansat",
    native_name: "Yolŋu & Bininj / Arnhem Land",
    alternate_names: ["Gunbalang", "Gungurugoni", "Gunibidji"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "North Australian Escarpment and Coastal Complex",
    year_start: -40000,
    year_end: 2026,
    period_label: "40,000 BCE – Present",
    period_label_fi: "40 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Arnhem_Land",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Arnheminmaa",
    wikidata_id: "Q216894",
    summary_en: "Encompassing the Gunbalang, Gungurugoni, and Gunibidji (Ndébbana) language groups of northern Arnhem Land who sustained resilient estuarine and woodland economies and complex ritual governance.",
    summary_fi: "Pohjois-Arnheminmaan Gunbalang-, Gungurugoni- ja Gunibidji-kieliryhmät, jotka ovat vaalineet jokisuistojen ja rannikkometsien taloutta sekä perinteistä seremoniallista hallintoa.",
    capital: "Maningrida / Liverpool River",
    feature_name_matches: ["Gunbalang", "Gungurugoni", "Gunibidji"]
  },
  {
    slug: "northern-territory-plains-peoples",
    name: "Victoria River & Barkly Peoples",
    name_fi: "Victoria-joen ja Barklyn kansat",
    native_name: "Jaminjung, Jingili & Karangpurru",
    alternate_names: ["Jaminjung", "Jingili", "Karangpurru"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Northern Territory Inland Nations",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Northern_Territory",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pohjoisterritorio",
    wikidata_id: "Q3237",
    summary_en: "Inland Indigenous groups encompassing the Jaminjung of the lower Victoria River, the Jingili of the Barkly Tableland, and the Karangpurru, preserving ancient trade routes and ritual songlines.",
    summary_fi: "Pohjoisterritorion sisämaan aboriginaalikansat, kuten Victoria-joen alajuoksun Jaminjung, Barklyn tasangon Jingili ja Karangpurru, jotka ylläpitivät muinaisia kauppa- ja laululinjoja.",
    capital: "Timber Creek / Elliott",
    feature_name_matches: ["Jaminjung", "Jingili", "Karangpurru"]
  },
  {
    slug: "pilbara-coastal-desert-peoples",
    name: "Pilbara Coastal & Desert Peoples",
    name_fi: "Pilbaran rannikko- ja aavikkokansat",
    native_name: "Jaburrara, Jiwarli, Jurruru, Kadjerong & Pinikura",
    alternate_names: ["Jaburrara", "Jiwarli", "Jurruru", "Kadjerong", "Pinikura"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Pilbara-Gascoyne Indigenous Complex",
    year_start: -35000,
    year_end: 2026,
    period_label: "35,000 BCE – Present",
    period_label_fi: "35 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Pilbara",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pilbara",
    wikidata_id: "Q1474813",
    summary_en: "Ancient custodians of the Pilbara, Burrup Peninsula rock engravings (Murujuga), and Ashburton watercourses, encompassing the Jaburrara, Jurruru, Pinikura, and Jiwarli nations.",
    summary_fi: "Pilbaran, Burrupin niemimaan (Murujugan) maailmankuulujen kalliokaiverrusten sekä Ashburtonin jokilaaksojen aboriginaalikansat, mukaan lukien Jaburrara, Jurruru, Pinikura ja Jiwarli.",
    capital: "Murujuga / Dampier Archipelago",
    feature_name_matches: ["Jaburrara", "Jiwarli", "Jurruru", "Kadjerong", "Pinikura"]
  },
  {
    slug: "goldfields-aboriginal-peoples",
    name: "Goldfields Aboriginal Peoples",
    name_fi: "Goldfieldsin aboriginaalikansat",
    native_name: "Kalaako, Malpa & Kalaamaya",
    alternate_names: ["Kalaako/Malpa", "Kalaamaya"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Western Australian Goldfields Indigenous Horizon",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Goldfields-Esperance",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/L%C3%A4nsi-Australia",
    wikidata_id: "Q1534884",
    summary_en: "Indigenous groups of the semiarid Western Australian Goldfields region around Kalgoorlie and Southern Cross, adapting with remarkable resourcefulness to eucalyptus woodlands and sandplains.",
    summary_fi: "Länsi-Australian Goldfieldsin alueen ja Kalgoorlien seudun aboriginaaliryhmät, jotka sopeutuivat taidokkaasti puolikuiviin eukalyptusmetsiin ja hiekkatasankoihin.",
    capital: "Kalgoorlie / Southern Cross",
    feature_name_matches: ["Kalaako/Malpa", "Kalaamaya"]
  },
  {
    slug: "queensland-indigenous-nations",
    name: "Queensland Indigenous Nations",
    name_fi: "Queenslandin alkuperäiskansat",
    native_name: "Gugu-Badhun & Mayi-Yapi",
    alternate_names: ["Gugu-Badhun", "Mayi-Yapi"],
    culture_group: "Oceania",
    lineage_id: "australia-indigenous",
    historical_period: "Inland Queensland Indigenous Horizon",
    year_start: -30000,
    year_end: 2026,
    period_label: "30,000 BCE – Present",
    period_label_fi: "30 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Queensland",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Queensland",
    wikidata_id: "Q36074",
    summary_en: "First Nations encompassing the Gugu-Badhun of the Upper Burdekin basalt plateau and the Mayi-Yapi of the Cloncurry region, holding deep knowledge of volcanic lava flows and dry riverbeds.",
    summary_fi: "Sisämaan Queenslandin alkuperäiskansat, kuten Burdekin-joen basalttitasangon Gugu-Badhun ja Cloncurryn seudun Mayi-Yapi, joilla on syvällinen tietämys tulivuori- ja jokimaisemista.",
    capital: "Upper Burdekin / Cloncurry",
    feature_name_matches: ["Gugu-Badhun", "Mayi-Yapi"]
  },
  {
    slug: "commonwealth-of-australia",
    name: "Commonwealth of Australia",
    name_fi: "Australian liittovaltio",
    native_name: "Commonwealth of Australia",
    alternate_names: ["Australia"],
    culture_group: "Oceania",
    lineage_id: "australia",
    historical_period: "Modern Oceanic Federation",
    year_start: 1901,
    year_end: 2026,
    period_label: "1901 CE – Present",
    period_label_fi: "1901 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Australia",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Australia",
    wikidata_id: "Q408",
    summary_en: "Federal constitutional democracy established on 1 January 1901 federating six British colonies across the continent, combining multicultural immigrant society with ancient Indigenous roots.",
    summary_fi: "Vuonna 1901 kuuden brittiläisen siirtokunnan liitosta syntynyt mannervaltio ja parlamentaarinen demokratia, joka yhdistää monikulttuurisen väestön mantereen ikivanhaan alkuperäisperintöön.",
    capital: "Canberra",
    feature_name_matches: ["Australia"]
  },

  // 2. New Zealand & Polynesian Explorers
  {
    slug: "maori-people",
    name: "Māori People (Aotearoa)",
    name_fi: "Māorit (Aotearoa)",
    native_name: "Māori / Tangata Whenua",
    alternate_names: ["Maori", "Māori", "Maoris", "M?ori"],
    culture_group: "Oceania",
    lineage_id: "maori",
    historical_period: "Polynesian Settlement of Aotearoa to Modern Era",
    year_start: 1250,
    year_end: 2026,
    period_label: "1250 CE – Present",
    period_label_fi: "1250 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/M%C4%81ori_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Maorit",
    wikidata_id: "Q6122",
    summary_en: "Indigenous Polynesian people of Aotearoa (New Zealand) who arrived in waka voyaging canoes around 1300 CE, establishing distinct iwi tribal polities, monumental carving, fortified pā, and the haka.",
    summary_fi: "Uuden-Seelannin (Aotearoan) polynesialainen alkuperäiskansa, joka asutti saaret purjehduskanootein noin 1300 ja loi omaleimaisen päällikkökuntien kulttuurin, pa-linnoitteet, veistotaiteen ja hakan.",
    capital: "Turangawaewae / Waitangi",
    feature_name_matches: ["Maori", "Māori", "Maoris", "M?ori"]
  },
  {
    slug: "new-zealand",
    name: "Dominion & State of New Zealand",
    name_fi: "Uusi-Seelanti",
    native_name: "New Zealand / Aotearoa",
    alternate_names: ["New Zealand", "Dominion of New Zealand"],
    culture_group: "Oceania",
    lineage_id: "new-zealand",
    historical_period: "Modern Pacific Constitutional Monarchy",
    year_start: 1840,
    year_end: 2026,
    period_label: "1840 CE – Present",
    period_label_fi: "1840 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/New_Zealand",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Uusi-Seelanti",
    wikidata_id: "Q664",
    summary_en: "Island nation in the southwestern Pacific Ocean founded constitutionally on the 1840 Treaty of Waitangi between the British Crown and Māori chiefs, noted for progressive democracy and environmental stewardship.",
    summary_fi: "Lounaisen Tyynenmeren saarivaltio, jonka perustana on vuoden 1840 Waitangin sopimus brittiläisen kruunun ja māoripäälliköiden välillä ja joka tunnetaan edistyksellisestä demokratiastaan.",
    capital: "Wellington",
    feature_name_matches: ["New Zealand"]
  },

  // 3. Polynesia, Pacific Kingdoms & Empires
  {
    slug: "polynesian-voyagers",
    name: "Polynesians (Pacific Voyagers)",
    name_fi: "Polynesialaiset",
    native_name: "Tangata Pasifika / Polynesian Peoples",
    alternate_names: ["Polynesians", "Polynesian"],
    culture_group: "Oceania",
    lineage_id: "polynesia",
    historical_period: "Great Pacific Oceanic Expansion",
    year_start: -1000,
    year_end: 2026,
    period_label: "1000 BCE – Present",
    period_label_fi: "1000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Polynesians",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Polynesialaiset",
    wikidata_id: "Q335359",
    summary_en: "Master navigators who settled the Polynesian Triangle (from Hawaii to New Zealand and Easter Island) across thousands of open oceanic miles using outrigger wa'a canoes, celestial wayfinding, and bird flight paths.",
    summary_fi: "Merenkulkijakansa, joka asutti valtavan polynesialaisen kolmion Havaijilta Uuteen-Seelantiin ja Pääsiäissaarelle kaksoisrunkoisilla kanooteilla suunnistaen tähtien, aallokoiden ja lintujen avulla.",
    capital: "Raiatea (Havai'i) / Taputapuātea",
    feature_name_matches: ["Polynesians"]
  },
  {
    slug: "tui-tonga-empire",
    name: "Tuʻi Tonga Empire",
    name_fi: "Tuʻi Tongan valtakunta",
    native_name: "Puleʻanga Tuʻi Tonga",
    alternate_names: ["Tuʻi Tonga Empire", "Tongan Empire"],
    culture_group: "Oceania",
    lineage_id: "tonga",
    historical_period: "Classical Oceanic Maritime Empire",
    year_start: 950,
    year_end: 1865,
    period_label: "950 CE – 1865 CE",
    period_label_fi: "950 jaa. – 1865 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Tu%CA%BBi_Tonga_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Tu%CA%BBi_Tongan_kuningaskunta",
    wikidata_id: "Q2630560",
    summary_en: "Powerful Oceanic maritime thalassocracy centered in Tongatapu that exercised tributary hegemony and trade dominance over Fiji, Samoa, Niue, and the Cook Islands with great kalia war canoes.",
    summary_fi: "Tongatapulla sijainnut voimakas merellinen talassokratia, joka ulotti verotusoikeutensa ja vaikutusvaltansa Fidžille, Samoalle ja Niuelle suurten kalia-sotakanoottien avulla.",
    capital: "Muʻa (Tongatapu)",
    feature_name_matches: ["Tuʻi Tonga Empire"]
  },
  {
    slug: "kingdom-of-tonga",
    name: "Kingdom of Tonga",
    name_fi: "Tongan kuningaskunta",
    native_name: "Puleʻanga Fakatuʻi ʻo Tonga",
    alternate_names: ["Tonga"],
    culture_group: "Oceania",
    lineage_id: "tonga",
    historical_period: "Constitutional Polynesian Monarchy",
    year_start: 1845,
    year_end: 2026,
    period_label: "1845 CE – Present",
    period_label_fi: "1845 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Tonga",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Tonga",
    wikidata_id: "Q678",
    summary_en: "Only Pacific island nation never to have lost its indigenous sovereignty to a foreign power, united in 1845 by King George Tupou I into a modern constitutional Christian monarchy.",
    summary_fi: "Tyynenmeren ainoa saarivaltio, joka säilytti itsenäisyytensä siirtomaavallan aikana ja jonka kuningas George Tupou I yhdisti perustuslailliseksi kristilliseksi monarkiaksi 1845.",
    capital: "Nukuʻalofa",
    feature_name_matches: ["Tonga"]
  },
  {
    slug: "hawaiian-kingdom",
    name: "Kingdom of Hawaii",
    name_fi: "Havaijin kuningaskunta",
    native_name: "Kō Hawaiʻi Paeʻāina",
    alternate_names: ["Kingdom of Hawaii", "Kō Hawaiʻi Paeʻāina (Hawaiian Kingdom)", "Hawaiian Kingdom"],
    culture_group: "Oceania",
    lineage_id: "hawaii",
    historical_period: "Sovereign Polynesian Kingdom",
    year_start: 1795,
    year_end: 1893,
    period_label: "1795 CE – 1893 CE",
    period_label_fi: "1795 jaa. – 1893 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Hawaiian_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Havaijin_kuningaskunta",
    wikidata_id: "Q2630713",
    summary_en: "Internationally recognized sovereign Polynesian state established by Kamehameha the Great uniting the Hawaiian islands, overthrown in 1893 in a coup orchestrated by American sugar planters.",
    summary_fi: "Kamehameha Suuren vuonna 1795 yhdistämä itsenäinen ja kansainvälisesti tunnustettu polynesialainen kuningaskunta, joka kukistettiin amerikkalaisten plantaasinomistajien vallankaappauksessa 1893.",
    capital: "Honolulu, Lahaina",
    feature_name_matches: ["Kingdom of Hawaii", "Kō Hawaiʻi Paeʻāina (Hawaiian Kingdom)"]
  },
  {
    slug: "samoa",
    name: "Independent State of Samoa",
    name_fi: "Samoan itsenäinen valtio",
    native_name: "Malo Saʻoloto Tutoʻatasi o Sāmoa",
    alternate_names: ["Samoa", "Western Samoa"],
    culture_group: "Oceania",
    lineage_id: "samoa",
    historical_period: "Polynesian Cradle & Modern Independent State",
    year_start: -1000,
    year_end: 2026,
    period_label: "1000 BCE – Present",
    period_label_fi: "1000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Samoa",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Samoa",
    wikidata_id: "Q683",
    summary_en: "Central Polynesian nation celebrated as the cradle of Polynesian culture (Faʻa Sāmoa), preserving an ancient matai chieftain system and becoming the first Pacific island nation to regain independence in 1962.",
    summary_fi: "Polynesialaisen kulttuurin kehtona pidetty saarivaltio (Faʻa Sāmoa), joka säilytti perinteisen matai-päällikköjärjestelmänsä ja saavutti ensimmäisenä Tyynenmeren maana itsenäisyytensä vuonna 1962.",
    capital: "Apia",
    feature_name_matches: ["Samoa"]
  },
  {
    slug: "american-samoa",
    name: "Territory of American Samoa",
    name_fi: "Amerikan Samoa",
    native_name: "Amerika Sāmoa / Territory of American Samoa",
    alternate_names: ["American Samoa"],
    culture_group: "Oceania",
    lineage_id: "samoa",
    historical_period: "Eastern Samoan Archipelagic Entity",
    year_start: 1900,
    year_end: 2026,
    period_label: "1900 CE – Present",
    period_label_fi: "1900 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/American_Samoa",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Amerikan_Samoa",
    wikidata_id: "Q16641",
    summary_en: "Unincorporated territory of the United States in the southern Pacific consisting of Tutuila and the Manuʻa islands, maintaining traditional communal land tenure under fa'a Samoa.",
    summary_fi: "Yhdysvaltojen territorio eteläisellä Tyynellämerellä, joka koostuu Tutuilasta ja Manuʻan saarista ja jossa maata hallitaan perinteisen yhteisöllisen samoalaisen tavan mukaan.",
    capital: "Pago Pago",
    feature_name_matches: ["American Samoa"]
  },
  {
    slug: "rapa-nui-civilization",
    name: "Rapa Nui (Easter Island)",
    name_fi: "Rapa Nui (Pääsiäissaari)",
    native_name: "Rapa Nui / Te Pito o te Henua",
    alternate_names: ["Rapa Nui", "Easter Island"],
    culture_group: "Oceania",
    lineage_id: "polynesia",
    historical_period: "Megalithic Polynesian Civilization",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Easter_Island",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/P%C3%A4%C3%A4si%C3%A4issaari",
    wikidata_id: "Q14452",
    summary_en: "Isolated Polynesian civilization famed worldwide for carving almost 1,000 monumental monolithic stone moai statues and inventing the undeciphered rongorongo script.",
    summary_fi: "Eristäytynyt polynesialainen korkeakulttuuri, joka tunnetaan lähes tuhannesta monumentaalisesta moai-kivipatsaastaan ja arvoituksellisesta rongorongo-kirjoituksestaan.",
    capital: "Hanga Roa",
    feature_name_matches: ["Rapa Nui"]
  },
  {
    slug: "niue",
    name: "Island of Niue",
    name_fi: "Niue",
    native_name: "Niuē / Niuē Fekai",
    alternate_names: ["Niue"],
    culture_group: "Oceania",
    lineage_id: "polynesia",
    historical_period: "Polynesian Island Realm",
    year_start: 900,
    year_end: 2026,
    period_label: "900 CE – Present",
    period_label_fi: "900 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Niue",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Niue",
    wikidata_id: "Q34020",
    summary_en: "Raised coral atoll known as the 'Rock of Polynesia' settled by Samoan and Tongan voyagers, functioning today as a self-governing state in free association with New Zealand.",
    summary_fi: "Kohonnut koralliatolli, jota kutsutaan 'Polynesian kallioksi'; asutettu Samoalta ja Tongalta ja toimii nykyään itsenäisenä vapaassa liitossa Uuden-Seelannin kanssa.",
    capital: "Alofi",
    feature_name_matches: ["Niue"]
  },
  {
    slug: "wallis-and-futuna",
    name: "Wallis and Futuna Islands",
    name_fi: "Wallis ja Futuna",
    native_name: "ʻUvea mo Futuna",
    alternate_names: ["Wallis and Futuna Islands", "Wallis and Futuna"],
    culture_group: "Oceania",
    lineage_id: "polynesia",
    historical_period: "Polynesian Chiefdoms & French Overseas Territory",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Wallis_and_Futuna",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Wallis_ja_Futuna",
    wikidata_id: "Q35555",
    summary_en: "French island collectivity in the South Pacific comprising the three traditional Polynesian kingdoms of Uvea, Sigave, and Alo, maintaining active customary royal leadership.",
    summary_fi: "Ranskan merentakainen yhteisö Eteläisellä Tyynellämerellä, johon kuuluvat kolme perinteistä polynesialaista kuningaskuntaa Uvea, Sigave ja Alo kuninkaineen.",
    capital: "Mata Utu",
    feature_name_matches: ["Wallis and Futuna Islands"]
  },

  // 4. Melanesia & New Guinea
  {
    slug: "republic-of-fiji",
    name: "Republic of Fiji",
    name_fi: "Fidžin tasavalta",
    native_name: "Matanitu Tukulavu o Viti",
    alternate_names: ["Fiji", "Colony of Fiji"],
    culture_group: "Oceania",
    lineage_id: "fiji",
    historical_period: "Melanesian-Polynesian Border Nation",
    year_start: -1500,
    year_end: 2026,
    period_label: "1500 BCE – Present",
    period_label_fi: "1500 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Fiji",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Fid%C5%BEi",
    wikidata_id: "Q712",
    summary_en: "Melanesian archipelagic nation bridging Melanesia and Polynesia with Lapita ceramic origins, developing elaborate warrior chiefdoms and evolving into a modern South Pacific economic hub.",
    summary_fi: "Melanesian ja Polynesian rajalla sijaitseva saaristovaltio, jolla on Lapita-keramiikkaan ulottuvat juuret ja joka kehittyi merkittäväksi Tyynenmeren talous- ja kulttuurikeskukseksi.",
    capital: "Suva, Levuka",
    feature_name_matches: ["Fiji"]
  },
  {
    slug: "papua-new-guinea",
    name: "Papua New Guinea & Papuans",
    name_fi: "Papua-Uusi-Guinea ja papualaiset",
    native_name: "Independen Stet bilong Papua Niugini / Papuans",
    alternate_names: ["Papua New Guinea", "Papuans", "Papuan", "Papuan neolithic farmers"],
    culture_group: "Oceania",
    lineage_id: "papua",
    historical_period: "Highland Agricultural Cradle & Pacific Nation",
    year_start: -9000,
    year_end: 2026,
    period_label: "9000 BCE – Present",
    period_label_fi: "9000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Papua_New_Guinea",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Papua-Uusi-Guinea",
    wikidata_id: "Q691",
    summary_en: "Home to Kuk Early Agricultural Site, one of humanity's earliest independent plant domestication cradles (taro, bananas), harboring over 800 indigenous languages in the New Guinea highlands.",
    summary_fi: "Kukin muinaisen viljelyalueen ansiosta yksi maapallon varhaisimmista itsenäisistä maanviljelyn syntysijoista, jonka vuoristossa puhutaan yli 800 itsenäistä alkuperäiskieltä.",
    capital: "Port Moresby",
    feature_name_matches: ["Papua New Guinea", "Papuan", "Papuan neolithic farmers", "Papuans"]
  },
  {
    slug: "new-caledonia-kanak",
    name: "New Caledonia (Kanaky)",
    name_fi: "Uusi-Kaledonia (Kanaky)",
    native_name: "Kanaky / Nouvelle-Calédonie",
    alternate_names: ["New Caledonia", "Kanak"],
    culture_group: "Oceania",
    lineage_id: "melanesia",
    historical_period: "Melanesian Island Realm",
    year_start: -1600,
    year_end: 2026,
    period_label: "1600 BCE – Present",
    period_label_fi: "1600 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/New_Caledonia",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Uusi-Kaledonia",
    wikidata_id: "Q33788",
    summary_en: "Melanesian archipelago in the southwest Pacific home to indigenous Kanak clans who built grand ceremonial Grande Case roundhouses and cultivated yam terraced gardens.",
    summary_fi: "Melanesialainen saaristo lounaisella Tyynellämerellä, jonka kanak-alkuperäiskansat rakensivat monumentaalisia pyöreitä päällikkötaloja ja viljelivät jamsseja pengerretyillä rinteillä.",
    capital: "Nouméa",
    feature_name_matches: ["New Caledonia"]
  },
  {
    slug: "new-hebrides-vanuatu",
    name: "New Hebrides (Vanuatu)",
    name_fi: "Uudet-Hebridit (Vanuatu)",
    native_name: "Ripablik blong Vanuatu / New Hebrides",
    alternate_names: ["New Hebrides", "Vanuatu"],
    culture_group: "Oceania",
    lineage_id: "melanesia",
    historical_period: "Melanesian Archipelagic Condominium",
    year_start: -1300,
    year_end: 2026,
    period_label: "1300 BCE – Present",
    period_label_fi: "1300 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Vanuatu",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Vanuatu",
    wikidata_id: "Q686",
    summary_en: "Volcanic archipelago in Melanesia settled by Lapita voyagers, governed jointly as an Anglo-French Condominium before gaining independence as the Republic of Vanuatu in 1980.",
    summary_fi: "Melanesiassa sijaitseva vulkaaninen saaristo, jota Britannia ja Ranska hallinnoivat yhteishallintoalueena ennen sen itsenäistymistä Vanuatun tasavaltana 1980.",
    capital: "Port Vila",
    feature_name_matches: ["New Hebrides"]
  },

  // 5. Austronesian Origins & Archaeological Horizons
  {
    slug: "austronesian-expansion",
    name: "Austronesian Peoples",
    name_fi: "Austronesialaiset kansat",
    native_name: "Austronesian Maritime Sphere",
    alternate_names: ["Austronesians"],
    culture_group: "Oceania",
    lineage_id: "austronesian",
    historical_period: "Maritime Neolithic Migration Horizon",
    year_start: -4000,
    year_end: 1500,
    period_label: "4000 BCE – 1500 CE",
    period_label_fi: "4000 eaa. – 1500 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Austronesian_peoples",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Austronesialaiset_kielet",
    wikidata_id: "Q208453",
    summary_en: "Seafaring linguistic and cultural group originating in Neolithic Taiwan whose outrigger canoe voyagers colonized island Southeast Asia, Madagascar, and remote Polynesia.",
    summary_fi: "Taiwanin neoliittiselta kaudelta lähtöisin oleva merenkulkijoiden kieli- ja kulttuuriperhe, jonka purjehtijat asuttivat Kaakkois-Aasian saariston, Madagaskarin ja koko Polynesian.",
    capital: "Taiwan & Island Southeast Asia",
    feature_name_matches: ["Austronesians"]
  },
  {
    slug: "dapenkeng-culture",
    name: "Dapenkeng Culture & Taiwanese Indigenous Tribes",
    name_fi: "Dapenkeng-kulttuuri ja Taiwanin alkuperäiskansat",
    native_name: "Dàpénkēng / Formosan Indigenous Peoples",
    alternate_names: ["Dapenkeng culture", "Dakapeng culture", "Taiwanese Tribes"],
    culture_group: "Oceania",
    lineage_id: "austronesian",
    historical_period: "Neolithic Taiwan Austronesian Genesis",
    year_start: -4500,
    year_end: 1700,
    period_label: "4500 BCE – 1700 CE",
    period_label_fi: "4500 eaa. – 1700 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Dapenkeng_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Dapenkeng-kulttuuri",
    wikidata_id: "Q5221650",
    summary_en: "Foundational Neolithic cord-marked ceramic culture in coastal Taiwan identified as the linguistic and genetic launchpad for the great Austronesian maritime expansion.",
    summary_fi: "Taiwanin rannikon neoliittinen nuorakeramiikkakulttuuri, jota pidetään kielellisesti ja geneettisesti koko suuren austronesialaisen merivaelluksen alkukotina.",
    capital: "Bali / Tamsui River estuary",
    feature_name_matches: ["Dapenkeng culture", "Dakapeng culture", "Taiwanese Tribes"]
  },

  // 6. Source-Map Tagging Anomalies mapped to proper encyclopedia records
  {
    slug: "armorica-celtic-brittany",
    name: "Armorica (Celtic Gaul & Brittany)",
    name_fi: "Armorika (Kelttiläinen Gallia ja Bretagne)",
    native_name: "Aremorica / Breizh",
    alternate_names: ["Armorica"],
    culture_group: "Oceania",
    lineage_id: "celtic",
    historical_period: "Iron Age Celtic Gaul to Medieval Brittany",
    year_start: -600,
    year_end: 1532,
    period_label: "600 BCE – 1532 CE",
    period_label_fi: "600 eaa. – 1532 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Armorica",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Armorica",
    wikidata_id: "Q746356",
    summary_en: "Maritime Celtic territory in northwestern Gaul between the Seine and Loire that resisted Roman expansion, later receiving Celtic Briton migrants who founded the Duchy of Brittany.",
    summary_fi: "Luoteis-Gallian kelttiläinen rannikkoalue Seinen ja Loiren välillä, joka vastusti Rooman laajentumista ja josta kehittyi brittiläisten muuttajien myötä Bretagnen herttuakunta.",
    capital: "Rennes, Vannes",
    feature_name_matches: ["Armorica"]
  },
  {
    slug: "wassoulou-samori-empire",
    name: "Wassoulou Empire (Samori Touré)",
    name_fi: "Wassouloun valtakunta (Samori Touré)",
    native_name: "Wassoulou / Samori Empire",
    alternate_names: ["First Samori Empire", "Second Samori Empire"],
    culture_group: "Oceania",
    lineage_id: "west-africa",
    historical_period: "Late 19th Century West African Islamic Empire",
    year_start: 1878,
    year_end: 1898,
    period_label: "1878 CE – 1898 CE",
    period_label_fi: "1878 jaa. – 1898 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Wassoulou_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Wassouloun_valtakunta",
    wikidata_id: "Q1435213",
    summary_en: "Formidable Islamic anti-colonial empire created by Samori Touré in Upper Guinea and Côte d'Ivoire equipped with manufactured firearms that resisted French colonial conquest for two decades.",
    summary_fi: "Samori Tourén perustama islamilainen valtakunta Ylä-Guineassa ja Norsunluurannikolla, joka käytti omia tuliasepajoja ja vastusti Ranskan valloitusta kaksi vuosikymmentä.",
    capital: "Bissandugu, Dabakala",
    feature_name_matches: ["First Samori Empire", "Second Samori Empire"]
  },
  {
    slug: "kayapo-mebengokre",
    name: "Kayapó People (Mebêngôkre)",
    name_fi: "Kayapó-kansa (Mebêngôkre)",
    native_name: "Mebêngôkre / Kayapó",
    alternate_names: ["Mebêngôkre (Kayapó)", "Kayapó"],
    culture_group: "Oceania",
    lineage_id: "south-america-indigenous",
    historical_period: "Indigenous Amazonian Jê Nation",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kayapo_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kayapot",
    wikidata_id: "Q1145115",
    summary_en: "Indigenous Jê-speaking nation of the Xingu River basin in the Brazilian Amazon, famed for their environmental stewardship, elaborate body painting, and leader Raoni Metuktire.",
    summary_fi: "Brasilian Amazonian Xingu-joen altaan jê-kielinen alkuperäiskansa, joka tunnetaan sademetsien suojelutaistelustaan, taidokkaista kehomaalauksistaan ja päällikkö Raonista.",
    capital: "Xingu River Basin (Pará / Mato Grosso)",
    feature_name_matches: ["Mebêngôkre (Kayapó)"]
  },
  {
    slug: "weapemeoc-nation",
    name: "Weapemeoc (Yeopim) Nation",
    name_fi: "Weapemeoc-kansa (Yeopim)",
    native_name: "WiYaPeMiAk / Weapemeoc",
    alternate_names: ["WiYaPeMiAk (Weapemeoc-Yeopim)", "Yeopim"],
    culture_group: "Oceania",
    lineage_id: "north-america-indigenous",
    historical_period: "Carolina Sound Algonquian Nation",
    year_start: 1200,
    year_end: 1780,
    period_label: "1200 CE – 1780 CE",
    period_label_fi: "1200 jaa. – 1780 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Weapemeoc",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Algonkinit",
    wikidata_id: "Q7976192",
    summary_en: "Carolina Algonquian nation inhabiting the north shore of Albemarle Sound encountered by English Roanoke colonists, cultivating maize and harvesting estuarine seafood.",
    summary_fi: "Pohjois-Carolinan Albemarle Soundin pohjoisrantaa asuttanut algonkinkansa, jonka englantilaiset Roanoken siirtolaiset kohtasivat 1580-luvulla.",
    capital: "Chepanoc (Albemarle Sound)",
    feature_name_matches: ["WiYaPeMiAk (Weapemeoc-Yeopim)"]
  },
  {
    slug: "jukun-kingdom",
    name: "Jukun Kingdom (Kwararafa)",
    name_fi: "Jukun-kuningaskunta (Kwararafa)",
    native_name: "Kwararafa / Jukun",
    alternate_names: ["Jukun"],
    culture_group: "Oceania",
    lineage_id: "west-africa",
    historical_period: "Benue River Valley Confederation",
    year_start: 1200,
    year_end: 1900,
    period_label: "1200 CE – 1900 CE",
    period_label_fi: "1200 jaa. – 1900 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kwararafa",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kwararafa",
    wikidata_id: "Q3813955",
    summary_en: "Powerful multi-ethnic confederation led by the Jukun people in the Benue River valley of modern Nigeria, renowned for horse cavalry raids across the northern savannas.",
    summary_fi: "Jukun-kansan johtama voimakas valtioliitto Benue-joen laaksossa nykyisessä Nigeriassa, joka tunnettiin sotaisasta ratsuväestään ja menestyksestä hausoja vastaan.",
    capital: "Wukari",
    feature_name_matches: ["Jukun"]
  }
]

const outPath = path.resolve(__dirname, "../data-sources/batches/oceania.json")
fs.writeFileSync(outPath, JSON.stringify(OCEANIA_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${OCEANIA_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(OCEANIA_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
