import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "./seed_culture_metadata_batch"

const EAST_AFRICA_CULTURES: CultureBatchEntry[] = [
  {
    slug: "kerma-kingdom",
    name: "Kingdom of Kerma",
    name_fi: "Kerman kuningaskunta",
    native_name: "Kerma",
    alternate_names: ["Kerma Culture", "Early Nubian Kingdom"],
    culture_group: "East Africa",
    lineage_id: "nubia",
    historical_period: "Bronze Age Nubia",
    year_start: -2500,
    year_end: -1500,
    period_label: "2500 BCE – 1500 BCE",
    period_label_fi: "2500 eaa. – 1500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kerma_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kerma_(kuningaskunta)",
    wikidata_id: "Q844111",
    summary_en: "Indigenous Nubian civilization centered at the monumental mudbrick temple (Western Deffufa) on the Nile, competing with Egypt's Middle and New Kingdoms with famed Nubian archers.",
    summary_fi: "Muinainen nubialainen sivilisaatio Niilin varrella, joka tunnetaan massiivisista savitiilitemppeleistään (Deffufa) ja taitavista jousiampujistaan, jotka kilpailivat Egyptin faaraoiden kanssa.",
    capital: "Kerma",
    feature_name_matches: ["Kerma"]
  },
  {
    slug: "blemmyes-kingdom",
    name: "Blemmyes & Beja Kingdom",
    name_fi: "Blemmyit ja bedžavaltakunta",
    native_name: "Βλέμμυες",
    alternate_names: ["Blemmyes", "Beja People"],
    culture_group: "East Africa",
    lineage_id: "east-africa",
    historical_period: "Classical Antiquity to Early Middle Ages",
    year_start: -600,
    year_end: 600,
    period_label: "600 BCE – 600 CE",
    period_label_fi: "600 eaa. – 600 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Blemmyes",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Blemmyit",
    wikidata_id: "Q883870",
    summary_en: "Nomadic pastoralist confederation in the Eastern Desert between the Nile and the Red Sea, frequently clashing with Roman and Byzantine frontier legions in Upper Egypt.",
    summary_fi: "Niilin ja Punaisenmeren välisen itäisen aavikon paimentolaiskansa, joka kävi toistuvia taisteluja Rooman ja Bysantin rajalegioonia vastaan Ylä-Egyptissä.",
    capital: "Eastern Desert",
    feature_name_matches: ["Blemmyes"]
  },
  {
    slug: "christian-nubian-kingdoms",
    name: "Christian Nubian Kingdoms",
    name_fi: "Kristityt nubialaiskuningaskunnat",
    native_name: "Nobatia / Makuria / Alodia",
    alternate_names: ["Nobatia", "Makkura", "Alwa", "Makuria", "Alodia"],
    culture_group: "East Africa",
    lineage_id: "nubia",
    historical_period: "Medieval Nubia",
    year_start: 350,
    year_end: 1504,
    period_label: "350 CE – 1504 CE",
    period_label_fi: "350 jaa. – 1504 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Makuria",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Makuria",
    wikidata_id: "Q844391",
    summary_en: "Three medieval Christian kingdoms (Nobatia, Makuria, and Alodia/Alwa) along the Middle Nile that preserved Coptic and Old Nubian liturgies, signing the 600-year Baqt treaty with Arab Egypt.",
    summary_fi: "Niilin keskijuoksun kolme keskiaikaista kristittyä kuningaskuntaa (Nobatia, Makuria ja Alwa), jotka säilyttivät koptilaisen kirkkotaiteen ja solmivat Baqt-rauhansopimuksen arabien kanssa.",
    capital: "Dongola, Faras, Soba",
    feature_name_matches: ["Nobatia", "Makkura", "Alwa"]
  },
  {
    slug: "funj-sultanate",
    name: "Funj Sultanate of Sennar",
    name_fi: "Funjin sulttaanikunta (Sennar)",
    native_name: "سلطنة سنار",
    alternate_names: ["Funj", "Sultanate of Sennar", "Black Sultanate"],
    culture_group: "East Africa",
    lineage_id: "sudan",
    historical_period: "Early Modern Sudan",
    year_start: 1504,
    year_end: 1821,
    period_label: "1504 CE – 1821 CE",
    period_label_fi: "1504 jaa. – 1821 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sennar_(sultanate)",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sennarin_sulttaanikunta",
    wikidata_id: "Q845344",
    summary_en: "Islamic sultanate along the Blue Nile that succeeded Christian Alodia, controlling Sudan's trade caravans and promoting Islamic learning and Sufism until conquest by Muhammad Ali's Egypt.",
    summary_fi: "Sinisen Niilin varrella toiminut islamilainen sulttaanikunta Sudanissa, joka valvoi kauppakaravaaneja ja tuki suufilaista oppineisuutta aina Egyptin valloitukseen (1821) saakka.",
    capital: "Sennar",
    feature_name_matches: ["Funj"]
  },
  {
    slug: "darfur-sultanate",
    name: "Sultanate of Darfur",
    name_fi: "Darfurin sulttaanikunta",
    native_name: "سلطنة دارفور",
    alternate_names: ["Darfur", "Keira Dynasty"],
    culture_group: "East Africa",
    lineage_id: "sudan",
    historical_period: "Early Modern to Early 20th Century",
    year_start: 1603,
    year_end: 1916,
    period_label: "1603 CE – 1916 CE",
    period_label_fi: "1603 jaa. – 1916 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sultanate_of_Darfur",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Darfurin_sulttaanikunta",
    wikidata_id: "Q913619",
    summary_en: "Pre-colonial state in western Sudan ruled by the Keira dynasty of the Fur people, controlling the Forty Days Road (Darb al-Arbain) trans-Saharan caravan route until British annexation in 1916.",
    summary_fi: "Länsi-Sudanin historiallinen valtakunta, jota fur-kansan Keira-dynastia hallitsi valvoen neljänkymmenen päivän karavaanireittiä (Darb al-Arbain) Egyptiin asti.",
    capital: "Al-Fashir",
    feature_name_matches: ["Darfur"]
  },
  {
    slug: "damot-highlands",
    name: "Kingdom of D'mt & Ethiopian Highlands",
    name_fi: "D'mtin kuningaskunta ja Etiopian ylängöt",
    native_name: "ደዕመት (D'mt)",
    alternate_names: ["Damot", "Ethiopian Highland Peoples", "Ethiopian highland farmers"],
    culture_group: "East Africa",
    lineage_id: "ethiopia",
    historical_period: "Ancient Ethiopian Highlands",
    year_start: -1000,
    year_end: 400,
    period_label: "1000 BCE – 400 CE",
    period_label_fi: "1000 eaa. – 400 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/D%CA%BDmt",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/D%E2%80%99mt",
    wikidata_id: "Q853549",
    summary_en: "Iron Age highland kingdom in northern Ethiopia and Eritrea centered at Yeha, possessing close cultural, architectural, and linguistic links with Sabaean South Arabia and pioneering terraced agriculture.",
    summary_fi: "Varhainen rautakautinen kuningaskunta Pohjois-Etiopian ylängöllä Yehan keskuksessa, jolla oli vahvat kulttuuri- ja kauppayhteydet Etelä-Arabian sabalaisiin.",
    capital: "Yeha",
    feature_name_matches: ["Damot", "Ethiopian Highland Peoples", "Ethiopian highland farmers"]
  },
  {
    slug: "aksumite-empire",
    name: "Kingdom of Aksum",
    name_fi: "Aksumin valtakunta",
    native_name: "መንግሥተ አክሱም",
    alternate_names: ["Axum", "Aksumite Empire"],
    culture_group: "East Africa",
    lineage_id: "ethiopia",
    historical_period: "Classical Antiquity to Early Middle Ages",
    year_start: 100,
    year_end: 940,
    period_label: "100 CE – 940 CE",
    period_label_fi: "100 jaa. – 940 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Aksum",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Aksumin_valtakunta",
    wikidata_id: "Q184536",
    summary_en: "Major trading empire dominating the Red Sea and Horn of Africa, erecting towering stone obelisks, minting its own coinage, and adopting Christianity under King Ezana in c. 330 CE.",
    summary_fi: "Punaisenmeren ja Afrikan sarven mahtava kauppaimperiumi, joka pystytti massiivisia kiviobeliskeja, löi omia kultarahoja ja omaksui kristinuskon kuningas Ezanan johdolla noin vuonna 330 jaa.",
    capital: "Aksum",
    feature_name_matches: ["Axum"]
  },
  {
    slug: "ethiopian-empire",
    name: "Ethiopian Empire (Abyssinia)",
    name_fi: "Etiopian keisarikunta (Abessinia)",
    native_name: "የኢትዮጵያ ንጉሠ ነገሥት መንግሥተ",
    alternate_names: ["Abyssinia", "Ethiopia", "Ethiopia (Italy)", "Shoa"],
    culture_group: "East Africa",
    lineage_id: "ethiopia",
    historical_period: "Medieval to Modern Horn of Africa",
    year_start: 1270,
    year_end: 2026,
    period_label: "1270 CE – Present",
    period_label_fi: "1270 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Ethiopian_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Etiopian_keisarikunta",
    wikidata_id: "Q207521",
    summary_en: "Monarchical empire ruled by the Solomonic dynasty that famously defeated an Italian invasion at Adwa in 1896 under Menelik II, preserving sovereign African independence throughout the colonial era.",
    summary_fi: "Salomonisen dynastian hallitsema vuoristokeisarikunta, joka torjui Italian valloitusyrityksen kuuluisassa Adwan taistelussa vuonna 1896 ja säilytti itsenäisyytensä siirtomaa-aikana.",
    capital: "Addis Ababa, Gondar, Ankober",
    feature_name_matches: ["Abyssinia", "Ethiopia", "Ethiopia (Italy)", "Shoa"]
  },
  {
    slug: "adal-sultanate",
    name: "Adal & Ifat Sultanates",
    name_fi: "Adalin ja Ifatin sulttaanikunnat",
    native_name: "سلطنة عدل",
    alternate_names: ["Adal", "Ifat", "Adal Sultanate"],
    culture_group: "East Africa",
    lineage_id: "somalia",
    historical_period: "Medieval Horn of Africa",
    year_start: 1285,
    year_end: 1577,
    period_label: "1285 CE – 1577 CE",
    period_label_fi: "1285 jaa. – 1577 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Adal_Sultanate",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Adal",
    wikidata_id: "Q348421",
    summary_en: "Muslim Somali-Afar-Harari state in the Horn of Africa centered at Zeila and Harar, launching a major 16th-century conquest against the Ethiopian Empire led by Imam Ahmad ibn Ibrahim al-Ghazi.",
    summary_fi: "Afrikan sarven islamilainen sulttaanikunta Zeilan ja Hararin kaupungeissa, joka kävi 1500-luvulla laajan valloitussodan Etiopian keisarikuntaa vastaan imaami Ahmad Gragnin johdolla.",
    capital: "Zeila, Harar",
    feature_name_matches: ["Adal", "Ifat"]
  },
  {
    slug: "oromo-nation",
    name: "Oromo Peoples & Gadaa",
    name_fi: "Oromokansa ja Gadaa-järjestelmä",
    native_name: "Oromoo",
    alternate_names: ["Oromo"],
    culture_group: "East Africa",
    lineage_id: "ethiopia",
    historical_period: "Precolonial to Modern Horn of Africa",
    year_start: 1500,
    year_end: 2026,
    period_label: "1500 CE – Present",
    period_label_fi: "1500 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Oromo_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Oromot",
    wikidata_id: "Q318550",
    summary_en: "Largest ethnolinguistic group in the Horn of Africa, distinguished by the democratic Gadaa socio-political generation-grade governance system inscribed on UNESCO's Intangible Heritage list.",
    summary_fi: "Afrikan sarven suurin kansa, joka tunnetaan ainutlaatuisesta demokraattisesta ikäluokkahallintojärjestelmästään (Gadaa), joka on valittu Unescon aineettoman kulttuuriperinnön luetteloon.",
    capital: "Finfine / Oromia",
    feature_name_matches: ["Oromo"]
  },
  {
    slug: "somali-republic",
    name: "Somali Kingdoms & Republic",
    name_fi: "Somalivaltiot ja Somalian tasavalta",
    native_name: "Soomaaliya",
    alternate_names: ["Somalia", "British Somaliland", "Italian Somaliland"],
    culture_group: "East Africa",
    lineage_id: "somalia",
    historical_period: "Colonial to Modern Horn of Africa",
    year_start: 1888,
    year_end: 2026,
    period_label: "1888 CE – Present",
    period_label_fi: "1888 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Somalia",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Somalia",
    wikidata_id: "Q1045",
    summary_en: "Coastal nation commanding Africa's longest coastline along the Gulf of Aden and Indian Ocean, formed by unifying British Somaliland and Italian Somaliland in 1960.",
    summary_fi: "Afrikan mantereen pisimmän rantaviivan omaava valtio Adeninlahden ja Intian valtameren rannalla, joka muodostui Britannian ja Italian Somalimaiden yhdistyessä vuonna 1960.",
    capital: "Mogadishu, Hargeisa",
    feature_name_matches: ["Somalia", "British Somaliland", "Italian Somaliland"]
  },
  {
    slug: "republic-of-djibouti",
    name: "Republic of Djibouti",
    name_fi: "Djiboutin tasavalta",
    native_name: "Djibouti / جيبوتي",
    alternate_names: ["Djibouti", "French Somaliland"],
    culture_group: "East Africa",
    lineage_id: "djibouti",
    historical_period: "Colonial to Modern Bab-el-Mandeb",
    year_start: 1896,
    year_end: 2026,
    period_label: "1896 CE – Present",
    period_label_fi: "1896 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Djibouti",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Djibouti",
    wikidata_id: "Q977",
    summary_en: "Strategically located nation on the Bab-el-Mandeb strait linking the Red Sea to the Gulf of Aden, formerly French Somaliland, inhabited by Issa Somali and Afar communities.",
    summary_fi: "Strategisesti tärkeä valtio Bab el Mandebin salmella Punaisenmeren suulla, entinen Ranskan Somalimaa, jonka asukkaita ovat issasomalit ja afarit.",
    capital: "Djibouti City",
    feature_name_matches: ["Djibouti", "French Somaliland"]
  },
  {
    slug: "state-of-eritrea",
    name: "State of Eritrea",
    name_fi: "Eritrean valtio",
    native_name: "ኤርትራ / إرتريا",
    alternate_names: ["Eritrea", "Eritrea (Italy)"],
    culture_group: "East Africa",
    lineage_id: "eritrea",
    historical_period: "Colonial to Modern Red Sea Coast",
    year_start: 1890,
    year_end: 2026,
    period_label: "1890 CE – Present",
    period_label_fi: "1890 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Eritrea",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Eritrea",
    wikidata_id: "Q986",
    summary_en: "Red Sea nation founded as an Italian colony in 1890, gaining independence from Ethiopia in 1993 after a thirty-year armed struggle, famed for the modernist architecture of Asmara.",
    summary_fi: "Punaisenmeren rannikkovaltio, joka perustettiin Italian siirtomaana vuonna 1890 ja saavutti itsenäisyytensä kolmikymmenvuotisen sodan jälkeen vuonna 1993.",
    capital: "Asmara",
    feature_name_matches: ["Eritrea", "Eritrea (Italy)"]
  },
  {
    slug: "buganda-kingdom",
    name: "Kingdom of Buganda",
    name_fi: "Bugandan kuningaskunta",
    native_name: "Obwakabaka bwa Buganda",
    alternate_names: ["Buganda"],
    culture_group: "East Africa",
    lineage_id: "uganda",
    historical_period: "Late Medieval to Modern Great Lakes",
    year_start: 1300,
    year_end: 2026,
    period_label: "1300 CE – Present",
    period_label_fi: "1300 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Buganda",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Buganda",
    wikidata_id: "Q472146",
    summary_en: "Dominant Bantu kingdom on the northern shores of Lake Victoria ruled by the Kabaka, possessing a powerful royal war-canoe navy and the historic UNESCO-listed Kasubi Tombs.",
    summary_fi: "Victorianjärven pohjoisrannikkoa hallinnut suuri bantukuningaskunta, jota johti kabaka ja joka tunnetaan Kasubin kuninkaallisista haudoista.",
    capital: "Mengo, Kampala",
    feature_name_matches: ["Buganda"]
  },
  {
    slug: "bunyoro-uganda",
    name: "Bunyoro-Kitara & Republic of Uganda",
    name_fi: "Bunyoro-Kitara ja Ugandan tasavalta",
    native_name: "Bunyoro-Kitara / Uganda",
    alternate_names: ["Bunyoro", "Uganda"],
    culture_group: "East Africa",
    lineage_id: "uganda",
    historical_period: "Medieval to Modern Great Lakes",
    year_start: 1300,
    year_end: 2026,
    period_label: "1300 CE – Present",
    period_label_fi: "1300 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Bunyoro",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bunyoro",
    wikidata_id: "Q852373",
    summary_en: "Ancient Great Lakes empire founded by the Batembuzi and Bachwezi dynasties, resisting British colonization under Omukama Kabalega, evolving into the Republic of Uganda.",
    summary_fi: "Suurten järvien historiallinen imperiumi Länsi-Ugandassa, jota hallitsi omukama ja jonka perintö on osa nykyistä Ugandan tasavaltaa.",
    capital: "Hoima, Entebbe, Kampala",
    feature_name_matches: ["Bunyoro", "Uganda"]
  },
  {
    slug: "rwanda-kingdom",
    name: "Kingdom & Republic of Rwanda",
    name_fi: "Ruandan kuningaskunta ja tasavalta",
    native_name: "Ubwami bw'u Rwanda",
    alternate_names: ["Rwanda", "Rwanda (Belgium)"],
    culture_group: "East Africa",
    lineage_id: "rwanda",
    historical_period: "Precolonial to Modern Great Lakes",
    year_start: 1400,
    year_end: 2026,
    period_label: "1400 CE – Present",
    period_label_fi: "1400 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Rwanda",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ruanda",
    wikidata_id: "Q1037",
    summary_en: "Highland kingdom known as the 'Land of a Thousand Hills', ruled by the Mwami until the 1961 revolution and emerging as a rapidly developing modern technological center.",
    summary_fi: "Tuhansien kukkuloiden maana tunnettu Suurten järvien ylänkövaltio, jota hallitsivat perinteiset kuninkaat (mwami) ennen modernin tasavallan muodostumista.",
    capital: "Nyanza, Kigali",
    feature_name_matches: ["Rwanda", "Rwanda (Belgium)"]
  },
  {
    slug: "burundi-kingdom",
    name: "Kingdom & Republic of Burundi",
    name_fi: "Burundin kuningaskunta ja tasavalta",
    native_name: "Ubwami bw'i Burundi",
    alternate_names: ["Burundi"],
    culture_group: "East Africa",
    lineage_id: "burundi",
    historical_period: "Precolonial to Modern Great Lakes",
    year_start: 1680,
    year_end: 2026,
    period_label: "1680 CE – Present",
    period_label_fi: "1680 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Burundi",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Burundi",
    wikidata_id: "Q967",
    summary_en: "Traditional Great Lakes monarchy founded by Ntare Rushatsi, famed for royal sacred drum (Karyenda) sanctuaries and surviving as a sovereign kingdom until 1966.",
    summary_fi: "Perinteinen Suurten järvien kuningaskunta Tanganjikajärven rannalla, joka tunnettiin pyhistä kuninkaallisista rummuistaan (karyenda).",
    capital: "Muramvya, Gitega, Bujumbura",
    feature_name_matches: ["Burundi"]
  },
  {
    slug: "republic-of-kenya",
    name: "Republic of Kenya",
    name_fi: "Kenian tasavalta",
    native_name: "Kenya",
    alternate_names: ["Kenya", "British East Africa"],
    culture_group: "East Africa",
    lineage_id: "kenya",
    historical_period: "Colonial to Modern East Africa",
    year_start: 1895,
    year_end: 2026,
    period_label: "1895 CE – Present",
    period_label_fi: "1895 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kenya",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kenia",
    wikidata_id: "Q114",
    summary_en: "East African economic hub encompassing the Great Rift Valley, Swahili coastal ports like Mombasa, and the Maasai Mara, gaining independence from Britain in 1963 under Jomo Kenyatta.",
    summary_fi: "Itä-Afrikan talouskeskus Ison hautavajoaman laaksossa, joka tunnetaan Mombasan historiallisesta swahilirannikosta ja kansallispuistoistaan.",
    capital: "Nairobi, Mombasa",
    feature_name_matches: ["Kenya"]
  },
  {
    slug: "zanzibar-sultanate",
    name: "Sultanate of Zanzibar",
    name_fi: "Sansibarin sulttaanikunta",
    native_name: "سلطنة زنجبار",
    alternate_names: ["Zanzibar", "Sultanate of Zanzibar", "Sultinate of Zanzibar"],
    culture_group: "East Africa",
    lineage_id: "tanzania",
    historical_period: "Early Modern to 20th Century Swahili Coast",
    year_start: 1856,
    year_end: 1964,
    period_label: "1856 CE – 1964 CE",
    period_label_fi: "1856 jaa. – 1964 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sultanate_of_Zanzibar",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sansibar_(sulttaanikunta)",
    wikidata_id: "Q211116",
    summary_en: "Swahili spice and commercial island empire ruled by an Omani royal dynasty from Stone Town, controlling the East African clove trade and commercial coastal caravan networks.",
    summary_fi: "Intian valtameren maustesaarten sulttaanikunta Kivikaupungissa (Stone Town), jota Omanin hallitsijasuku johti ja joka hallitsi neilikkakauppaa.",
    capital: "Stone Town, Zanzibar",
    feature_name_matches: ["Zanzibar", "Sultanate of Zanzibar", "Sultinate of Zanzibar"]
  },
  {
    slug: "merina-kingdom-madagascar",
    name: "Merina Kingdom & Republic of Madagascar",
    name_fi: "Merinan kuningaskunta ja Madagaskarin tasavalta",
    native_name: "Fanjakan'Imerina / Madagasikara",
    alternate_names: ["Merina Kingdom", "Imerina", "Madagascar", "Madagascar (France)"],
    culture_group: "East Africa",
    lineage_id: "madagascar",
    historical_period: "Early Modern to Modern Madagascar",
    year_start: 1540,
    year_end: 2026,
    period_label: "1540 CE – Present",
    period_label_fi: "1540 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Merina_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Madagaskarin_kuningaskunta",
    wikidata_id: "Q844234",
    summary_en: "Highland kingdom of the Austronesian-speaking Merina people unified by King Andrianampoinimerina and Queen Ranavalona I, ruling the world's fourth largest island from the Rova of Antananarivo.",
    summary_fi: "Madagaskarin ylänköjen austronesialaisen merinakansan kuningaskunta, joka yhdisti koko saaren ja hallitsi sitä Antananarivon kuninkaallisesta palatsista (Rova).",
    capital: "Antananarivo, Ambohimanga",
    feature_name_matches: ["Merina Kingdom", "Imerina", "Madagascar", "Madagascar (France)"]
  },
  {
    slug: "imamate-of-futa-toro",
    name: "Imamate of Futa Toro",
    name_fi: "Futa Toron imaamikunta",
    native_name: "Fuuta Tooro",
    alternate_names: ["Futa Toro"],
    culture_group: "East Africa",
    lineage_id: "senegal",
    historical_period: "Early Modern West African Theocracy",
    year_start: 1776,
    year_end: 1859,
    period_label: "1776 CE – 1859 CE",
    period_label_fi: "1776 jaa. – 1859 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Imamate_of_Futa_Toro",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Futa_Toro",
    wikidata_id: "Q889154",
    summary_en: "Theocratic Fula Islamic state in the Senegal River valley established by Torodbe clerics under Ceerno Sulaymaan Baal, banning the transatlantic slave trade across its borders.",
    summary_fi: "Fulanikansan teokraattinen islamilainen valtio Senegalin jokilaaksossa, jonka oppineet perustivat ja joka kielsi orjakaupan alueensa läpi.",
    capital: "Futa Toro",
    feature_name_matches: ["Futa Toro"]
  },
  {
    slug: "shoalwater-bay-indigenous",
    name: "Darumbal People of Shoalwater Bay",
    name_fi: "Shoalwater Bayn darumbalit",
    alternate_names: ["Shoalwater Bay", "Darumbal"],
    culture_group: "East Africa",
    lineage_id: "oceania",
    historical_period: "Australian Indigenous Traditions",
    year_start: -10000,
    year_end: 2026,
    period_label: "10,000 BCE – Present",
    period_label_fi: "10 000 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Darumbal",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Australian_alkuasukkaat",
    wikidata_id: "Q5225791",
    summary_en: "Aboriginal Australian people of the Capricorn Coast and Shoalwater Bay in Central Queensland, with enduring spiritual, cultural, and hunting custodial ties to coastal lands and waters.",
    summary_fi: "Australian Queenslandin rannikon ja Shoalwater Bayn alkuperäiskansa, jolla on vuosituhantinen perinteinen side rannikon meri- ja maa-alueisiin.",
    capital: "Rockhampton / Shoalwater Bay",
    feature_name_matches: ["Shoalwater Bay"]
  },
  {
    slug: "toromona-people",
    name: "Toromona Indigenous People",
    name_fi: "Toromona-kansa",
    alternate_names: ["Toromona"],
    culture_group: "East Africa",
    lineage_id: "andean",
    historical_period: "Amazonian Indigenous Traditions",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Toromona_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bolivian_intiaanit",
    wikidata_id: "Q2669389",
    summary_en: "Indigenous uncontacted or isolated people living in the upper Madre de Dios and Madidi river basins of northern Bolivia, famously resisting Inca incursions into the Amazonian lowlands.",
    summary_fi: "Amazonian ylängön ja Madidi-kansallispuiston alueella Pohjois-Boliviassa asuva alkuperäiskansa, joka torjui aikanaan inkojen valloitusretket sademetsiin.",
    capital: "Madidi River",
    feature_name_matches: ["Toromona"]
  }
]

const outPath = path.resolve(__dirname, "../data-sources/batches/east-africa.json")
fs.writeFileSync(outPath, JSON.stringify(EAST_AFRICA_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${EAST_AFRICA_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(EAST_AFRICA_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
