import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "./seed_culture_metadata_batch"

const SOUTH_ASIA_CULTURES: CultureBatchEntry[] = [
  {
    slug: "indus-valley-civilization",
    name: "Indus Valley Civilisation",
    name_fi: "Indus-kulttuuri",
    native_name: "Meluhha",
    alternate_names: ["Harappan Civilisation", "Indus Civilisation"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Bronze Age South Asia",
    year_start: -3300,
    year_end: -1300,
    period_label: "3300 BCE – 1300 BCE",
    period_label_fi: "3300 eaa. – 1300 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Indus_Valley_Civilisation",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Indus-kulttuuri",
    wikidata_id: "Q1344",
    summary_en: "A major Bronze Age civilization in northwestern South Asia that flourished around the Indus River basin. Famous for sophisticated urban planning, baked-brick houses, advanced drainage systems, granaries, and undeciphered Indus script.",
    summary_fi: "Merkittävä pronssikautinen sivilisaatio Luoteis-Etelä-Aasiassa Indus-joen laaksossa. Tunnetaan edistyksellisestä kaupunkisuunnittelusta, poltetuista tiilirakennuksista, viemärijärjestelmistä ja toistaiseksi avaamattomasta kirjoituksesta.",
    capital: "Harappa, Mohenjo-daro",
    feature_name_matches: ["Indus valley civilization"]
  },
  {
    slug: "gandhara-grave-culture",
    name: "Gandhara Grave Culture",
    name_fi: "Gandharan hautakulttuuri",
    alternate_names: ["Swat Culture"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Iron Age",
    year_start: -1400,
    year_end: -500,
    period_label: "1400 BCE – 500 BCE",
    period_label_fi: "1400 eaa. – 500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gandhara_grave_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gandharan_hautakulttuuri",
    wikidata_id: "Q2634351",
    summary_en: "An archaeological culture emerging in the Swat River valley and Gandhara region, characterized by cist graves, horse burials, and distinctive burnished pottery, bridging Central Asian migrants with northern South Asia.",
    summary_fi: "Arkeologinen kulttuuri Swat-joen laaksossa ja Gandharassa, jolle olivat ominaisia arkkuhautaukset, hevoshautaukset ja omaleimainen keramiikka varhaisella rautakaudella.",
    capital: "Swat Valley",
    feature_name_matches: ["Gandhara grave culture"]
  },
  {
    slug: "vedic-aryans",
    name: "Vedic Aryans",
    name_fi: "Veedalaiset arjalaiset",
    native_name: "आर्य (Ārya)",
    alternate_names: ["Vedic Culture", "Vedic India"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Vedic Period",
    year_start: -1500,
    year_end: -500,
    period_label: "1500 BCE – 500 BCE",
    period_label_fi: "1500 eaa. – 500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Vedic_period",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Veda-kausi",
    wikidata_id: "Q194452",
    summary_en: "Indo-Aryan pastoralist and agrarian society of the northern Indian subcontinent that composed the sacred Vedas in Sanskrit, establishing foundational theological, philosophical, and social frameworks of Hinduism.",
    summary_fi: "Indoarjalainen pastoraalinen ja maata viljelevä yhteiskunta Pohjois-Intiassa, joka sävelsi pyhät Veda-kirjat sanskritiksi ja muovasi hindulaisuuden teologiset ja yhteiskunnalliset perusteet.",
    capital: "Hastinapura, Ayodhya",
    feature_name_matches: ["Vedic Aryans"]
  },
  {
    slug: "dravidians",
    name: "Ancient Dravidian Peoples",
    name_fi: "Dravidakansat",
    native_name: "திராவிடர் (Tirāviṭar)",
    alternate_names: ["Dravidian Civilization", "Early Dravidians"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Iron Age to Classical South India",
    year_start: -1000,
    year_end: 500,
    period_label: "1000 BCE – 500 CE",
    period_label_fi: "1000 eaa. – 500 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Dravidian_peoples",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Dravidakansat",
    wikidata_id: "Q184407",
    summary_en: "Linguistic and cultural groups of the southern Deccan and Tamilakam who developed megalithic burial complexes, maritime Indian Ocean trade, and ancient Sangam literature.",
    summary_fi: "Etelä-Intian ja Deccanin kielelliset ja kulttuuriset ryhmät, jotka kehittivät megaliittisia hautausperinteitä, vilkasta Intian valtameren kauppaa ja klassista Sangam-kirjallisuutta.",
    capital: "Madurai, Karur",
    feature_name_matches: ["Dravidians"]
  },
  {
    slug: "mauryan-empire",
    name: "Maurya Empire",
    name_fi: "Maurya-valtakunta",
    native_name: "मौर्य साम्राज्यम्",
    alternate_names: ["Mauryan Empire", "Empire of Ashoka"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Iron Age Imperial India",
    year_start: -322,
    year_end: -185,
    period_label: "322 BCE – 185 BCE",
    period_label_fi: "322 eaa. – 185 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Maurya_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Maurya-valtakunta",
    wikidata_id: "Q62943",
    summary_en: "A pan-Indian iron age empire founded by Chandragupta Maurya and counselled by Chanakya. Reaching its zenith under Ashoka the Great, it unified nearly the entire subcontinent, spreading Buddhism via monumental edicts and pillars.",
    summary_fi: "Chandragupta Mauryan perustama suuri rautakautinen intialainen imperiumi, joka yhdisti lähes koko niemimaan ja jonka hallitsija Ašoka levitti buddhalaisuutta ympäri Aasiaa kalliokirjoituksillaan.",
    capital: "Pataliputra",
    feature_name_matches: ["Mauryan Empire"]
  },
  {
    slug: "satavahana-dynasty",
    name: "Satavahana Dynasty",
    name_fi: "Satavahana-dynastia",
    native_name: "శాతవాహన",
    alternate_names: ["Andhras", "Satavahanas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Post-Mauryan Classical Deccan",
    year_start: -100,
    year_end: 225,
    period_label: "100 BCE – 225 CE",
    period_label_fi: "100 eaa. – 225 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Satavahana_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Satavahanat",
    wikidata_id: "Q5257",
    summary_en: "Ancient Deccan empire covering modern Telangana, Andhra Pradesh, and Maharashtra that established trade connections with the Roman Empire and sponsored Buddhist monuments such as Amaravati and Karla caves.",
    summary_fi: "Deccanin ylängön muinainen kuningaskunta, joka hallitsi Keski- ja Etelä-Intiaa, kävi kauppaa Rooman valtakunnan kanssa ja rahoitti Amaravatin ja Karlan luolien buddhalaisia muistomerkkejä.",
    capital: "Pratishthana, Amaravati",
    feature_name_matches: ["Satavahanihara"]
  },
  {
    slug: "kalinga-kingdom",
    name: "Kalinga",
    name_fi: "Kalinga",
    native_name: "କଳିଙ୍ଗ",
    alternate_names: ["Kalinga Kingdom", "Chedi Dynasty"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Classical East India",
    year_start: -500,
    year_end: 400,
    period_label: "500 BCE – 400 CE",
    period_label_fi: "500 eaa. – 400 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kalinga_(historical_region)",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kalinga",
    wikidata_id: "Q1143216",
    summary_en: "Historical coastal realm in modern Odisha and Andhra Pradesh whose devastating conquest by Ashoka in 261 BCE prompted Ashoka's conversion to Buddhism. Later revived as a major maritime power under Emperor Kharavela.",
    summary_fi: "Historiallinen rannikkovaltakunta nykyisessä Odishassa, jonka tuhoisa valloitus vuonna 261 eaa. sai Maurya-keisari Ašokan kääntymään buddhalaisuuteen. Nousi myöhemmin uudestaan keisari Kharavelan johdolla.",
    capital: "Kalinganagara, Sisupalgarh",
    feature_name_matches: ["Kalinga"]
  },
  {
    slug: "chola-empire",
    name: "Chola Empire",
    name_fi: "Chola-valtakunta",
    native_name: "சோழர் (Cōḻar)",
    alternate_names: ["Chola Dynasty", "Imperial Cholas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Classical to Medieval South India",
    year_start: -300,
    year_end: 1279,
    period_label: "300 BCE – 1279 CE",
    period_label_fi: "300 eaa. – 1279 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Chola_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Chola",
    wikidata_id: "Q151148",
    summary_en: "One of the longest-ruling Tamil dynasties in southern India, creating a formidable thalassocracy under Rajaraja I and Rajendra I that projected power across the Bay of Bengal into Sri Lanka and Southeast Asia.",
    summary_fi: "Yksi pisimpään hallinneista eteläintialaisista tamili-dynastioista, joka loi kukoistavan merivaltakunnan, hallitsi Bengalinlahtea ja rakensi massiivisia graniittitemppeleitä kuten Thanjavurin Brihadisvaran.",
    capital: "Thanjavur, Gangaikonda Cholapuram, Uraiyur",
    feature_name_matches: ["Chola", "Chola Empire", "Cholas"]
  },
  {
    slug: "pandya-dynasty",
    name: "Pandya Dynasty",
    name_fi: "Pandya-dynastia",
    native_name: "பாண்டியர்",
    alternate_names: ["Pandyan Kingdom", "Pandyas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Ancient to Medieval Tamilakam",
    year_start: -300,
    year_end: 1345,
    period_label: "300 BCE – 1345 CE",
    period_label_fi: "300 eaa. – 1345 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Pandya_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pandya-dynastia",
    wikidata_id: "Q213340",
    summary_en: "Ancient Tamil dynasty ruling from Madurai, known for renowned pearl fisheries in the Gulf of Mannar, patronage of Tamil Sangam poetry, and enduring temples across southern Tamil Nadu.",
    summary_fi: "Muinainen tamilidynastia Maduraissa, joka tunnettiin Mannarinlahden helmikalastuksesta, Sangam-runouden suojelusta sekä eteläisen Intian suurista temppeleistä.",
    capital: "Madurai, Korkai",
    feature_name_matches: ["Pandya state", "Pandyas"]
  },
  {
    slug: "chera-dynasty",
    name: "Chera Dynasty",
    name_fi: "Chera-dynastia",
    native_name: "சேரர்",
    alternate_names: ["Keralaputras", "Cheras"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Sangam Era to Medieval Kerala",
    year_start: -300,
    year_end: 1102,
    period_label: "300 BCE – 1102 CE",
    period_label_fi: "300 eaa. – 1102 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Chera_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Chera-dynastia",
    wikidata_id: "Q216345",
    summary_en: "Major ancient South Indian dynasty controlling the Malabar Coast of modern Kerala, controlling spice trade routes connecting India with Greco-Roman Alexandria and the Middle East through ports like Muziris.",
    summary_fi: "Merkittävä eteläintialainen dynastia Keralan Malabarrannikolla, joka hallitsi tuottoisaa maustekauppaa Rooman valtakunnan ja Lähi-idän kanssa satamakaupunkinsa Muziriksen kautta.",
    capital: "Vanchi, Mahodayapuram, Karur",
    feature_name_matches: ["Cheras"]
  },
  {
    slug: "gupta-empire",
    name: "Gupta Empire",
    name_fi: "Gupta-valtakunta",
    native_name: "गुप्त साम्राज्य",
    alternate_names: ["Golden Age of India", "Guptas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Classical Golden Age",
    year_start: 319,
    year_end: 550,
    period_label: "319 CE – 550 CE",
    period_label_fi: "319 jaa. – 550 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gupta_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gupta-valtakunta",
    wikidata_id: "Q11774",
    summary_en: "Ancient Indian empire that presided over India's classical Golden Age, marked by peace, prosperity, and breakthroughs in mathematics (zero and decimal system by Aryabhata), astronomy, Sanskrit drama, and sculpture.",
    summary_fi: "Pohjois-Intian klassisen kultakauden imperiumi, jonka aikana saavutettiin vallankumouksellisia edistysaskeleita matematiikassa (nolla ja desimaalijärjestelmä), tähtitieteessä ja sanskritinkielisessä kirjallisuudessa.",
    capital: "Pataliputra, Ujjain",
    feature_name_matches: ["Gupta Empire"]
  },
  {
    slug: "vakataka-dynasty",
    name: "Vakataka Dynasty",
    name_fi: "Vakataka-dynastia",
    native_name: "वाकाटक",
    alternate_names: ["Vakatakas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Classical Central India",
    year_start: 250,
    year_end: 500,
    period_label: "250 CE – 500 CE",
    period_label_fi: "250 jaa. – 500 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Vakataka_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Vakataka-dynastia",
    wikidata_id: "Q1263004",
    summary_en: "Ruling dynasty of the Deccan contemporary with the Guptas, renowned for patronizing the rock-cut Buddhist temples and magnificent painted frescoes at Ajanta.",
    summary_fi: "Deccanin ylängön hallitsijasuku, joka hallitsi samaan aikaan kuin Guptat ja tunnetaan erityisesti Ajantan upeiden kalliomaalausten ja luolaluostareiden suojelijana.",
    capital: "Vatsagulma, Pravarapura",
    feature_name_matches: ["Vakataka"]
  },
  {
    slug: "pallava-dynasty",
    name: "Pallava Dynasty",
    name_fi: "Pallava-dynastia",
    native_name: "பல்லவர்",
    alternate_names: ["Pallavas", "Pallava Empire"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Medieval South India",
    year_start: 275,
    year_end: 897,
    period_label: "275 CE – 897 CE",
    period_label_fi: "275 jaa. – 897 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Pallava_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pallava-dynastia",
    wikidata_id: "Q217277",
    summary_en: "Prominent South Indian kingdom ruling northern Tamil Nadu and southern Andhra Pradesh, celebrated for pioneer Dravidian architecture including the monolithic rock temples at Mamallapuram and the Shore Temple.",
    summary_fi: "Merkittävä eteläintialainen kuningaskunta Kanchipuramissa, joka tunnetaan dravidalaisen kiviarkkitehtuurin uranuurtajana ja Mamallapuramin rantatemppelin rakennuttajana.",
    capital: "Kanchipuram",
    feature_name_matches: ["Pallava", "Pallava state", "Pallavas"]
  },
  {
    slug: "chalukya-dynasty",
    name: "Chalukya Dynasty",
    name_fi: "Chalukya-dynastia",
    native_name: "ಚಾಲುಕ್ಯರು",
    alternate_names: ["Badami Chalukyas", "Chalukya Empire", "Western Chalukyas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Classical to Medieval Deccan",
    year_start: 543,
    year_end: 1189,
    period_label: "543 CE – 1189 CE",
    period_label_fi: "543 jaa. – 1189 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Chalukya_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Chalukya-dynastia",
    wikidata_id: "Q144766",
    summary_en: "Powerful dynasty ruling large areas of southern and central India from Badami and later Kalyani, famous for blending northern Nagara and southern Dravida architectural styles at Aihole, Badami, and Pattadakal.",
    summary_fi: "Voimakas dynastia Keski- ja Etelä-Intiassa, joka hallitsi Badamista ja myöhemmin Kalyānista käsin ja yhdisti pohjoisen ja etelän arkkitehtuurityylejä Pattadakalin ja Aiholen temppeleissä.",
    capital: "Badami, Kalyani",
    feature_name_matches: ["Chalukya Empire", "Chalukyas", "Western Chalukyas"]
  },
  {
    slug: "rashtrakuta-dynasty",
    name: "Rashtrakuta Dynasty",
    name_fi: "Rashtrakuta-dynastia",
    native_name: "ರಾಷ್ಟ್ರಕೂಟರು",
    alternate_names: ["Rashtrakutas", "Rashtrakuta Empire"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Medieval India",
    year_start: 753,
    year_end: 982,
    period_label: "753 CE – 982 CE",
    period_label_fi: "753 jaa. – 982 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Rashtrakuta_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Rashtrakutat",
    wikidata_id: "Q503412",
    summary_en: "Imperial royal dynasty ruling vast swathes of the Indian subcontinent from Manyakheta, celebrated for commissioning the monolithic Kailash rock temple at Ellora and fostering Kannada and Sanskrit literature.",
    summary_fi: "Laajaa Intian aluetta hallinnut keisarillinen dynastia Manyakhetasta käsin, joka rakennutti uskomattoman kalliosta veistetyn Kailash-temppelin Ellorassa.",
    capital: "Manyakheta (Malkhed)",
    feature_name_matches: ["Rashtrakuta", "Rashtrakuta state"]
  },
  {
    slug: "pala-empire",
    name: "Pala Empire",
    name_fi: "Pala-valtakunta",
    native_name: "পাল সাম্রাজ্য",
    alternate_names: ["Palas of Bengal", "Pala Dynasty"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Post-Classical Bengal & Bihar",
    year_start: 750,
    year_end: 1161,
    period_label: "750 CE – 1161 CE",
    period_label_fi: "750 jaa. – 1161 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Pala_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pala-valtakunta",
    wikidata_id: "Q234009",
    summary_en: "Buddhist imperial power originating in Bengal and Bihar that patronized major Mahayana monastic universities including Nalanda and Vikramashila, establishing enduring links with Tibet and Southeast Asia.",
    summary_fi: "Bengalista ja Biharista lähtöisin ollut buddhalainen keisarikunta, joka suojeli ja kehitti Nalandan ja Vikramashilan suuria luostariyliopistoja.",
    capital: "Pataliputra, Gauda, Bikrampur",
    feature_name_matches: ["Palas"]
  },
  {
    slug: "gurjara-pratihara-dynasty",
    name: "Gurjara-Pratihara Dynasty",
    name_fi: "Gurjara-Pratihara",
    native_name: "प्रतिहार",
    alternate_names: ["Pratiharas", "Imperial Pratiharas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Medieval Northern India",
    year_start: 730,
    year_end: 1036,
    period_label: "730 CE – 1036 CE",
    period_label_fi: "730 jaa. – 1036 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gurjara-Pratihara_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Gurjara-Pratihara",
    wikidata_id: "Q845558",
    summary_en: "Imperial power ruling northern India from Kannauj that successfully checked early Arab eastward expansion from Sindh and patronized ornate temple sculptures and Open-pavilion architecture.",
    summary_fi: "Pohjois-Intiaa Kannaujista hallinnut dynastia, joka torjui varhaiset arabivalloitusyritykset idässä ja suojeli kukoistavaa intialaista temppeliarkkitehtuuria.",
    capital: "Kannauj",
    feature_name_matches: ["Gurjara Pratihara", "Pratiharas"]
  },
  {
    slug: "kadamba-dynasty",
    name: "Kadamba Dynasty",
    name_fi: "Kadamba-dynastia",
    native_name: "ಕದಂಬರು",
    alternate_names: ["Kadambas of Banavasi"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Medieval Karnataka",
    year_start: 345,
    year_end: 525,
    period_label: "345 CE – 525 CE",
    period_label_fi: "345 jaa. – 525 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kadamba_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kadamba-dynastia",
    wikidata_id: "Q641019",
    summary_en: "Ancient royal family of Karnataka founded by Mayurasharma at Banavasi that was among the first indigenous kingdoms to use Kannada as an official administrative language alongside Sanskrit.",
    summary_fi: "Karnatakan muinainen kuningaskunta Banavasissa, joka otti ensimmäisten joukossa kannadan kielen viralliseksi hallintokieleksi sanskritin rinnalle.",
    capital: "Banavasi",
    feature_name_matches: ["Kadambas"]
  },
  {
    slug: "western-ganga-dynasty",
    name: "Western Ganga Dynasty",
    name_fi: "Länsi-Ganga-dynastia",
    native_name: "ಪಶ್ಚಿಮ ಗಂಗರು",
    alternate_names: ["Western Gangas"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early to High Medieval Karnataka",
    year_start: 350,
    year_end: 1000,
    period_label: "350 CE – 1000 CE",
    period_label_fi: "350 jaa. – 1000 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Western_Ganga_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/L%C3%A4nsi-Ganga-dynastia",
    wikidata_id: "Q2044893",
    summary_en: "Important ruling dynasty of southern Karnataka that patronized Jainism and commissioned the colossal monolithic statue of Gommateshwara (Bahubali) at Shravanabelagola in 981 CE.",
    summary_fi: "Etelä-Karnatakan hallitsijasuku, joka tuki jainalaisuutta ja pystytti Shravanabelagolan jättimäisen monoliittisen Gommateshwaran patsaan vuonna 981 jaa.",
    capital: "Kolar, Talakad",
    feature_name_matches: ["Western Gangas"]
  },
  {
    slug: "maitraka-kingdom",
    name: "Maitraka Dynasty",
    name_fi: "Maitraka-dynastia",
    native_name: "मैत्रक",
    alternate_names: ["Maitrakas of Vallabhi"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Classical to Post-Gupta Gujarat",
    year_start: 475,
    year_end: 776,
    period_label: "475 CE – 776 CE",
    period_label_fi: "475 jaa. – 776 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Maitraka_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Maitraka-dynastia",
    wikidata_id: "Q2346747",
    summary_en: "Dynasty ruling Saurashtra and Gujarat from their capital Vallabhi, which flourished as an internationally renowned center of Buddhist learning and Jain canon compilation.",
    summary_fi: "Gujaratin ja Saurashtran aluetta hallinnut dynastia Vallabhista käsin, joka toimi merkittävänä kansainvälisenä buddhalaisen oppineisuuden ja jainalaisen kirjallisuuden keskuksena.",
    capital: "Vallabhi",
    feature_name_matches: ["Maitraka Kingdom"]
  },
  {
    slug: "solanki-dynasty",
    name: "Chaulukya Dynasty of Gujarat",
    name_fi: "Solanki-dynastia",
    native_name: "ચૌલુક્ય",
    alternate_names: ["Solankis", "Chaulukyas of Gujarat"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "High Medieval Gujarat",
    year_start: 940,
    year_end: 1244,
    period_label: "940 CE – 1244 CE",
    period_label_fi: "940 jaa. – 1244 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Chaulukya_dynasty",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Chaulukya-dynastia",
    wikidata_id: "Q1257404",
    summary_en: "Rajput dynasty ruling Gujarat and parts of Rajasthan from Anhilwad Patan, celebrated for the Sun Temple at Modhera and the UNESCO World Heritage stepwell Rani ki Vav.",
    summary_fi: "Gujaratin ja Rajasthanin rajaseutuja hallinnut rajput-dynastia, joka rakennutti Modheran häikäisevän aurinkotemppelin ja Unescon suojeleman Rani ki Vav -porraskaivon.",
    capital: "Anhilwad Patan",
    feature_name_matches: ["Solankis", "Gujarat"]
  },
  {
    slug: "rajput-kingdoms",
    name: "Rajput Kingdoms",
    name_fi: "Rajput-kuningaskunnat",
    native_name: "राजपूत",
    alternate_names: ["Rajputana", "Rajput Clans"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Medieval to Early Modern India",
    year_start: 600,
    year_end: 1947,
    period_label: "600 CE – 1947 CE",
    period_label_fi: "600 jaa. – 1947 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Rajput",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Rajputit",
    wikidata_id: "Q207908",
    summary_en: "Confederation of martial Hindu clans ruling princely states across Rajasthan, Saurashtra, and central India, renowned for chivalric warrior codes and hilltop fortresses like Chittorgarh and Mehrangarh.",
    summary_fi: "Rajasthanin ja Keski-Intian soturiklaanien hallitsemat ruhtinaskunnat, jotka tunnetaan ritarillisista ihanteistaan ja massiivisista linnoituksistaan kuten Chittorgarhista ja Mehrangarhista.",
    capital: "Chittorgarh, Udaipur, Jodhpur, Jaipur",
    feature_name_matches: ["Rajput Clans and Small States", "Rajput kingdoms", "Rajputana", "Rajputs"]
  },
  {
    slug: "kashmir-kingdom",
    name: "Kingdom of Kashmir",
    name_fi: "Kashmirin kuningaskunta",
    native_name: "कश्मीरा",
    alternate_names: ["Karkota Dynasty", "Utpala Dynasty", "Kashmir and Ladakh"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Medieval Kashmir",
    year_start: 625,
    year_end: 1339,
    period_label: "625 CE – 1339 CE",
    period_label_fi: "625 jaa. – 1339 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Karkota_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kashmirin_historia",
    wikidata_id: "Q2988188",
    summary_en: "Himalayan valley kingdom rising to regional imperial prominence under Lalitaditya Muktapida of the Karkota dynasty, renowned for Martand Sun Temple, Sanskrit poetics, and Kashmir Shaivism.",
    summary_fi: "Himalajan laaksokuningaskunta, joka nousi huomattavaksi imperiumiksi Karkota-dynastian Lalitadityan johdolla ja kukoisti sanskritinkielisen filosofian ja shaivismin keskuksena.",
    capital: "Srinagar, Parihaspore",
    feature_name_matches: ["Kingdom of Kashmir", "Kashmir and Ladakh"]
  },
  {
    slug: "hindu-kingdoms-and-republics",
    name: "Classical & Medieval Hindu Kingdoms",
    name_fi: "Intialaiset hindukuningaskunnat",
    native_name: "साम्राज्य (Sāmrājya)",
    alternate_names: ["Hindu Republics", "Janapadas", "Minor Hindu Kingdoms"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Ancient to Early Modern Subcontinent",
    year_start: -600,
    year_end: 1800,
    period_label: "600 BCE – 1800 CE",
    period_label_fi: "600 eaa. – 1800 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/History_of_India",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Intian_historia",
    wikidata_id: "Q668",
    summary_en: "Various independent regional polities, city-states, and oligarchic republics across South Asia that preserved Sanskrit learning, temple worship, and autonomous rural institutions across changing eras.",
    summary_fi: "Itsenäiset alueelliset hindulaiset kaupunkivaltiot, ruhtinaskunnat ja tasavallat eri puolilla Intian niemimaata, jotka ylläpitivät perinteistä sanskritilaista sivistystä ja temppelikulttuuria.",
    capital: "Various regional capitals",
    feature_name_matches: ["Hindu kingdoms", "Hindu kingdoms and republics", "minor Hindu kingdoms"]
  },
  {
    slug: "kushan-principalities",
    name: "Kushan Principalities",
    name_fi: "Kušano-sasanidit ja kušaniruhtinaskunnat",
    native_name: "Kushanashahr",
    alternate_names: ["Kidarites", "Kushano-Sasanians"],
    culture_group: "South Asia",
    lineage_id: "kushan",
    historical_period: "Late Antiquity Northwest India",
    year_start: 230,
    year_end: 450,
    period_label: "230 CE – 450 CE",
    period_label_fi: "230 jaa. – 450 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kushano-Sasanian_Kingdom",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kushan-valtakunta",
    wikidata_id: "Q1417070",
    summary_en: "Successor rump states and cadet branches of the Kushan Empire in Gandhara and northern Punjab that retained Greco-Buddhist artistic traditions and issued distinctive coinage.",
    summary_fi: "Kušan-valtakunnan seuraajavaltiot Gandharassa ja Punjabissa, jotka säilyttivät kreikkalais-buddhalaiset taideperinteet ja oman kolikkokantansa myöhäisantiikissa.",
    capital: "Peshawar, Taxila",
    feature_name_matches: ["Kushan Principalities"]
  },
  {
    slug: "orissa-gajapati",
    name: "Gajapati Kingdom of Orissa",
    name_fi: "Gajapati-kuningaskunta",
    native_name: "ଗଜପତି ସାମ୍ରାଜ୍ୟ",
    alternate_names: ["Orissa", "Eastern Gangas", "Suryavamsi Gajapatis"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Medieval to Early Modern East India",
    year_start: 1078,
    year_end: 1541,
    period_label: "1078 CE – 1541 CE",
    period_label_fi: "1078 jaa. – 1541 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Gajapati_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Odisha",
    wikidata_id: "Q2995392",
    summary_en: "Medieval Hindu empire ruling coastal Odisha and surrounding regions, famed as master builders of monumental temples including Jagannath Temple in Puri and the Sun Temple at Konark.",
    summary_fi: "Odishan rannikkoa hallinnut keskiaikainen hindulainen kuningaskunta, joka tunnetaan Purin Jagannath-temppelin ja Konarakin aurinkotemppelin rakennuttajana.",
    capital: "Cuttack",
    feature_name_matches: ["Orissa"]
  },
  {
    slug: "delhi-sultanate",
    name: "Delhi Sultanate",
    name_fi: "Delhin sulttaanikunta",
    native_name: "سلطنت دهلی",
    alternate_names: ["Sultanate of Delhi", "Mamluk / Khalji / Tughlaq / Sayyid / Lodi dynasties"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Medieval Islamic India",
    year_start: 1206,
    year_end: 1526,
    period_label: "1206 CE – 1526 CE",
    period_label_fi: "1206 jaa. – 1526 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Delhi_Sultanate",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Delhin_sulttaanikunta",
    wikidata_id: "Q229411",
    summary_en: "Islamic empire based in Delhi stretching over large parts of the Indian subcontinent, ruled successively by five Turkic and Afghan dynasties until superseded by Babur's Mughal conquest.",
    summary_fi: "Delhistä käsin hallittu islamilainen valtakunta, jota johti peräkkäin viisi turkkilais- ja afgaanitaustaista dynastiaa ja joka toi indoislamilaisen arkkitehtuurin Intiaan.",
    capital: "Delhi, Daulatabad",
    feature_name_matches: ["Sultanate of Delhi"]
  },
  {
    slug: "vijayanagara-empire",
    name: "Vijayanagara Empire",
    name_fi: "Vijayanagaran valtakunta",
    native_name: "ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯ",
    alternate_names: ["Karnata Empire", "Vijayanagara"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Late Medieval South India",
    year_start: 1336,
    year_end: 1646,
    period_label: "1336 CE – 1646 CE",
    period_label_fi: "1336 jaa. – 1646 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Vijayanagara_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Vijayanagara",
    wikidata_id: "Q167639",
    summary_en: "South Indian Hindu empire based at Hampi on the Tungabhadra River that successfully resisted northern sultanate advances for three centuries, fostering vibrant temple architecture, poetry, and trade.",
    summary_fi: "Etelä-Intian mahtava hindulainen imperiumi Hampissa, joka suojeli etelän kulttuuriperintöä kolmen vuosisadan ajan ja kävi vilkasta kansainvälistä kauppaa.",
    capital: "Vijayanagara (Hampi), Penukonda, Chandragiri",
    feature_name_matches: ["Vijayanagara"]
  },
  {
    slug: "bahmani-sultanate",
    name: "Bahmani Sultanate",
    name_fi: "Bahmanin sulttaanikunta",
    native_name: "بهمنیان",
    alternate_names: ["Bahmani Kingdom"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Late Medieval Deccan",
    year_start: 1347,
    year_end: 1527,
    period_label: "1347 CE – 1527 CE",
    period_label_fi: "1347 jaa. – 1527 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Bahmani_Sultanate",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bahmanin_sulttaanikunta",
    wikidata_id: "Q733796",
    summary_en: "First independent Muslim kingdom of the Deccan, founded by Ala-ud-Din Bahman Shah after revolting against the Delhi Sultanate, later splintering into the five Deccan Sultanates.",
    summary_fi: "Ensimmäinen itsenäinen Deccanin islamilainen kuningaskunta, jonka perusti Ala-ud-Din Bahman Shah kapinoituaan Delhin sulttaania vastaan ja joka hajosi viideksi sulttaanikunnaksi.",
    capital: "Gulbarga, Bidar",
    feature_name_matches: ["Bahmani Kingdom"]
  },
  {
    slug: "deccan-sultanates",
    name: "Deccan Sultanates",
    name_fi: "Deccanin sulttaanikunnat",
    native_name: "دکنی سلطنتیں",
    alternate_names: ["Bijapur", "Golconda", "Ahmadnagar", "Bidar", "Berar"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Modern Deccan",
    year_start: 1490,
    year_end: 1687,
    period_label: "1490 CE – 1687 CE",
    period_label_fi: "1490 jaa. – 1687 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Deccan_sultanates",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Deccanin_sulttaanikunnat",
    wikidata_id: "Q641328",
    summary_en: "Five late medieval Muslim dynasties—Ahmadnagar, Berar, Bidar, Bijapur, and Golconda—ruling the Deccan Plateau, famed for exquisite Deccani miniature paintings, Gol Gumbaz dome architecture, and diamond trade.",
    summary_fi: "Viisi Deccanin ylängön islamilaista sulttaanikuntaa (Bijapur, Golkonda, Ahmadnagar, Bidar ja Berar), jotka tunnetaan Deccanin miniatyyritaiteesta ja Golkondan timanteista.",
    capital: "Bijapur, Golconda, Ahmadnagar, Bidar, Ellichpur",
    feature_name_matches: ["Ahmadnagar", "Berar", "Bidar", "Bijapur", "Golconda"]
  },
  {
    slug: "sindh-kingdoms",
    name: "Sindh Dynasties",
    name_fi: "Sindhin dynastiat",
    native_name: "سنڌ",
    alternate_names: ["Soomra Dynasty", "Samma Dynasty", "Talpur Dynasty", "Sindh"],
    culture_group: "South Asia",
    lineage_id: "pakistan",
    historical_period: "Medieval to Early Modern Sindh",
    year_start: 1026,
    year_end: 1843,
    period_label: "1026 CE – 1843 CE",
    period_label_fi: "1026 jaa. – 1843 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sindh#History",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sindh",
    wikidata_id: "Q37211",
    summary_en: "Indigenous Muslim dynasties of the lower Indus valley that governed Sindh through the Soomra, Samma, and Talpur eras, known for Sufi poetry and the Makli Necropolis at Thatta.",
    summary_fi: "Alisen Induksen laakson paikalliset dynastiat Sindhissä, jotka vaalivat suufilaista runoutta ja rakensivat Thattan massiivisen Maklin hautakaupungin.",
    capital: "Thatta, Hyderabad (Sindh)",
    feature_name_matches: ["Sindh"]
  },
  {
    slug: "mughal-empire",
    name: "Mughal Empire",
    name_fi: "Suurmogulien valtakunta",
    native_name: "مغل بادشاھی",
    alternate_names: ["Moghul Empire", "Gurkani"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Modern Imperial India",
    year_start: 1526,
    year_end: 1857,
    period_label: "1526 CE – 1857 CE",
    period_label_fi: "1526 jaa. – 1857 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Mughal_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Suurmogulien_valtakunta",
    wikidata_id: "Q33296",
    summary_en: "Early modern Turco-Mongol Islamic empire founded by Babur that unified nearly all of South Asia under Akbar and Aurangzeb, leaving monuments including the Taj Mahal and Red Fort.",
    summary_fi: "Turkkilais-mongolilainen keisarikunta Intiassa, jonka Babur perusti vuonna 1526 ja joka loi loisteliasta taidetta ja arkkitehtuuria kuten Taj Mahalin ja Punaisen linnoituksen.",
    capital: "Agra, Delhi, Fatehpur Sikri, Lahore",
    feature_name_matches: ["Mughal Empire"]
  },
  {
    slug: "maratha-empire",
    name: "Maratha Empire",
    name_fi: "Marattivaltakunta",
    native_name: "मराठा साम्राज्य",
    alternate_names: ["Maratha Confederacy", "Maratha"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Modern India",
    year_start: 1674,
    year_end: 1818,
    period_label: "1674 CE – 1818 CE",
    period_label_fi: "1674 jaa. – 1818 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Maratha_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Marattivaltakunta",
    wikidata_id: "Q83618",
    summary_en: "Hindu confederacy founded by Chhatrapati Shivaji Maharaj that challenged and dismantled Mughal dominance, becoming the preeminent power in 18th-century India until British conquest.",
    summary_fi: "Shivajin perustama marattien hindulainen valtakunta ja konfederaatio, joka syrjäytti suurmogulit 1700-luvulla ja nousi Intian niemimaan mahtavimmaksi voimaksi.",
    capital: "Raigad, Pune, Satara",
    feature_name_matches: ["Maratha", "Maratha Confederacy"]
  },
  {
    slug: "sikh-empire",
    name: "Sikh Empire",
    name_fi: "Sikhivaltakunta",
    native_name: "ਸਿੱਖ ਸਲਤਨਤ",
    alternate_names: ["Sikh Confederacy", "Sikhs", "Punjab"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Modern Punjab",
    year_start: 1799,
    year_end: 1849,
    period_label: "1799 CE – 1849 CE",
    period_label_fi: "1799 jaa. – 1849 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Sikh_Empire",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sikhivaltio",
    wikidata_id: "Q846295",
    summary_en: "Secular sovereign empire in the Punjab region forged by Maharaja Ranjit Singh, known for its modernized Fauj-i-Khas army, religious pluralism, and protection of the Harmandir Sahib (Golden Temple).",
    summary_fi: "Maharadža Ranjit Singhin Punjabiin perustama sikhivaltio, joka nojasi modernisoituun armeijaan ja uskonnolliseen suvaitsevaisuuteen ennen joutumistaan Britannian alaisuuteen.",
    capital: "Lahore, Amritsar",
    feature_name_matches: ["Sikhs", "Punjab"]
  },
  {
    slug: "kingdom-of-mysore",
    name: "Kingdom of Mysore",
    name_fi: "Mysoren kuningaskunta",
    native_name: "ಮೈಸೂರು ಸಂಸ್ಥಾನ",
    alternate_names: ["Mysore (Indian princely state)", "Mysore"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Modern to Princely State",
    year_start: 1399,
    year_end: 1950,
    period_label: "1399 CE – 1950 CE",
    period_label_fi: "1399 jaa. – 1950 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Mysore",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Mysoren_kuningaskunta",
    wikidata_id: "Q262081",
    summary_en: "Prominent realm in southern Karnataka ruled by the Wadiyar dynasty and under Hyder Ali and Tipu Sultan, who pioneered iron-cased Mysorean rockets in wars against the British East India Company.",
    summary_fi: "Etelä-Karnatakan valtakunta, jota hallitsivat Wadiyar-dynastia sekä Hyder Ali ja Tipu Sultan, jotka kehittivät rautakuorisia rakettiaseita taisteluissa brittejä vastaan.",
    capital: "Mysore, Srirangapatna",
    feature_name_matches: ["Mysore", "Mysore (Indian princely state)"]
  },
  {
    slug: "hyderabad-state",
    name: "Hyderabad State",
    name_fi: "Hyderabadin valtio",
    native_name: "حیدرآباد",
    alternate_names: ["Nizam's Dominions", "Dominions of the Nizam"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Modern to Princely State",
    year_start: 1724,
    year_end: 1948,
    period_label: "1724 CE – 1948 CE",
    period_label_fi: "1724 jaa. – 1948 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Hyderabad_State",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Hyderabad_(ruhtinaskunta)",
    wikidata_id: "Q1248067",
    summary_en: "Largest and wealthiest princely state in British India, founded by Nizam-ul-Mulk Asaf Jah I, controlling central Deccan territory and rich diamond mines until integrated into India in 1948.",
    summary_fi: "Brittiläisen Intian suurin ja vaurain ruhtinaskunta Deccanin ylängöllä, jota hallitsi nizami aina vuoden 1948 Intiaan liittämiseen saakka.",
    capital: "Hyderabad",
    feature_name_matches: ["Nizam's Dominions"]
  },
  {
    slug: "travancore-kingdom",
    name: "Kingdom of Travancore",
    name_fi: "Travancoren kuningaskunta",
    native_name: "തിരുവിതാംകൂർ",
    alternate_names: ["Thiruvithamkoor", "Travancore"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Early Modern Kerala",
    year_start: 1729,
    year_end: 1949,
    period_label: "1729 CE – 1949 CE",
    period_label_fi: "1729 jaa. – 1949 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Travancore",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Travancore",
    wikidata_id: "Q1337965",
    summary_en: "Southern coastal kingdom in modern Kerala founded by Marthanda Varma, renowned for defeating the Dutch East India Company at the Battle of Colachel in 1741 and patronizing the Padmanabhaswamy Temple.",
    summary_fi: "Etelä-Keralan kuningaskunta, joka voitti Hollannin Itä-Intian kauppakomppanian Colachelin taistelussa 1741 ja tuki Padmanabhaswamyn rikasta temppeliä.",
    capital: "Padmanabhapuram, Thiruvananthapuram",
    feature_name_matches: ["Travancore"]
  },
  {
    slug: "cochin-kingdom",
    name: "Kingdom of Cochin",
    name_fi: "Cochinin kuningaskunta",
    native_name: "കൊച്ചി രാജ്യം",
    alternate_names: ["Perumpadappu Swaroopam", "Cochin"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Late Medieval to Modern Kerala",
    year_start: 1102,
    year_end: 1949,
    period_label: "1102 CE – 1949 CE",
    period_label_fi: "1102 jaa. – 1949 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Cochin",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Kochi_(Intia)",
    wikidata_id: "Q889158",
    summary_en: "Historic coastal kingdom on the Arabian Sea centered at the spice port of Kochi, welcoming Saint Thomas Christians, Cochin Jews, and becoming Portugal's first European settlement in India in 1500.",
    summary_fi: "Arabianmeren rannikkovaltakunta Keralassa, jonka pääsatama Kochi toimi maustekaupan solmukohtana ja Portugalin ensimmäisenä tukikohtana Intiassa.",
    capital: "Kochi, Tripunithura",
    feature_name_matches: ["Cochin"]
  },
  {
    slug: "sri-lanka-kingdoms",
    name: "Sinhalese Kingdoms of Sri Lanka",
    name_fi: "Sri Lankan singaleesikuningaskunnat",
    native_name: "ශ්‍රී ලංකා",
    alternate_names: ["Ceylon", "Ceylon (Dutch)", "Simhala", "Kandy", "Sri Lanka"],
    culture_group: "South Asia",
    lineage_id: "sri-lanka",
    historical_period: "Ancient to Modern Sri Lanka",
    year_start: -543,
    year_end: 2026,
    period_label: "543 BCE – Present",
    period_label_fi: "543 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/History_of_Sri_Lanka",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sri_Lankan_historia",
    wikidata_id: "Q854",
    summary_en: "Continuous Buddhist island civilization of Sri Lanka spanning the Anuradhapura, Polonnaruwa, and Kandy kingdoms, renowned for hydraulic reservoir engineering and veneration of the Sacred Tooth Relic.",
    summary_fi: "Sri Lankan vuosituhantinen singaleesilainen buddhalainen saarikulttuuri, joka ulottui Anuradhapuran ja Polonnaruwan kuningaskunnista Kandyn valtakuntaan ja nykyaikaan.",
    capital: "Anuradhapura, Polonnaruwa, Kandy, Colombo",
    feature_name_matches: ["Ceylon", "Ceylon (Dutch)", "Kandy", "Simhala", "Sri Lanka"]
  },
  {
    slug: "nepal-kingdom",
    name: "Kingdom of Nepal",
    name_fi: "Nepalin kuningaskunta",
    native_name: "नेपाल अधिराज्य",
    alternate_names: ["Gorkha Kingdom", "Nepal"],
    culture_group: "South Asia",
    lineage_id: "nepal",
    historical_period: "Ancient to Modern Himalayas",
    year_start: -500,
    year_end: 2026,
    period_label: "500 BCE – Present",
    period_label_fi: "500 eaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Nepal",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Nepal",
    wikidata_id: "Q837",
    summary_en: "Himalayan kingdom encompassing the Kathmandu Valley civilizations (Licchavis, Mallas) and unified by Prithvi Narayan Shah of Gorkha in 1768, famous for Newar craftsmanship, Gurkha warriors, and Mount Everest.",
    summary_fi: "Himalajan vuoristovaltakunta, jonka Katmandun laakson Licchavi- ja Malla-kuningaskunnat yhdistettiin Gorkhan Prithvi Narayan Shahin johdolla vuonna 1768.",
    capital: "Kathmandu",
    feature_name_matches: ["Nepal"]
  },
  {
    slug: "bhutan-kingdom",
    name: "Kingdom of Bhutan",
    name_fi: "Bhutanin kuningaskunta",
    native_name: "འབྲུག་ཡུལ་ (Druk Yul)",
    alternate_names: ["Druk Yul", "Bhutan"],
    culture_group: "South Asia",
    lineage_id: "bhutan",
    historical_period: "Tibetan Buddhist Himalayan Realm",
    year_start: 747,
    year_end: 2026,
    period_label: "747 CE – Present",
    period_label_fi: "747 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/History_of_Bhutan",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bhutan",
    wikidata_id: "Q917",
    summary_en: "Sovereign Himalayan Buddhist nation unified by Ngawang Namgyal in the 17th century through a network of fortified monasteries (dzongs), preserving Drukpa Kagyu traditions and Gross National Happiness.",
    summary_fi: "Himalajan tiibetinbuddhalainen kuningaskunta, jonka Ngawang Namgyal yhdisti 1600-luvulla linnoitettujen dzong-luostareiden verkostolla ja joka vaalii Drukpa Kagyu -perinteitä.",
    capital: "Thimphu, Punakha",
    feature_name_matches: ["Bhutan"]
  },
  {
    slug: "sikkim-kingdom",
    name: "Kingdom of Sikkim",
    name_fi: "Sikkimin kuningaskunta",
    native_name: "འབྲས་ལྗོངས། (Drenjong)",
    alternate_names: ["Chogyals of Sikkim", "Sikkim (Indian princely state)"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Himalayan Buddhist Monarchy",
    year_start: 1642,
    year_end: 1975,
    period_label: "1642 CE – 1975 CE",
    period_label_fi: "1642 jaa. – 1975 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Kingdom_of_Sikkim",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sikkim",
    wikidata_id: "Q1397",
    summary_en: "Himalayan Buddhist monarchy founded by Phuntsog Namgyal as the first Chogyal in 1642, retaining independence in the shadow of Kangchenjunga until joining the Indian Union in 1975.",
    summary_fi: "Himalajalla sijainnut buddhalainen kuningaskunta Kangchenjungan rinteillä, jota hallitsivat Chogyal-kuninkaat aina vuoden 1975 Intiaan liittymiseen asti.",
    capital: "Yuksom, Rabdentse, Tumlong, Gangtok",
    feature_name_matches: ["Sikkim (Indian princely state)"]
  },
  {
    slug: "republic-of-india",
    name: "Republic of India",
    name_fi: "Intian tasavalta",
    native_name: "भारत गणराज्य (Bhārat Gaṇarājya)",
    alternate_names: ["India", "Union of India"],
    culture_group: "South Asia",
    lineage_id: "india",
    historical_period: "Modern Sovereign Nation",
    year_start: 1947,
    year_end: 2026,
    period_label: "1947 CE – Present",
    period_label_fi: "1947 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/India",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Intia",
    wikidata_id: "Q668",
    summary_en: "World's most populous constitutional democracy occupying the greater part of South Asia, achieving independence from British rule in 1947 under Mahatma Gandhi and Jawaharlal Nehru.",
    summary_fi: "Maailman väkirikkain demokraattinen valtio Etelä-Aasiassa, joka saavutti itsenäisyyden Britannian siirtomaavallasta vuonna 1947 Mahatma Gandhin ja Jawaharlal Nehrun johdolla.",
    capital: "New Delhi",
    feature_name_matches: ["India"]
  },
  {
    slug: "islamic-republic-of-pakistan",
    name: "Islamic Republic of Pakistan",
    name_fi: "Pakistanin islamilainen tasavalta",
    native_name: "اسلامی جمہوریہ پاکستان",
    alternate_names: ["Pakistan"],
    culture_group: "South Asia",
    lineage_id: "pakistan",
    historical_period: "Modern Sovereign Nation",
    year_start: 1947,
    year_end: 2026,
    period_label: "1947 CE – Present",
    period_label_fi: "1947 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Pakistan",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pakistan",
    wikidata_id: "Q843",
    summary_en: "South Asian sovereign nation founded by Muhammad Ali Jinnah as a homeland for Muslims of the British Raj in 1947, spanning the Indus River basin from the Arabian Sea to the Karakoram mountains.",
    summary_fi: "Etelä-Aasian valtio, jonka Muhammad Ali Jinnah perusti vuonna 1947 brittiläisen Intian muslimeille ja joka käsittää Indus-joen laakson Arabianmereltä Karakorumin vuorille.",
    capital: "Islamabad, Karachi",
    feature_name_matches: ["Pakistan"]
  },
  {
    slug: "peoples-republic-of-bangladesh",
    name: "People's Republic of Bangladesh",
    name_fi: "Bangladeshin kansantasavalta",
    native_name: "গণপ্রজাতন্ত্রী বাংলাদেশ",
    alternate_names: ["Bangladesh", "East Pakistan"],
    culture_group: "South Asia",
    lineage_id: "bangladesh",
    historical_period: "Modern Sovereign Nation",
    year_start: 1971,
    year_end: 2026,
    period_label: "1971 CE – Present",
    period_label_fi: "1971 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Bangladesh",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Bangladesh",
    wikidata_id: "Q902",
    summary_en: "Deltaic nation on the Bay of Bengal that won independence from Pakistan in the 1971 Liberation War under Sheikh Mujibur Rahman, home to rich Bengali literature, music, and the Sundarbans mangrove forest.",
    summary_fi: "Bengalinlahden suistoalueella sijaitseva valtio, joka itsenäistyi Pakistanista vuonna 1971 šeikki Mujibur Rahmanin johdolla ja tunnetaan rikkaasta bengalinkielisestä kulttuuristaan.",
    capital: "Dhaka",
    feature_name_matches: ["Bangladesh"]
  },
  {
    slug: "oklahoma-indigenous-nations",
    name: "Indigenous Nations in Oklahoma",
    name_fi: "Oklahoman alkuperäiskansat",
    alternate_names: ["Otoe-Missouria", "Peoria", "Sac and Fox"],
    culture_group: "South Asia",
    lineage_id: "north-america",
    historical_period: "Indigenous American Peoples",
    year_start: 1000,
    year_end: 2026,
    period_label: "1000 CE – Present",
    period_label_fi: "1000 jaa. – nykyaika",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Indigenous_peoples_of_the_Americas",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Intiaanit",
    wikidata_id: "Q36747",
    summary_en: "Native American sovereign nations including the Otoe-Missouria, Peoria, and Sac and Fox peoples, historically relocated to Indian Territory (modern Oklahoma), preserving distinct tribal sovereignty and cultural heritages.",
    summary_fi: "Pohjois-Amerikan alkuperäiskansoja kuten otoe-missouriat, peoriat sekä saukit ja ketut, jotka siirrettiin intiaanialueelle nykyiseen Oklahomaan ja jotka ylläpitävät omaa heimoperinnettään.",
    capital: "Oklahoma",
    feature_name_matches: [
      "Otoe-Missouri (Oklahoma)",
      "Otoe-Missouria (Oklahoma)",
      "Peoria (Oklahoma)",
      "Sac and Fox (Oklahoma)"
    ]
  }
]

const outPath = path.resolve(__dirname, "../data-sources/batches/south-asia.json")
fs.writeFileSync(outPath, JSON.stringify(SOUTH_ASIA_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${SOUTH_ASIA_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(SOUTH_ASIA_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
