import fs from "fs"
import path from "path"
import { CultureBatchEntry } from "./seed_culture_metadata_batch"

const PREHISTORIC_CULTURES: CultureBatchEntry[] = [
  // Hominin Species & Paleolithic Horizons
  {
    slug: "homo-erectus",
    name: "Homo erectus",
    name_fi: "Homo erectus (Pystyihminen)",
    native_name: "Homo erectus",
    alternate_names: ["Homo erectus", "Java Man", "Peking Man"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Early to Middle Pleistocene Hominin Dispersal",
    year_start: -1900000,
    year_end: -108000,
    period_label: "1,900,000 BCE – 108,000 BCE",
    period_label_fi: "1 900 000 eaa. – 108 000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Homo_erectus",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Pystyihminen",
    wikidata_id: "Q101149",
    summary_en: "Pioneering archaic human species that first mastered fire, invented Acheulean bifacial handaxes, and dispersed from Africa across Eurasia into Georgia, China, and Java.",
    summary_fi: "Varhainen ihmislaji, joka ensimmäisenä valjasti tulen käytön, kehitti Acheulin käsikirveet ja levittäytyi Afrikasta Euraasian halki Kaukasukselle, Kiinaan ja Jaavalle.",
    capital: "Lake Turkana, Dmanisi, Zhoukoudian, Sangiran",
    feature_name_matches: ["Homo erectus"]
  },
  {
    slug: "homo-heidelbergensis",
    name: "Homo heidelbergensis",
    name_fi: "Homo heidelbergensis (Heidelberginihminen)",
    native_name: "Homo heidelbergensis",
    alternate_names: ["Homo heidelbergensis", "Rhodesian Man"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Middle Pleistocene Common Ancestor",
    year_start: -600000,
    year_end: -200000,
    period_label: "600,000 BCE – 200,000 BCE",
    period_label_fi: "600 000 eaa. – 200 000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Homo_heidelbergensis",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Heidelberginihminen",
    wikidata_id: "Q105786",
    summary_en: "Middle Pleistocene hominin species ancestral to Neanderthals, Denisovans, and modern humans, noted for large brains, wooden hunting spears (Schöningen spears), and big-game hunting.",
    summary_fi: "Keskipleistoseenin ihmislaji ja neandertalinihmisten, denisovanihmisten ja nykyihmisten yhteinen kantamuoto; tunnettu Schöningenin puukeihäistä ja suurriistan metsästyksestä.",
    capital: "Mauer, Atapuerca (Sima de los Huesos), Schöningen",
    feature_name_matches: ["Homo heidelbergensis"]
  },
  {
    slug: "homo-neanderthalensis",
    name: "Neanderthal (Homo neanderthalensis)",
    name_fi: "Neandertalinihminen",
    native_name: "Homo neanderthalensis",
    alternate_names: ["Neanderthal", "Neanderthals", "Mousterian"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Middle to Upper Paleolithic Western Eurasia",
    year_start: -430000,
    year_end: -40000,
    period_label: "430,000 BCE – 40,000 BCE",
    period_label_fi: "430 000 eaa. – 40 000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Neanderthal",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Neandertalinihminen",
    wikidata_id: "Q40171",
    summary_en: "Robust archaic human lineage adapted to Pleistocene cold climates across Europe and Western Asia, creators of Mousterian stone technology, cave art, personal adornments, and deliberate burials.",
    summary_fi: "Euroopan ja Länsi-Aasian jääkausien kylmään ilmastoon sopeutunut ihmislaji, joka kehitti Moustier-kiviesinekulttuurin, kalliotaidetta ja vainajien rituaalihautauksia.",
    capital: "Neander Valley, Shanidar, Gorham's Cave, Krapina",
    feature_name_matches: ["Neanderthal"]
  },
  {
    slug: "paleolithic-hunter-gatherers",
    name: "Upper Paleolithic Hunter-Gatherer Horizons",
    name_fi: "Yläpaleoliittiset metsästäjä-keräilijät",
    native_name: "Paleolithic Hunter-Gatherers",
    alternate_names: ["Hunters-gatherers", "Upper Paleolithic foragers"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Late Pleistocene Human Expansion",
    year_start: -50000,
    year_end: -10000,
    period_label: "50,000 BCE – 10,000 BCE",
    period_label_fi: "50 000 eaa. – 10 000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Upper_Paleolithic",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/My%C3%B6h%C3%A4ispaleoliittinen_kausi",
    wikidata_id: "Q479495",
    summary_en: "Anatomically modern human societies during the last glacial period who created monumental parietal cave art at Lascaux and Altamira, carved Venus figurines, and tracked megafauna across continents.",
    summary_fi: "Viimeisen jääkauden nykyihmisyhteisöt, jotka loivat Lascaux'n ja Altamiran luolamaalaukset, veistivät Venus-veistoksia ja metsästivät mammutteja ja muuta jääkauden suurriistaa.",
    capital: "Vêzère Valley, Franco-Cantabrian caves",
    feature_name_matches: ["Hunters-gatherers"]
  },

  // Mesolithic Horizons
  {
    slug: "alluvial-lowland-mesolithic-foragers",
    name: "Alluvial Lowland Mesolithic Hunter-Foragers",
    name_fi: "Tulvatasankojen mesoliittiset metsästäjä-keräilijät",
    native_name: "Alluvial Lowland Mesolithic",
    alternate_names: ["Alluvial Lowland Mesolithic Hunter-Foragers"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Early Holocene Riverine Adaptation",
    year_start: -10000,
    year_end: -5000,
    period_label: "10,000 BCE – 5000 BCE",
    period_label_fi: "10 000 eaa. – 5000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Mesolithic",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Mesoliittinen_kausi",
    wikidata_id: "Q44155",
    summary_en: "Post-glacial hunter-gatherer communities inhabiting lowland river deltas, floodplains, and wetland marshes, specializing in weir fishing, waterfowl trapping, and wild plant harvesting.",
    summary_fi: "Jääkauden jälkeiset metsästäjä-keräilijäyhteisöt alavilla jokisuistoilla ja kosteikoilla; erikoistuivat patokalastukseen, vesilintujen pyyntiin ja luonnonkasvien keräilyyn.",
    capital: "Danube, Rhine, and Tigris riverine basins",
    feature_name_matches: ["Alluvial Lowland Mesolithic Hunter-Foragers"]
  },
  {
    slug: "coastal-woodland-mesolithic-foragers",
    name: "Coastal & Woodland Mesolithic Hunter-Foragers",
    name_fi: "Rannikoiden ja lehtimetsien mesoliittiset metsästäjä-keräilijät",
    native_name: "Coastal and Woodland Mesolithic",
    alternate_names: ["Coastal and Woodland Mesolithic Hunter-Foragers"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Early Holocene Maritime-Forest Horizon",
    year_start: -9500,
    year_end: -4500,
    period_label: "9500 BCE – 4500 BCE",
    period_label_fi: "9500 eaa. – 4500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Maglemosian_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Maglemosen_kulttuuri",
    wikidata_id: "Q831518",
    summary_en: "Early Holocene foragers inhabiting temperate coastal margins and mixed deciduous forests, employing microlithic composite arrows, dugout canoes, and hazelnut gathering strategies.",
    summary_fi: "Varhaisen holoseenin rannikoiden ja lehtimetsien asukkaat, jotka käyttivät mikroliittikärkisiä nuolia, ruuhia ja hyödynsivät pähkinäpensaiden satoa ja kalavesiä.",
    capital: "Doggerland and North Sea coastal encampments",
    feature_name_matches: ["Coastal and Woodland Mesolithic Hunter-Foragers"]
  },
  {
    slug: "highland-mesolithic-foragers",
    name: "Highland Mesolithic Hunter-Foragers",
    name_fi: "Ylänköjen mesoliittiset metsästäjä-keräilijät",
    native_name: "Highland Mesolithic",
    alternate_names: ["Highland Mesolithic Hunter-Foragers"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Alpine & Montane Post-Glacial Foragers",
    year_start: -9000,
    year_end: -4000,
    period_label: "9000 BCE – 4000 BCE",
    period_label_fi: "9000 eaa. – 4000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Mesolithic#Europe",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Mesoliittinen_kausi",
    wikidata_id: "Q44155",
    summary_en: "Seasonal mountain foragers of the Alps, Pyrenees, Zagros, and Taurus ranges who established high-altitude camps to hunt ibex, red deer, and marmots following summer snowmelt.",
    summary_fi: "Alppien, Pyreneiden ja Zagrosvuorten kausiluonteiset ylänkömetsästäjät, jotka pystyttivät leirejä korkealle vuoristoon vuohien, peurojen ja murmeleiden metsästystä varten.",
    capital: "Alpine and Zagros rock shelter sites",
    feature_name_matches: ["Highland Mesolithic Hunter-Foragers"]
  },
  {
    slug: "steppe-mesolithic-foragers",
    name: "Steppe Mesolithic Hunter-Foragers",
    name_fi: "Aron mesoliittiset metsästäjä-keräilijät",
    native_name: "Steppe Mesolithic",
    alternate_names: ["Steppe Mesolithic Hunter-Foragers"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Pontic-Caspian Steppe Mesolithic Complex",
    year_start: -8500,
    year_end: -5200,
    period_label: "8500 BCE – 5200 BCE",
    period_label_fi: "8500 eaa. – 5200 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Eastern_Hunter-Gatherer",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/It%C3%A4iset_mets%C3%A4st%C3%A4j%C3%A4-ker%C3%A4ilij%C3%A4t",
    wikidata_id: "Q28135805",
    summary_en: "Eastern Hunter-Gatherer (EHG) societies of the open Eurasian steppes and river corridors between the Dnieper and Volga, skilled archers hunting aurochs, wild horses, and saiga antelope.",
    summary_fi: "Euraasian arokäytävien itäiset metsästäjä-keräilijät (EHG) Dneprin ja Volgan välillä; taitavia jousiampujia, jotka metsästivät alkuhärkiä, villihevosia ja saiga-antilooppeja.",
    capital: "Pontic-Caspian steppe camps",
    feature_name_matches: ["Steppe Mesolithic Hunter-Foragers"]
  },
  {
    slug: "shellfish-gatherers-midden-cultures",
    name: "Shell Midden & Shellfish Gatherers",
    name_fi: "Simpukankerääjät ja tunkioiden rannikkokulttuurit",
    native_name: "Shell Midden Gatherers",
    alternate_names: ["Shellfish gatherers", "Ertebølle", "Asturian"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Global Littoral Marine Adaptation",
    year_start: -7000,
    year_end: -3000,
    period_label: "7000 BCE – 3000 BCE",
    period_label_fi: "7000 eaa. – 3000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Midden",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Tunkio",
    wikidata_id: "Q836371",
    summary_en: "Coastal and estuarine foraging societies worldwide who created massive shell middens (køkkenmøddinger), exploiting oysters, mussels, clams, and marine fish alongside seal hunting.",
    summary_fi: "Rannikoiden ja estuaarien keräilijäkansat ympäri maailmaa, jotka jättivät jälkeensä valtavia simpukankuorikumpuja (køkkenmødding) ja hyödynsivät merellisiä ravintovaroja.",
    capital: "Ertebølle, Tagus, and global coastal middens",
    feature_name_matches: ["Shellfish gatherers"]
  },
  {
    slug: "patagonian-marine-hunters",
    name: "Patagonian & Fuegian Shellfish & Marine Mammal Hunters",
    name_fi: "Patagonian ja Tulimaan merinisäkkäiden metsästäjät",
    native_name: "Yaghan / Kawésqar / Chono",
    alternate_names: ["Patagonian shellfish and marine mammal hunters", "Fuegians"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "south-american-indigenous",
    historical_period: "Subantarctic Maritime Canoe Societies",
    year_start: -5000,
    year_end: 1900,
    period_label: "5000 BCE – 1900 CE",
    period_label_fi: "5000 eaa. – 1900 jaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Yaghan_people",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Jaganit",
    wikidata_id: "Q577317",
    summary_en: "Nomadic canoe peoples (Yaghan and Kawésqar) of the treacherous subantarctic fjords and Cape Horn archipelago, hunting sea lions, whales, and diving for shellfish in frigid waters.",
    summary_fi: "Tulimaan ja Kap Hornin vuonojen kanoottikansat (jaganit ja kawésqarit), jotka metsästivät merileijonia ja valaita ja sukelsivat simpukoita kylmissä subantarktisissa vesissä.",
    capital: "Beagle Channel and Cape Horn settlements",
    feature_name_matches: ["Patagonian shellfish and marine mammal hunters"]
  },

  // Neolithic & Chalcolithic Civilizations
  {
    slug: "levantine-corridor-neolithic",
    name: "Levantine Corridor (Early Neolithic Farmers)",
    name_fi: "Levantin käytävän varhaisneoliittiset maanviljelijät",
    native_name: "PPNA / PPNB Levant",
    alternate_names: ["Levantine Corridor (Neolithic Farmers)", "Natufian", "Pre-Pottery Neolithic"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Agricultural Revolution in the Fertile Crescent",
    year_start: -10000,
    year_end: -6000,
    period_label: "10,000 BCE – 6000 BCE",
    period_label_fi: "10 000 eaa. – 6000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Pre-Pottery_Neolithic",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Esikeraaminen_neoliittinen_kausi",
    wikidata_id: "Q677795",
    summary_en: "Cradle of early agriculture in the Jordan Rift Valley and Upper Levant where humans first domesticated emmer wheat, barley, goats, and sheep, erecting monumental round stone towers at Jericho.",
    summary_fi: "Varhaisen maanviljelyn kehto Jordanin hautavajoamassa ja Levantissa, missä vehnä, ohra ja lampaat kesytettiin ensimmäisenä ja Jerikoon rakennettiin muinaisia pyöreitä kivitorneja.",
    capital: "Jericho (Tell es-Sultan), 'Ain Ghazal, Göbekli Tepe",
    feature_name_matches: ["Levantine Corridor (Neolithic Farmers)"]
  },
  {
    slug: "neolithic-farmers-horizon",
    name: "Old World Neolithic Pioneer Farmers",
    name_fi: "Vanhan maailman neoliittiset maanviljelijät",
    native_name: "Neolithic Farmers",
    alternate_names: ["Neolithic Farmers", "Early European Farmers"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "prehistoric",
    historical_period: "Expansion of Agriculture across West Asia and Europe",
    year_start: -7500,
    year_end: -3500,
    period_label: "7500 BCE – 3500 BCE",
    period_label_fi: "7500 eaa. – 3500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Neolithic",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Neoliittinen_kausi",
    wikidata_id: "Q25456",
    summary_en: "Early agrarian communities that spread farming technologies, polished stone tools, pottery, and permanent village settlements from Anatolia across the Mediterranean and mainland Europe.",
    summary_fi: "Varhaiset maanviljelijäyhteisöt, jotka levittivät karjankasvatusta, keramiikkaa ja kyliä Anatoliasta Välimerelle ja Keski-Eurooppaan muuttaen ihmiskunnan elintavan pysyvästi.",
    capital: "Çatalhöyük, Nea Nikomedeia",
    feature_name_matches: ["Neolithic Farmers"]
  },
  {
    slug: "ghassulian-culture",
    name: "Ghassulian Culture",
    name_fi: "Ghassulin kulttuuri",
    native_name: "Ghassulian",
    alternate_names: ["Ghassul", "Teleilat el-Ghassul"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "levant",
    historical_period: "Chalcolithic Southern Levant",
    year_start: -4400,
    year_end: -3500,
    period_label: "4400 BCE – 3500 BCE",
    period_label_fi: "4400 eaa. – 3500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Ghassulian",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Ghassulin_kulttuuri",
    wikidata_id: "Q2636262",
    summary_en: "Chalcolithic archaeological culture in the southern Levant known for polyhedral mudbrick houses, advanced copper metallurgy (Nahal Mishmar treasure hoard), and polychrome frescoes of eight-pointed stars.",
    summary_fi: "Kuparikautinen kulttuuri eteläisessä Levantissa Jordan-joen laaksossa; tunnettu Nahal Mishmarin häikäisevästä kupariaarteesta ja geometrisista seinämaalauksistaan.",
    capital: "Teleilat el-Ghassul",
    feature_name_matches: ["Ghassul"]
  },
  {
    slug: "naqada-i-culture",
    name: "Naqada I Culture (Amratian)",
    name_fi: "Naqada I -kulttuuri (Amratian)",
    native_name: "Naqada I / Amratian",
    alternate_names: ["Naquada I", "Naqada I"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "egypt",
    historical_period: "Predynastic Upper Egypt",
    year_start: -4000,
    year_end: -3500,
    period_label: "4000 BCE – 3500 BCE",
    period_label_fi: "4000 eaa. – 3500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Amratian_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Naqadan_kulttuuri",
    wikidata_id: "Q477382",
    summary_en: "Predynastic Upper Egyptian archaeological culture recognized for black-topped red terracotta pottery, carved basalt cosmetic palettes, and ivory figurines that laid foundations for Pharaonic civilization.",
    summary_fi: "Esidynastinen Ylä-Egyptin kulttuuri, joka tunnetaan mustareunaisesta punakeramiikastaan, kosmetiikkapaleteistaan ja norsunluuveistoksistaan, jotka loivat pohjan faaraoiden valtakunnalle.",
    capital: "Naqada (Nubt), el-Amra, Hierakonpolis",
    feature_name_matches: ["Naquada I"]
  },
  {
    slug: "dimini-culture",
    name: "Dimini Culture",
    name_fi: "Diminin kulttuuri",
    native_name: "Διμήνι / Dimini",
    alternate_names: ["Dimini"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "greco-roman",
    historical_period: "Late Neolithic Thessaly",
    year_start: -4800,
    year_end: -4000,
    period_label: "4800 BCE – 4000 BCE",
    period_label_fi: "4800 eaa. – 4000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Dimini",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Dim%C3%ADni",
    wikidata_id: "Q1225881",
    summary_en: "Late Neolithic settlement in Thessaly, Greece, famed for concentric stone defense walls, an imposing central megaron chieftain hall, and intricate polychrome pottery with spiral and meander patterns.",
    summary_fi: "Myöhäisneoliittinen asutuskeskus Thessaliassa Kreikassa, joka tunnetaan sisäkkäisistä kivimuureistaan, keskusmegaronistaan ja spiraalikuvioisesta keramiikastaan.",
    capital: "Dimini (Pagasetic Gulf)",
    feature_name_matches: ["Dimini"]
  },
  {
    slug: "stentinello-culture",
    name: "Stentinello Culture",
    name_fi: "Stentinellon kulttuuri",
    native_name: "Cultura di Stentinello",
    alternate_names: ["Stentinello culture"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "italy",
    historical_period: "Middle Neolithic Sicily & Calabria",
    year_start: -5000,
    year_end: -4000,
    period_label: "5000 BCE – 4000 BCE",
    period_label_fi: "5000 eaa. – 4000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Stentinello_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Sisilian_esihistoria",
    wikidata_id: "Q1447039",
    summary_en: "Neolithic agricultural culture of Sicily and Calabria centered near Syracuse, fortified by rock-cut defensive ditches and celebrated for cardium-impressed pottery and Lipari obsidian blade trading.",
    summary_fi: "Neoliittinen viljelykulttuuri Sisiliassa ja Calabriassa; suojasi kyliään kallioon louhituilla vallikaivannoilla ja kävi vilkasta Liparisaarten obsidiaanin kauppaa.",
    capital: "Stentinello (Syracuse)",
    feature_name_matches: ["Stentinello culture"]
  },
  {
    slug: "la-almagra-culture",
    name: "La Almagra Culture",
    name_fi: "La Almagran kulttuuri",
    native_name: "Cultura de la cerámica a la almagra",
    alternate_names: ["La Almagra culture"],
    culture_group: "Prehistoric & Archaeological",
    lineage_id: "spain",
    historical_period: "Early Neolithic Andalusia",
    year_start: -5500,
    year_end: -4000,
    period_label: "5500 BCE – 4000 BCE",
    period_label_fi: "5500 eaa. – 4000 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Prehistory_of_the_Iberian_Peninsula",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Iberian_esihistoria",
    wikidata_id: "Q1200547",
    summary_en: "Early Neolithic culture of southern Spain (Andalusia) recognized for distinctive red-slipped ceramic vessels coated in ochre/almagra and burnished, associated with cave dwellings and early cereal farming.",
    summary_fi: "Varhaisneoliittinen andalusialainen kulttuuri Etelä-Espanjassa; tunnettu punaisella okralla (almagra) kiillotetusta keramiikastaan ja varhaisesta luola-asutuksesta.",
    capital: "Cueva de los Murciélagos, Andalusia",
    feature_name_matches: ["La Almagra culture"]
  },

  // Western & Central Europe Prehistoric Complexes
  {
    slug: "funnelbeaker-culture",
    name: "Funnelbeaker Culture (TRB)",
    name_fi: "Suppilopikarikulttuuri (TRB)",
    native_name: "Trichterbecherkultur (TRB)",
    alternate_names: ["Funnel-Beaker", "TRB"],
    culture_group: "Western & Central Europe",
    lineage_id: "prehistoric",
    historical_period: "Neolithic Megalithic Builders of Northern Europe",
    year_start: -4300,
    year_end: -2800,
    period_label: "4300 BCE – 2800 BCE",
    period_label_fi: "4300 eaa. – 2800 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Funnelbeaker_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Suppilopikarikulttuuri",
    wikidata_id: "Q644142",
    summary_en: "Major Neolithic culture of Northern and Central Europe (Scandinavia, Germany, Poland, Netherlands) named for funnel-necked beakers and responsible for monumental megalithic passage graves and dolmens.",
    summary_fi: "Pohjois- ja Keski-Euroopan suuri neoliittinen kulttuuri, joka nimettiin suppilokaulaisista savipikareistaan ja joka rakensi monumentaalisia megaliitti- ja käytävähautoja (dolmeneita).",
    capital: "Northern European megalithic ritual centers",
    feature_name_matches: ["Funnel-Beaker"]
  },
  {
    slug: "nordic-bronze-age",
    name: "Nordic Bronze Age Culture",
    name_fi: "Pohjolan pronssikauden kulttuuri",
    native_name: "Nordic Bronze Age",
    alternate_names: ["N. European Bronze Age cultures", "Nordic Bronze Age"],
    culture_group: "Western & Central Europe",
    lineage_id: "nordic",
    historical_period: "Bronze Age Scandinavia & Baltic",
    year_start: -1700,
    year_end: -500,
    period_label: "1700 BCE – 500 BCE",
    period_label_fi: "1700 eaa. – 500 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Nordic_Bronze_Age",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Skandinavian_pronssikausi",
    wikidata_id: "Q844119",
    summary_en: "Rich prehistoric Scandinavian culture renowned for solar worship (Trundholm sun chariot), curved bronze horns (lurs), elaborate ship rock carvings (petroglyphs), and long-distance amber-bronze trading.",
    summary_fi: "Rikas skandinaavinen pronssikauden kulttuuri, joka tunnetaan aurinkokultistaan (Trundholmin aurinkovaunut), pronssilureistaan, kalliopiirroksistaan ja meripihkan kaupasta Keski-Eurooppaan.",
    capital: "Tanum, Kivik king's grave, Trundholm",
    feature_name_matches: ["N. European Bronze Age cultures"]
  },
  {
    slug: "unetice-culture",
    name: "Únětice Culture",
    name_fi: "Úněticen kulttuuri",
    native_name: "Únětická kultura",
    alternate_names: ["Únětice", "Unetice"],
    culture_group: "Western & Central Europe",
    lineage_id: "central-europe",
    historical_period: "Early Bronze Age Central Europe",
    year_start: -2300,
    year_end: -1600,
    period_label: "2300 BCE – 1600 BCE",
    period_label_fi: "2300 eaa. – 1600 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/%C3%9An%C4%9Btice_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/%C3%9An%C4%9Bticen_kulttuuri",
    wikidata_id: "Q937747",
    summary_en: "Early Bronze Age culture centered in Bohemia, Moravia, and Central Germany, internationally famous for advanced bronze metallurgy, triangular daggers, ingots, and the astronomical Nebra sky disk.",
    summary_fi: "Varhaispronssikauden kulttuuri Böömissä, Määrissä ja Keski-Saksassa; tunnettu edistyneestä metallurgiastaan, kolmikulmaisista tikareistaan ja Nebran taivaskiekosta.",
    capital: "Únětice (Prague), Leubingen, Nebra",
    feature_name_matches: ["Únětice"]
  },
  {
    slug: "urnfield-culture",
    name: "Urnfield Culture",
    name_fi: "Uurnakenttäkulttuuri",
    native_name: "Urnenfelderkultur",
    alternate_names: ["Urnfield cultures", "Urnfield"],
    culture_group: "Western & Central Europe",
    lineage_id: "central-europe",
    historical_period: "Late Bronze Age Central Europe",
    year_start: -1300,
    year_end: -750,
    period_label: "1300 BCE – 750 BCE",
    period_label_fi: "1300 eaa. – 750 eaa.",
    wikipedia_url_en: "https://en.wikipedia.org/wiki/Urnfield_culture",
    wikipedia_url_fi: "https://fi.wikipedia.org/wiki/Uurnakentt%C3%A4kulttuuri",
    wikidata_id: "Q221959",
    summary_en: "Late Bronze Age European cultural complex characterized by cremation burials in ceramic urns clustered in vast cemeteries, hillfort architecture, and ancestral roots of Hallstatt Celtic societies.",
    summary_fi: "Keski-Euroopan myöhäispronssikauden kulttuuri, jolle olivat tyypillisiä saviuurniin haudatut polttohautaukset laajoilla hautakentillä; toimi kelttiläisen Hallstattin kulttuurin edeltäjänä.",
    capital: "Danubian fortified hillforts",
    feature_name_matches: ["Urnfield cultures"]
  }
]

const outPath = path.resolve(__dirname, "../data-sources/batches/prehistoric-archaeological.json")
fs.writeFileSync(outPath, JSON.stringify(PREHISTORIC_CULTURES, null, 2), "utf-8")
console.log(`✓ Wrote ${PREHISTORIC_CULTURES.length} cultures to ${outPath}`)

const allMatches = new Set(PREHISTORIC_CULTURES.flatMap(c => c.feature_name_matches))
console.log(`Total unique matched names: ${allMatches.size}`)
